---
output:
  md_document:
    variant: markdown_github
---

ダウンロードしたことすら忘れるので、ダウンロードした (眠っていた) 論文とそのひとことメモ

- `低/中/高`は優先度
    - `摘`は要旨のみ
    - `概`はざっと目を通したうえで、必要ないと判断したもの
    - `無`は現時点で(自分にとって)読む必要がないもの
- `引`は引用に使いそうなもの
- `未刊`はin press
- `未取得`はダウンロードしていないもの
- `有償`はアクセス権がなくて有償なもの、おもに書籍
- 文字: Research article
- <FONT color="green">文字</FONT>: Review article
- <FONT color="blue">文字</FONT>: Meta analysis
- <FONT color="cyan">文字</FONT>: Other article without data

アクセスできないリスト

- 東大
    - HortScience
    - HortTechnology
    - J ASHS

- 山口大
    - Funct Plant Biol (契約なし)
    - Nature Plants (契約なし)
    - Philos Trans R Soc (契約なし)
    - Plant Cell (刊行後しばらくアクセス権なし)
    - Plant Cell Physiol (刊行後しばらくアクセス権なし)

```{r, eval = F}
library(rvest)
library(magrittr)
library(tidyverse)

data_html <-
  "https://github.com/KeachMurakami/KeachMurakami.github.io/blob/master/_supplemental/Literatures.Rmd" %>%
  read_html

num_paper <-
  data_html %>%
  html_nodes("article") %>%
  html_nodes(xpath = "//ul//li//p//a")
  # html_nodes("p") %>%
  html_structure()

```


-----

- 2017

    - 01

        - 19

            1. [Gimenez-Ibanez et al. 2017; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.14354/abstract); 無
                - JAZ2 controls stomata dynamics during bacterial invasion
                - バクテリアの感染と気孔開度の調節の仕組みに関して
                - 感染で一度閉じた気孔を、Coronatineというphytotoxinにより再度開かせる
                - 後輩に投げつける

            2. [de Vries et al. 2017; Trends Plant Sci](http://www.sciencedirect.com/science/article/pii/S1360138516302060); <FONT color="cyan">高</FONT>
                - Dynamic Plant–Plant– Herbivore Interactions Govern Plant Growth–Defence
Integration
                - 光獲得と対被食のトレードオフに関して
                - R/FR比がメイン


        - 20

            3. [Ballaré & Pierik 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12914/abstract); <FONT color="green">高・未刊</FONT>
                - The shade avoidance syndrome: Multiple signals and ecological consequences
                - “syndrome”ってつけるとキャッチーだ

            4. [Uematsu et al. 2017; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.14416/abstract); <FONT color="grey">無</FONT>
                - Foliar uptake of radiocaesium from irrigation water by paddy rice (*Oryza sativa*): an overlooked pathway in contaminated environments
                - いつか出してやると思っている*New Phytologist*に、研究科の元先輩がacceptされていたので記念に
                - 水田イネへの放射性セシウムの吸い上げについて


        - 21

            5. [Wientjes et al. 2017; BBA](http://www.sciencedirect.com/science/article/pii/S0005272817300099?np=y); 中
                - Imaging the Photosystem I/Photosystem II chlorophyll ratio inside the leaf
                - 画像解析 & 蛍光寿命解析でPSII/PSI比を面的に
                - 以下の`Iermak et al. 2016`の発展

            6. [Iermak et al. 2016; BBA](http://www.sciencedirect.com/science/article/pii/S0005272816305564); 20170121済
                - Visualizing heterogeneity of photosynthetic properties of plant leaves with two-photon fluorescence lifetime imaging microscopy
                - `Wientjes et al. 2017`から
                - two-photonとFLIMで深度情報まで考慮して光化学系組成を解析
                    - 厳密には、LCHII/PSII比とPSII/PSI比
                    - PSII/PSIエネルギー分配の絶対定量はできない
                - 見逃してたので、投稿論文に追加する？


        - 24

            7. [Galvão & Fankhauser 2015; Curr Opin Neurobiol](http://www.sciencedirect.com/science/article/pii/S0959438815000227); <FONT color="green">低</FONT>
                - Sensing the light environment in plants: photoreceptors and early signaling steps
                - 植物の光センシングに関する異分野への概説系レビュー
                - Chemical寄り

            8. [Razzak et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12921/abstract); 高
                - Differential response of Scots pine seedlings to variable intensity and ratio of R and FR light
                - ヨーロッパアカマツ苗の光強度 x R/FR比への応答
                - 胚軸長、色素蓄積など
                - 被子植物・裸子植物の差異を絡めている
                - abstractだとPCEに載るほどのものはない印象を受けるが...なにかあるんだろう


        - 25

            9. [Morena et al. 2017; J Photochem Photobiol B](http://www.sciencedirect.com/science/article/pii/S1011134416309733); 低・未刊
                - *In vitro* antimicrobial activity of LED irradiation on *Pseudomonas aeruginosa*
                - 長波長 (980 nm) LED光での*Pseudomonas aeruginosa* (緑膿菌) 繁殖の抑制
                - 口腔衛生、小児科学などの人たち

            10. [Munafò et al. 2017; Nat Hum Behav](http://www.nature.com/articles/s41562-016-0021); <FONT color="green">高</FONT>
                - A manifesto for reproducible science
                - 再現性の担保について
                    - *P*-hackingとか、そのあたり
                    - 去年のASAのstar-counting 統計の批判以来、流行っている
                    - *eLife*でも特集されてた
                        - [ココ](https://elifesciences.org/content/6/e23693)らへん
                        - 癌研究だとか、生体の実験でRCTだときついだろう
                - 探索的な研究だと仕方ない側面もあるよね、と思いつつ、着々と脱検定を進めている

            11. [Shirai et al. 2017; J Food Eng](http://www.sciencedirect.com/science/article/pii/S0260877416303739); <FONT color="grey">無</FONT>
                - Penetration of aerobic bacteria into meat: A mechanistic understanding
                - 食肉の表面から内部へのバクテリアの侵入のモデル化
                - 博士の公開審査で聞いたので
                - 「鉛直プロファイルの*in vivo*値とモデル推定値を比較していないのですか」という質問は、まっとうだけどしんどい


        - 26

            12. [Izumi et al. 2017; Plant Cell](http://www.plantcell.org/content/early/2017/01/25/tpc.16.00637.short?rss=1); 無・未刊
                - Entire Photodamaged Chloroplasts Are Transported to the Central Vacuole by Autophagy
                - chlorophagyなるフレーズ
                - photodamageを受けた葉緑体が液胞中心に移動する
                - 「移動して、そのあとどうなる」が意図的に書かれていなさそう

            13. [Kono et al. 2017; PCP](https://academic.oup.com/pcp/article/doi/10.1093/pcp/pcw215/2948616/Photoprotection-of-PSI-by-Far-Red-Light-Against); 20170803済
                - Photoprotection of PSI by Far-Red Light Against the Fluctuating Light-Induced Photoinhibition in Arabidopsis thaliana and Field-Grown Plants
                - FRで変動光下でのPSI阻害が抑制できる話
                - 内容は既知のものなので、引用されている文献など、知識収集メインで読むべし
                - 20170803読んだ
                - PSIの回復が遅い話の文献
                    - “... once PSI is damaged, repair and/or de novo PSI syn- thesis are very slow (Kudoh and Sonoike 2002)”
                - NDH-CEF経路を潰すと、FRでの光防御の恩恵が得られない
                    - NDH-CEFが恒常的に低fluxであるっぽくて、FR照射に関連した何か (例えばリン酸化で切り離しとか) で切り替えられるbufferみたいになってるのかなぁ
                    - 釈然としないが、経過観察
                - CEFだと、結局のところ光エネルギーは消費できてもP700+を還元して落ち着かせられない (またまわってくるから) のでP700<sup>+</sup>のNPQの作用が重要だろう、という話
                    - PSIIのNPQ誘導でinflux自体を下げれば、問題なくなるから、CEFだけでも持つのでは？と思う
                    - Redoxの経時のイメージが重要な気がする
                    - ここらへんはsystems biologyっぽく全体を一気に捉えないときつい = ぼくが個人レベルでできるような研究ではないので、パス
                    - ややステップ幅が広く、行間を補完しながら読む必要のあるDiscussionである


        - 28

            14. [Riikonen 2017; Forest Ecol Manag](http://www.sciencedirect.com/science/article/pii/S0378112716311173); 20170128済
                - Content of far-red light in supplemental light modified characteristics related to drought tolerance and post-planting growth in Scots pine seedlings
                - アカマツの苗木にFR添加したときの耐乾燥性とその後の成長
                - *in situ*水利用効率 (*P*<sub>n</sub>/*g*<sub>s</sub>) をRGB光源で測定した値で議論
                    - *in situ*な光 (=太陽光) のもとでは？
                    - 典型的な栽培光x測定光の交互作用問題
                - GLMMで、`ORIG x FR`項の係数を水準ごとに解析できるようダミー変数でバラすテクニック
                    - TS先生に今度あったときに話そう

            15. [Pierik & de Wit 2014; JXB](https://academic.oup.com/jxb/article-lookup/doi/10.1093/jxb/ert389); <FONT color="green">低</FONT>
                - Shade avoidance: phytochrome signalling and other aboveground neighbour detection cues
                - 群落の成長に伴うR/FRの変化と、その他の光質・物理的接触・VOCと関連付けてレビュー

            16. [Cocetta et al. 2017; BookChap](http://link.springer.com/article/10.1140/epjp/i2017-11298-x); <FONT color="green">低・有償</FONT>
                - Light use efficiency for vegetables production in protected and indoor environments
                - 37.75 euro
                - D論周りとぴったしだけど、引用文献を見るにあまり得るものはなさそう...?
                - 年度末に学振の研究遂行経費が残っていれば落とす

        - 30

            17. [Geigenberger et al. 2017; Trend Plant Sci](http://www.sciencedirect.com/science/article/pii/S1360138516302217); <FONT color="green">中・未刊</FONT>
                - The Unprecedented Versatility of the Plant Thioredoxin System
                - Redoxといえばthioredoxin見たいな感じがあるので読んでおこう

            18. [Endo et al. 1999; FEBS Letters](http://onlinelibrary.wiley.com/wol1/doi/10.1016/S0014-5793(99)00989-8/full); 20170130済
                - The role of chloroplastic NAD(P)H dehydrogenase in photoprotection
                - NDHが強光に対するphotoprotectionとして機能していることを主張
                    - 他にはあまりNDH-CEF単体で効いている話がないので、解釈が難しい
                - MV添加でPSI donorを作ると、ΔndhBでもPSIの励起が抑えられるから、NDH-CEF-PSIが効いてる
                - いまNDH-光阻害界隈がどうなってるのかはしっかり追えてないが、さほど効果的な防御システムになっているとは考えられていない (と思う, `Nawrocki et al. (2015)`とか)
                    - Nawrockiはこれ引いてないな...

            19. [Heyno et al. 2014; Phil Trans R Soc Lond B](http://rstb.royalsocietypublishing.org/content/369/1640/20130228); 20170130済
                - Putative role of the malate valve enzyme NADP–malate dehydrogenase in H<sub>2</sub>O<sub>2</sub> signalling in *Arabidopsis*
                - `Geigenberger et al. (2017)`をつらつら読んでいて引っかかったので
                - Malate valveでのNADP-malate-DHがH<sub>2</sub>O<sub>2</sub>経由のシグナリングとリンクしている
                    - 因果関係をダイレクトに示すものではないように思うが
                - Supporting Tableの1より大きいphi(II)とは...

        - 31

            20. [星野・岡田 2006; J Natl Inst Public Health](https://www.niph.go.jp/journal/data/55-3/j55-3.html); <FONT color="green">低</FONT>
                - 傾向スコアを用いた共変量調整による因果効果の推定と臨床医学・疫学・薬学・公衆衛生分野での応用について
                - `岩波DS Vol. 3`から

            21. [丹後 2000; J Natl Inst Public Health](https://www.niph.go.jp/journal/data/49-4/j49-4.html); <FONT color="green">20170131済</FONT>
                - 良質の根拠を生む randomization の本質 ー科学研究者としてのセンスー
                - `星野・岡田 (2006)`の引用文献をちら見して
                - 標準化・ルール整備が重要
                - 実験条件を“揃える”の定義は分野によるのがなんとも
                    - 生態学の`Hurlbert (1984)`は、“揃える”によりシビア
                    - 「条件」を受ける時間が長いと、微差を気にする必要があるから
                    - その基準は主観

            22. [Gerszberg & Hnatuszko-Konka 2017; Plant Growth Regul](http://link.springer.com/article/10.1007/s10725-017-0251-x); <FONT color="green">低</FONT>
                - Tomato tolerance to abiotic stress: a review of most often engineered target sequences
                - 非生物耐性のレビュー

    - 02

        - 01

            23. [Cai et al. 2017; J Photochem Photobiol B](http://www.sciencedirect.com/science/article/pii/S101113441631065X); 20170201済
                - The water-water cycle is a major electron sink in *Camellia* species when CO<sub>2</sub> assimilation is restricted
                - ツバキ３品種のAEF活性について
                    - ツバキはなぜか赤青光下で速やかに気孔が閉じる
                - WWCが強光かつ低*P*<sub>n</sub>条件 (光呼吸条件) で重要になる
                    1. 気孔が閉じてCO<sub>2</sub>供給が遅れる (これはツバキでユニークっぽい)
                    2. *V*<sub>o</sub>/*V*<sub>c</sub>が上がる
                    3. ATP/NADPH要求が増える (*V*<sub>o</sub>だと1.5, *V*<sub>c</sub>だと1.75なので)
                    4. WWCでNADPH生産を減らす
                - 実験・議論ともエレガントで明快

            24. [Nishikawa et al. 2012; PCP](https://academic.oup.com/pcp/article-lookup/doi/10.1093/pcp/pcs153); 20170202済
                - PGR5-Dependent Cyclic Electron Transport Around PSI Contributes to the Redox Homeostasis in Chloroplasts Rather Than CO<sub>2</sub> Fixation and Biomass Production in Rice
                - `Cai et al. 2017`が`Yamori et al. 2015; Sci Rep`と並べて低PFDでのCEF-PSIをサポートするとして引用していたので
                    - *pgr5*欠損は、強光下での*P*<sub>n</sub>も小さくしている (有意差はないけど)
                    - *pgr5*欠損は、とくに強光下でpmf (ECS解析) を低下させる
                    - やや強引な引用なのではないか...?

            25. [Williamson 2007; Nutrition Bulletin](http://onlinelibrary.wiley.com/doi/10.1111/j.1467-3010.2007.00628.x/abstract); <FONT color="green">無</FONT>
                - Is organic food better for our health?
                - まっとうな研究としてまっとうな研究者の本で引用されていたので、気になって
                - ニュートラル・客観的な論調
        - 02

            26. [園池 2012; 光合成研究](http://photosyn.jp/journal.html#64); 20170202済
                - 果実の光合成
                - 文章に優しさが溢れている

        - 03

            27. [Shimakawa et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/02/02/pp.16.01038.short?rss=1); 低・未刊
                - The liverwort, *Marchantia*, drives alternative electron flow using a flavodiiron protein to protect PSI
                - cyanobacteria同様、ゼニゴケにもFLV経由のAEFがあり、PSIを保護する
                - 高等植物ではFLV経路が機能しないので、自分にとって必要という感じではない
                - このグループは勢いが凄まじい

            28. [Chaux et al. 2015; Front Plant Sci](http://journal.frontiersin.org/article/10.3389/fpls.2015.00875/full); <FONT color="green">20170202済</FONT>
                - A security network in PSI photoprotection: regulation of photosynthetic control, NPQ and O<sub>2</sub> photoreduction by cyclic electron flow
                - “photosynthetic control”をテクニカルタームとして使っているが、流行らない気がする
                - Cyt *b*<sub>6</sub>*f*の制御というよりはPSIの収率の制御だと、自分は思っている

            29. [Joliot & Johnson 2011; PNAS](http://www.sciencedirect.com/science/article/pii/S0005272808000972); 20170203済 (再)
                - Regulation of cyclic and linear electron flow in higher plants
                - arabidopsisでCEFモードの起動・終了の時間を議論
                    - 起動は20秒程度の飽和赤色光で十分
                    - 終了の1/2tはdarkで20秒程度
                - 光化学反応の時定数 *k*<sub>psii</sub> を定量する話は[Joliot & Joliot 2008; BBA](http://www.sciencedirect.com/science/article/pii/S0005272808000972)
                - 励起エネルギー分配との区分にやや困る
                - 非常にエレガントな論文だと再読して気づく

        - 04

            30. [Zhang et al. 2017; Comput Electron Agric ](http://www.sciencedirect.com/science/article/pii/S0168169917300820); 無
                - Leaf image based cucumber disease recognition using sparse representation classification
                - Sparse modelかと思ったら違った
                - 可視障害の病斑箇所をK-meansでクラスタ分析して、そのパターンからSparse representationで障害の種類を診断
                - 生データを出せば病斑認識データセットとしてよく引用されそうだけども...
                - この雑誌をほとんど見たことがなかったけど、好みなのでフォロー

            31. [Dang et al. 2014; Plant Cell](http://www.plantcell.org/content/26/7/3036.abstract); 20170205済
                - Combined Increases in Mitochondrial Cooperation and Oxygen Photoreduction Compensate for Deficiency in Cyclic Electron Flow in *Chlamydomonas reinhardtii*
                - WTと*pgr*5の電子伝達のPFD・CO<sub>2</sub>応答を網羅的に解析している労力が凄まじい研究
                - 根底には、「PGR-CEFの欠損によりATP不足がWTよりさらに厳しい状態で、電子伝達はどう対応しているのか？」がある
                - Malate valve (mitorespiration) とO<sub>2</sub>還元 (FLV・Mehler) がATP不足をサポートする
                - *pgr*5はRCIを減らして系I結合LHCIIを増やしている...？
                - 変動光下ではやっぱり成育阻害が起こる
                - Ruuska、Drieverあたりでも思ったがMIMSいいな

        - 06

            32. [Li et al. 2017; Plant Physiol](http://www.plantcell.org/content/early/2017/01/30/tpc.16.00768.short?rss=1); 低・未刊
                - Protein Degradation Rate in Arabidopsis thaliana Leaf Growth and Development
                - タンパク分解をsystems biologyっぽく

            33. [Atherton et al. 2016; Remote Sens Environ](http://www.sciencedirect.com/science/article/pii/S0034425715302571); 低
                - Using Spectral Chlorophyll Fluorescence and the Photochemical Reflectance Index to Predict Physiological Dynamics
                - リモートセンシング系雑誌をまったくカバーしていなかったので、feedを集め始めた
                - 簡単には読めないが、

            34. [Bailleul et al. 2010; Photosynth Res](http://link.springer.com/article/10.1007/s11120-010-9579-z); <FONT color="green">20170206済 (再)</FONT>
                - Electrochromism: a useful probe to study algal photosynthesis
                - ECS解析のレビュー (ECSの知識はほぼこれのみ)
        - 07

            35. [Feild et al. 1998; Plant Physiol](http://www.plantphysiol.org/content/116/4/1209.long); 20170207済
                - Nonphotochemical Reduction of the Plastoquinone Pool in Sunflower Leaves Originates from Chlororespiration
                - *F*<sub>o</sub>と阻害剤を多用した暗条件下でのchlororesprationの挙動の解析
                - ヒマワリのpreincubation条件を振って、postilluminationでdark下での*F*<sub>o</sub>を観察
                    - illuminationが10 min 1000 µmol m<sup>-2</sup> s<sup>-1</sup>なのにそれにincubation条件がキャンセルされないのが新鮮
                - この論文のchlororespirationのターンオーバ速度を、0.1 mmolChl m<sup>-2</sup>でフラックスに換算すると、mmole<sup>-1</sup> molChl<sup>-1</sup> s<sup>-1</sup> ~ 10<sup>-1</sup> µmole<sup>-1</sup> m<sup>-2</sup> s<sup>-1</sup>で、暗条件でのPQへの電子伝達は、0.07 µmole<sup>-1</sup> m<sup>-2</sup> s<sup>-1</sup>程度の微弱なもの
                - rotenoneを加えてNDH経路を止めてもPQの再還元が起こる理由を、“Although this may indicate a rotenone-insensitive pathway for dark PQ reduction, it is equally likely that incomplete infiltration of rotenone into the leaves is the explanation.”と書いているが、単純にrotenone耐性の2型NDHなのでは...?
                    - 追っかければわかりそうだけど、深入りしない

        - 09

            36. [Yan et al. 2017; Global Change Biol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/gcb.13654/abstract); <FONT color="blue">低・未刊</FONT>
                - Contrasting responses of leaf stomatal characteristics to climate change: a considerable challenge to predict carbon and water cycles
                - CO<sub>2</sub>、temperature、droughtで気孔密度をメタ解析
                - 標高・時代を交絡因子として扱っているっぽい
                - メタ解析、いつかやってみたいので

        - 10

            37. [Vialet-Chabrand et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/02/09/pp.16.01767.short?rss=1); 高
                - Importance of fluctuations in light on ~~pant~~ plant photosynthetic acclimation
                - ~~タイトルがtypoってる (pantじゃなくてplantだろう、たぶん)~~治った
                - 変動光、はやってる
                - ようやくダウンロード (20170509)
                    - これはいい論文のにおいがする
                    - 変動x強光は定常x強光と比較して陰葉よりの資源利用 (厚さ・呼吸速度など) だが、PPFD-Pn<sub>area</sub>は同レベルで、PPFD-Pn<sub>mass</sub>だと有利
                        - タンパク系はあまり差なし
                    - 変動光は、光合成順化的にはよい (曖昧) こともあるが、乾物生産の面では不利
                    - ggplotのデフォルトカラーなので、色に意味をつけてほしかった (FL: 赤系・SQ: 青系とか)
                    - SE、SDじゃなくてCIで出してきたが、*n*はたぶん疑似反復だ

        - 12

            38. [Mishanin et al. 2017; Photosynth Res](http://link.springer.com/article/10.1007/s11120-017-0339-1); 20170219済
                - Acclimation of shade-tolerant and light-resistant *Tradescantia* species to growth light: chlorophyll *a* fluorescence, electron transport, and xanthophyll content
                - Tikhonovのグループ
                    - このグループも含め、なんとなくロシア・バルトあたりの論文は個人的に読みづらく感じる
                    - と思ってたらこの人のはめちゃくちゃ読みやすかったのでサンプリングバイアス
                - ツユクサの陰性・陽性を弱光(LL)・強光(HL)で栽培して光合成特性を解析
                - *F*<sub>685</sub>/*F*<sub>740</sub>比に注力
                    - NPQ・state transition・chloroplast movementの３要素に分解
                    - NPQ: 早い
                    - State transition: 中間程度
                    - chloroplast movement: *t*<sub>1/2</sub> ~ 10 min (Ptushenko et al. 2017)
                - LLだと77K蛍光ピーク強度比のstate transitionが単相だが、HLだと二相？
                - *T*<sub>light</sub>/*T*<sub>dark</sub>の絶対値の議論には意味がない
                    - *T*<sub>dark</sub>が小さい場合に安定しないので

        - 13

            39. [Michelet et al. 2013; Front Plant Sci](http://journal.frontiersin.org/article/10.3389/fpls.2013.00470/full); <FONT color="green">低</FONT>
                - Redox regulation of the Calvin–Benson cycle: something old, something new
                - カルビン回路の活性化についてレビュー
                - PQ-redoxではなく、thiore系のredox
                - `Mishanin et al. 2017`から

            40. [Mishanin et al. 2016; Photosynth Res](http://link.springer.com/article/10.1007%2Fs11120-016-0252-z); 中
                - Light acclimation of shade-tolerant and light-resistant *Tradescantia* species: induction of chlorophyll *a* fluorescence and P<sub>700</sub> photooxidation, expression of PsbS and Lhcb1 proteins
                - `Mishanin et al. 2017`から

            41. [Davis et al. 2011; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1365-3040.2011.02402.x/full); 中
                - Changes in leaf optical properties associated with light-dependent chloroplast movements
                - `Mishanin et al. 2017`から
                - 葉緑体の動きが吸収率に及ぼす影響が栽培条件で異なる話らしい
                    - “who examined how leaf anatomy in uenced chloroplast movements in 24 plant species, reported that chloroplast movement-dependent changes in leaf absorptance were greatest in shade species, in which absorptance changes of >10% were observed between HL and LL treatment”
                - あまり引用されていないので知らなかったが、良さそう

        - 15

            42. [Kawase et al. 2016; Climatic Change](http://link.springer.com/article/10.1007%2Fs10584-016-1781-3); 無
                - Enhancement of heavy daily snowfall in central Japan due to global warming as projected by large ensemble of regional climate simulations
                - 気候シナリオシンポ@つくば (2017/02/14) の発表者の論文
                - 門外漢だけどとても話が面白かったので
                - 温暖化 (海温上昇) により気象現象の極端化が進むと、日本海側の山間部で豪雪が生じる危険性がある

        - 16
            - 査読対応のため、T先生 (1985) の論文のフォロワー掘り

            43. [Vogelmann et al. 1989; Phil Trans R Soc Lond B](http://rstb.royalsocietypublishing.org/content/323/1216/411); 20170216済
                - Photosynthetic Light Gradients and Spectral Regime within Leaves of Medicago sativa
                - 細胞の集光レンズ効果の話

            44. [Pantaleoni et al. 2009; Planta](http://link.springer.com/article/10.1007/s00425-009-1004-5); 20170216済
                - Photosystem II organisation in chloroplasts of *Arum italicum* leaf depends on tissue location
                - Aroのグループ
                - 光合成系の組成を、柵状・海綿状組織に加え、葉柄柔組織 (parenchyma w/ chl)、葉柄通気組織 (aerenchyma w/o chl) で解析するやや博物学的要素が強い論文
                - State transitionとphotosystem stoichiometry以外で光分配が制御されていることを示してある
                    - 2016で引用すべきだった
                    - こっちを主題で書けばいいのに、と勝手に思う
                - この植物は部位ごとに分けるのに便利な様子
                    - “*Arum italicum* Miller (Araceae) leaf ... allows analysing separately four different photosynthetic tissues: the palisade and the spongy tissues, which form the lamina mesophyll, and the outer chlorenchyma and the inner aerenchyma, which form the petiole parenchyma”
                - 単子葉類は、PSII超複合体が不安定で、LHCII-trimerを過大評価しがち
                    - “in monocots the presence of less stable PSII supercomplexes could reduce the sensitivity of BN-PAGE analysis and lead to overestimation of the amount of LHCII trimers and misleading results (Ciambella et al. 2005)”
                - Palisade vs spongy の解析で、spongyの77K蛍光のPSI側が増えている
                    - free LHCII trimerが増えて熱放散、という解釈
                        - 2D-PAGEとも整合的
                        - preparation/77K計測までの条件で変わりそう (非NPQ形成状態でやったらstoichiometry影響が見えそう)
                    - 明快、という感じではないが、リーズナブル

            45. [Kanervo et al. 2005; Photochem Photobiol Sci ](http://pubs.rsc.org/en/content/articlelanding/2005/pp/b507866k/unauth#!divAbstract); <FONT color="green">低</FONT>
                - Functional flexibility and acclimation of the thylakoid membrane
                - Aroグループ (Pantaleoniから)
                - 知らない雑誌だ
                    - 植物率低そうだけど、一応 feed を取る

        - 17

            46. [Chow et al. 1987; Physiol Plant](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1399-3054.1987.tb06131.x/full); 20170217済・引
                - The composition and function of thylakoid membranes from pea plants grown under white or green light with or without far-red light
                - “the amounts of light-harvesting and electron transport components may be regulated by photosynthesis itself”
                - FR照射は、励起バランスが崩すのはかなり堅いはなし
                - しかし、FR照射で光合成系の組成が大きく変化する話は (知っている限り) ない
                - 自分のデータ (2016, Physiol Plant) もそうだし
                - 結局、やっぱりよくわからない部分があるなぁ

        - 20

            47. [Smirnakou et al. 2017; Front Plant Sci](http://journal.frontiersin.org/article/10.3389/fpls.2017.00188/full); 低
                - Continuous Spectrum LEDs Promote Seedling Quality Traits and Performance of *Quercus ithaburensis* var. *macrolepis*
                - タルボガシなる木の苗について
                - 調べるのが面倒だからスペクトル出してほしい...
                - 根の外観の話をするなら写真を...なんで紙媒体じゃないのにスペースをケチるのか

        - 22

            48. [Vavasseur & Raghavendra 2005; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1469-8137.2004.01276.x/full); <FONT color="green">低</FONT>
                - Guard cell metabolism and CO<sub>2</sub> sensing
                - 第二著者の本 (Photosynthesis) を裁断するにあたり、なんとなく調べた

        - 27

            49. [Motohashi & Myouga 2015; bio-protocol](http://www.bio-protocol.org/e1464); 20170227済
                - Chlorophyll Fluorescence Measurements in *Arabidopsis* Plants Using a Pulse-amplitude-modulated (PAM) Fluorometer
                - 学部生なんかへのMINI-PAMの使い方の説明によさそう
                - ただ、abstractの1文目からの`Fv = Fm ± Fo`はいかん...
                - bio-protocolは論文でいいのか...?

        - 28

            50. [Granier & Vile 2014; Curr Opin Plant Biol](http://www.sciencedirect.com/science/article/pii/S1369526614000259); 20170228済
                - Phenotyping and beyond: modelling the relationships between traits
                - phenotyping系のレビューが乱立しているような

            51. [Bos et al. 2017; BBA](http://www.sciencedirect.com/science/article/pii/S0005272817300403); 無
                - Multiple LHCII antennae can transfer energy efficiently to a single Photosystem I
                - Croce, Wientjesグループ
                - 複数のLCHIIが単一PSIへEET
                - このグループのは、ちょっともう厳しい (物理すぎて)

    - 3

        - 01

            52. [Kalaji et al. 2016; Photosynthe Res](https://link.springer.com/article/10.1007%2Fs11120-016-0318-y); <FONT color="green">低・引</FONT>
                - Frequently asked questions about chlorophyll fluorescence, the sequel
                - `Kalaji et al. 2014`の続編

            53. [Singh et al. 2017; Plant Cell Tiss Organ Cult](https://link.springer.com/article/10.1007/s11240-017-1170-2); 低
                - High light intensity stress as the limiting factor in micropropagation of sugar maple (*Acer saccharum* Marsh.)
                - PFD 3水準 x 光質 2水準で育てて2DのイメージングPAM
                - メープルは陰性植物らしい
                - “40 µmol 程度の光でも強光ストレスがあり、最適とは言えない”という結論だが、ストレスの根拠はred pigmentationであり、ダイレクトではない
                - 平行したクロロフィルの減少が、バイオマス (FW・DW) 減少につながっていないし、あまり納得できない
                - 結論ありきの研究という印象

            54. [Baerr et al. 2005; Physiol Plant](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1399-3054.2005.00506.x/abstract); 20170307済・引
                - Differential photosynthetic compensatory mechanisms exist in the *immutans* mutant of *Arabidopsis thaliana*
                - `Kanervo et al. 2005`から
                    - “the IM-knock-out mutants were recently shown to be more susceptible to photoinhibition than the wild type Arabidopsis plants”
                - この論文の意図には反しており、あまりよい引用ではない
                    - どちらかというと、「*im*、思ったより光阻害でない。でも斑入り程度によって阻害程度が異なるのは面白い。」
                    - “We found, on both a whole plant and individual leaf basis, that there were minimal differences in susceptibility to photoinhibition between im and the wild-type, as determined by the Fv/Fm ratios (Fig. 4). However, the general trend pointed towards an increased susceptibility in im, with the green sectors of the imw leaves being somewhat more susceptible than the img leaves (Fig. 4)”
                - 斑なし部 (green部) が斑入り部 (im部) の成長を補填している、という考え方

            55. [van Langevelde et al. 2017; Biol Lett](http://rsbl.royalsocietypublishing.org/content/13/3/20160874?rss=1); 無
                - Artificial night lighting inhibits feeding in moths
                - 蛾への光害

        - 02

            56. [McMillan et al. 1970; Genetics](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1212449/); 無・引
                - Quantitative Genetics of Fertility I. Lifetime Egg Production of *DROSOPHILA MELANOGASTER*---THEORETICAL
                - 上がって下がる三角形の経時パターンのモデル化
                - ショウジョウバエの産卵数

            57. [古在 2017; 植物環境工学](https://www.jstage.jst.go.jp/article/shita/29/1/29_3/_article/-char/ja/); <FONT color="cyan">201703XX済・引</FONT>
                - 植物工場研究に関する用語と単位
                - PPF vs PPFD論争は果たして...
                    - “米国園芸学会では、PPFDをPPFと表記するように求めているようだが、いずれ修正されるであろう (p. 6)”

            58. [Suga et al. 2017; Nature](http://www.nature.com/nature/journal/v543/n7643/full/nature21400.html); 無
                - Light-induced structural changes and the site of O=O bond formation in PSII caught by XFEL
                - 沈グループ (岡山)
                - 構造解析とかそこら辺は全然わからん
                - が、とりあえず落とす

            59. [Fukao 2017; Proc R Soc B](http://rspb.royalsocietypublishing.org/content/284/1850/20162650); 無
                - Vine tendrils use contact chemoreception to avoid conspecific leaves
                - 田無の農場の先生
                - この時代に単著とはすごい...

        - 03

            60. [Dhondt et al. 2013; Trend Plant Sci](http://www.sciencedirect.com/science/article/pii/S1360138513000812); <FONT color="green">低・未刊</FONT>
                - Cell to whole-plant phenotyping: the best is yet to come
                - レベル (器官とか細胞とか) 別のphenotyping手法など
                - スケール貫通で統一的にやるには？

            61. [Zhen & van Iersel, 2017; J Plant Physiol](http://www.sciencedirect.com/science/article/pii/S0176161716302826); 20170303済
                - Far-red light is needed for efficient photochemistry and photosynthesis
                - 所属・引用文献を見る限り、ガチ光合成の人ではなく、親近感を覚える
                - FR添加に対して、PSIIの光化学反応は速やかに応答してEmerson様のY<sub>II</sub>上昇が生じるが、NPQ形成には時間遅れがある
                - FR-doseに関してはほとんどなし、これはPSIIリミットがすぐに解消されて律速の切り替わりが起こるから
                - Pn/PPFDを出すことで、FRの影響を除いたPAR領域の利用率に言及
                    - 藻類時代の片側enhancementのあたりで誰かやってたはず
                    - `Inada (1978)`も高等植物でやってた
                - 多項式回帰で*P* = .nnn を書くのはややアレではないか
                    - 単回帰でも切片か係数か不明だからアレではあるが、誤認は難しいので許容できる
                - `Murakami et al. (2016)`も引用していただきたかった...

            62. [van Iersel & Gianino, 2017; HortScience](http://hortsci.ashspublications.org/content/52/1/72.abstract); 無
                - An Adaptive Control Approach for Light-emitting Diode Lights Can Reduce the Energy Costs of Supplemental Lighting in Greenhouses
                - 閾値制御でPWM-LED補光を行うシステム
                - このラボはうちに似ているなぁ...

        - 05

            63. [Schmidt & Gaudin 2017; Trend Plant Sci](http://www.sciencedirect.com/science/article/pii/S1360138517300249); <FONT color="green">無</FONT>
                - Toward an Integrated Root Ideotype for Irrigated Systems
                - 灌水系での根域の理想形
                - 根、流行ってる
                - 次はblue revolutionと言われるだけあり、金も人もかかっている

        - 06

            64. [Lechenet et al. 2017; Nat Plant](http://www.nature.com/articles/nplants20178); <FONT color="green">無</FONT>
                - Reducing pesticide use while preserving crop productivity and profitability on arable farms
                - Natureハイライトから
                - あんまりご縁はなさそう

        - 07

            65. [Puthiyaveetil et al. 2017; Nat Plant](http://www.nature.com/articles/nplants201720); 無
                - Surface charge dynamics in photosynthetic membranes and the structural consequences
                - Kirchhoffグループ
                - PSII-supercomplex内でのvan der Waalsと静電相互作用を分解
                - abstすらついていけないレベル

            66. [Votoshkina et al. 2017; Physiol Plant](http://onlinelibrary.wiley.com/wol1/doi/10.1111/ppl.12560/abstract); 中・未刊
                - Involvement of the chloroplast plastoquinone pool in the Mehler reaction
                - はじめて見るかも、Borisova-Mubarakshinaグループ

            67. [Santabarbara et al. 2017; Phys Chem Chem Phys](http://pubs.rsc.org/en/content/articlelanding/2017/cp/c7cp00554g#!divAbstract); 低・未刊
                - Kinetics and Heterogeneity of Energy Transfer from Light Harvesting Complex II to Photosystem I in the Supercomplex Isolated from Arabidopsis

            68. [Semchonok et al. 2017; BBA](http://www.sciencedirect.com/science/article/pii/S0005272817300439); 低・未刊
                - Interaction between the photoprotective protein LHCSR3 and C<sub>2</sub>S<sub>2</sub> Photosystem II supercomplex in *Chlamydomonas reinhardtii*
                - LHCSR3はdimerとしてPSIへ結合する
                - LHCSR3のPSIへの結合部位は複数ある...?

            69. [Rosso et al. 2006](http://www.plantphysiol.org/content/142/2/574.short); 20170308済・引
                - IMMUTANS does not act as a stress-induced safety valve in the protection of the photosynthetic apparatus of Arabidopsis during steady-state photosynthesis
                - PTOX (IM) を6-fold or 16-foldにOXしたナズナで光阻害耐性を調査
                - 言い切り論文は引用しやすくて助かる
                - `Ort & Baker (2002)`をサポーティング
                - “強光✕低温で成育する高山植物にはPTOXが多く含まれ、PQを酸化よりに維持する作用により光阻害を防ぐ”という`Streb et al. (2005)`を否定する
                    - 低温成育植物では、光合成能力が向上する場合があるので、IMには関係ないのでは？という解釈
                - むしろ*im*でWTより酸化気味、OX系でWTより還元気味 1 - qP (or 1- qL) なデータ
                    - “... inactivating IM has induced the expression and biosynthesis of yet another plastoqui- nol oxidase in the chloroplast, which is more effective than IM.”
                    - もしくは、“... an up-regulation of the metabolic electron sink capacity at the acceptor side of PSI.”

        - 08

            70. [Joët et al. 2002; J Biol Chem](http://www.jbc.org/content/277/35/31623.long); 低
                - Involvement of a Plastid Terminal Oxidase in Plastoquinone Oxidation as Evidenced by Expression of the Arabidopsis thaliana Enzyme in Tobacco

            71. [Heyno et al. 2009; J Biol Chem](http://www.jbc.org/content/284/45/31174.full); 低
                - Plastid Alternative Oxidase (PTOX) promotes oxidative stress when overexpressed in Tobacco.

            72. [Nikolova et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/03/07/pp.17.00110.short?rss=1); 無・未刊
                - Temperature induced remodeling of the photosynthetic machinery tunes photosynthesis in a thermophyllic alga
                - 落とすのみ

            73. [Tomeo & Rosenthal 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/03/07/pp.16.01940.short?rss=1); 無・未刊
                - Mesophyll conductance among soybean cultivars sets a tradeoff between photosynthesis and water-use
                - 落とすのみ

            74. [Peltier et al. 2010; Photosynth Res](https://link.springer.com/article/10.1007/s11120-010-9575-3); <FONT color="green">低</FONT>
                - Auxiliary electron transport pathways in chloroplasts of microalgae

            75. [McDonald et al. 2011; BBA](http://www.sciencedirect.com/science/article/pii/S0005272810007425); <FONT color="green">低</FONT>
                - Flexibility in photosynthetic electron transport: The physiological role of plastoquinol terminal oxidase (PTOX)

        - 10

            76. [Knoblauch & Peters 2017; JIPB](http://onlinelibrary.wiley.com/wol1/doi/10.1111/jipb.12532/abstract); <FONT color="green">低</FONT>
                - What actually is the Münch hypothesis? A short history of assimilate transport by mass flow
                - 圧流説の歴史系レビュー

        - 11

            77. [Ogawa et al. 2017; Photosynth Res](https://link.springer.com/article/10.1007%2Fs11120-017-0367-x); 低
                - Estimation of photosynthesis in cyanobacteria by pulse-amplitude modulation chlorophyll fluorescence: problems and solutions
                - 園池グループ
                - 藻類はstate transitionやらFLVやら多くて手に負えないという印象

        - 13

            78. [Onoda et al. 2017; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.14496/abstract); <FONT color="blue">低・引</FONT>
                - Physiological and structural tradeoffs underlying the leaf economics spectrum
                - カッコイイ研究だ
                - そして錚々たる顔ぶれだ...

        - 14

            79. [Wang et al. 2015; Plant Growth Regul](https://link.springer.com/article/10.1007/s10725-015-0046-x); 20170314済
                - Green light augments far-red-light-induced shade response
                - Foltaグループ
                - 緑とFRが上記のpetiole/leaf比に対して加法的に作用する
                    - 避陰反応の判断基準として妥当か？
                    - 比に対して加法的ということはつまり？
                - cryでも緑が効いているので、青/緑の可逆ではない
                - 検定と相性の悪い実験計画だ

            80. [Li et al. 2017; Int J Hydrogen Energy](http://www.sciencedirect.com/science/article/pii/S0360319917302756); 高
                - Light conversion film promotes CO<sub>2</sub> assimilation by increasing cyclic electron flow around Photosystem I in *Arabidopsis thaliana*
                - 初見の雑誌 & グループ
                - これで光質が“significantly altered”は無茶だろう...
                    - conclusionではslightlyだけども
                - conclusionで触れているように、要因をCEFのみに限定できる実験系ではないので、タイトル詐欺気味だと思う
                - そもそもなぜこの内容で光合成系のジャーナルに出さないのか、とか個人的な第一印象が非常に悪い

        - 15

            81. [遠藤 2017; 領域融合レビュー](http://leading.lifesciencedb.jp/6-e001/); <FONT color="green">無</FONT>
                - 植物における概日リズムの組織特異性および組織間での時間情報の伝達
                - とりあえずダウンロード
                - 新着論文レビューの同著者の[シロイヌナズナは組織特異的な概日時計をもつ (2014)](http://first.lifesciencedb.jp/archives/9444)も参照

            82. [Tikhonov & Vershubskii 2017; Photosynth Res](http://link.springer.com/article/10.1007/s11120-017-0349-z);
                - Connectivity between electron transport complexes and modulation of photosystem II activity in chloroplasts
                - Tikhonovグループ
                - ちょっと超えてる

        - 16

            83. [Takagi et al. 2017; Physiol Plant](http://onlinelibrary.wiley.com/wol1/doi/10.1111/ppl.12562/abstract); 中・引
                - Diversity of strategies for escaping reactive oxygen species production within photosystem I among land plants: P700 oxidation system is prerequisite for alleviating photoinhibition in photosystem I
                - 三宅グループ、相変わらず勢いすごい...
                - PSI周りのalternative flowを属別に解析
                - Cytが能動的に役割を果たす、というのはどうも違和感がある考え方
                - 因果関係をさらうべき

        - 21

            84. [Karasov et al.2017; Plant Cell](http://www.plantcell.org/content/early/2017/03/20/tpc.16.00931.short?rss=1); <FONT color="green">低</FONT>
                - Mechanisms to mitigate the tradeoff between growth and defense

        - 22

            85. [Dierck et al. 2017; Sci Hort](http://www.sciencedirect.com/science/article/pii/S0304423817301012); 低
                - Light quality regulates plant architecture in different genotypes of *Chrysanthemum morifolium* Ramat
                - ベルギーILVOグループ
                - あまり心は惹かれないなぁ

            86. [Scheres & van der Putten 2017; Nature](http://www.nature.com/nature/journal/v543/n7645/full/nature22010.html); <FONT color="green">中</FONT>
                - The plant perceptron connects environment to development
                - ホルモンを介したbiotic/abioticな応答のレビュー
                - ニューラルネットを想起させる図

            87. [Zipfel & Oldroyd 2017; Nature](http://www.nature.com/nature/journal/v543/n7645/full/nature22009.html); <FONT color="green">低</FONT>
                - Plant signalling in symbiosis and immunity
                - 共生・免疫流行ってる感がある

            88. [Ilík et al. 2017; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.14536/full); 中
                - Alternative electron transport mediated by flavodiiron proteins is operational in organisms from cyanobacteria up to gymnosperms
                - 鹿内グループ
                - flvも気にしないといけなくなるのか...?

            89. [Chloroplast: Current Research and Future Trends](http://www.caister.com/chloroplasts)
                - Kirchhoffの編集
                - およそ37000 yen
                - Caister Academic Pressの本ははじめて
                    - １回だけアクセスできるページからpdfで配布する形式
                    - リンクが403エラーで死んだので、ヒヤヒヤしながらコンタクトしたら、即座に対応してくれて印象グッド

        - 24

            90. [Kume 2017; J Plant Res](https://link.springer.com/article/10.1007/s10265-017-0910-z); 低
                - Importance of the green color, absorption gradient, and spectral absorption of chloroplasts for the radiative energy balance of leaves

            91. [Silva-Pérez et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12953/abstract); 低・未刊
                - Biochemical model of C<sub>3</sub> photosynthesis applied to wheat at different temperatures
                - Evansグループ
                - C3光合成モデルの応答解析をフィールド、温室、チャンバレベルのwheatで

        - 26

            92. [Tcherkez et al. 2017; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.14527/full); <FONT color="green">20170326済・引</FONT>
                - Tracking the origins of the Kok effect, 70 years after its discovery
                - Kok効果のレビュー
                - 弱光下での光合成が専門だけど、Kok効果を実感したことがない。
                - 分解能も効いてるのかな
                    - “A recommendation to solve this problem is to have a sufficient number of measurements: typically, at least three in the 0--10 lmol m<sup>-2</sup> s<sup>-1</sup> region.”
                - ecosystemレベルでもKok効果様の挙動があるらしい (`Bruhn et al. 2011`)
                    - 線形の項が多数重なったらそうなるだろう

            93. [Yin et al. 2014; Photosynth Res](https://link.springer.com/article/10.1007%2Fs11120-014-0030-8); 20170417済
                - Accounting for the decrease of photosystem photochemical efficiency with increasing irradiance to estimate quantum yield of leaf photosynthesis
                - Y<sub>II</sub>を測定することで、ガス交換の最大量子収率を上方修正する手法について
                    - 利用側ではなく、理解側の観点がつよい
                - `Tcherkez et al. 2017`から
                    - “... both the light partition to PSII (a) and the photochemical yield of PSII (ΦPSII) have been found to increase at low light (Oberhuber et al., 1993; Yin et al., 2014)”
                    - PSIなら見たことあるが、PSIIでも起こるというのはは直感に反する
                    - Fig. 3aのことを言っているのか？引用怪しい
                - “Actually the maximum photochemical efficiency of PSII as revealed by chlorophyll fluorescence for the dark-adapted leaves is generally not higher than 0.83 (Björkman and Demmig 1987; Schreiber et al. 1995; Morales et al. 1991), and the photochemical efficiency of PSII under strictly limiting light is only about 0.84- 0.95 of the value for the dark-adapted leaves (Bernacchi et al. 2003; Yin et al. 2009)”

        - 27

            94. [Kudoh 2016; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.13733/abstract); <FONT color="green">低</FONT>
                - Molecular phenology in plants: in natura systems biology for the comprehensive understanding of seasonal responses under natural environments
                - 農業気象で聞いたので
                - ハクサンハタザオは
                    - adaptiveに自然繁殖している
                    - 目視により栄養生長期か生殖成長期かがわかる
                    - Arabidopsisと近縁なので遺伝的手法との相性がよい
                - 環境調節勢としては計測項目 (~説明変数) を増やしたくなるが、ロバストさは下がる

            95. [Aikawa et al. 2010; PNAS](http://www.pnas.org/content/107/25/11632.long); 低
                - Robust control of the seasonal expression of the *Arabidopsis FLC* gene in a fluctuating environment
                - `Kudoh 2016`と発表から
                - 尤度関数の局所解が、日数に対してはセンシティブ、温度閾値に対しては鈍い
                - ロバストな応答系のためにはこうあるべきだ、という話

            96. [Haxo & Blinks 1950; J Gen Physiol](http://jgp.rupress.org/content/33/4/389); 低
                - Photosynthetic action spectra of marine algae
                - 光合成作用スペクトルで寺島先生が引いていた

    - 4
        - 異動してからIPがなかなか支給されず、非常に滞っている
        - 他大に来てわかる東大クオリティ (UT-article linkは優秀だった)

        - 03

            97. [Aasamaa & Aphalo, 2015; EEB](http://www.sciencedirect.com/science/article/pii/S0098847215000131); 20170404済
                - Effect of vegetational shade and its components on stomatal responses to red, blue and green light in two deciduous tree species with different shade tolerance
                - 植生による遮蔽が気孔応答に及ぼす影響を２品種で比較
                - 遮蔽による光質変化のうち、UVが気孔応答のセンシティブさに効いているらしいというデータを、Full sunlight, neutral shade (70%), UV cut, vs vegetational shadeの比較で示す
                    - 植生によるUVのカットが、気孔の応答性を高めるらしい
                    - “stomatal conductance (in high light) is lowered in plants grown under supplementary UV (Nogués et al., 1998, 1999; Yao and Liu, 2006; Martínez-Lüscher et al., 2013) and increased in plants grown under UV absorbing filters (Albert et al., 2011; Berli et al., 2013; Kataria et al., 2013)”
                - 葉内CO<sub>2</sub>濃度に応答した気孔開度変化の話
                    - “The subsequent decrease in [CO2] of intercellular spaces (Roelfsema et al., 2002; Young et al., 2006; Araújo et al., 2011) and increase in balance between photosyn- thetic electron transport and carbon assimilation processes (Messinger et al., 2006; Busch, 2014) are signals for stomatal opening.”
                - Greenの気孔開度影響の話
                    - GreenでのBlue開度の打ち消し効果は、UV cutで育った葉には顕著に現れるが、vegetational shadeで育った葉には生じない
                    - “the ecological role of the green-light reversal effect can be the prevention of excessive leaf water loss through stomata under (green light-rich) vegetational shade, where the potential for photosynthesis is small (Talbott et al., 2006)”


        - 06

            98. [Takagi et al. 2017; Plant J](http://onlinelibrary.wiley.com/wol1/doi/10.1111/tpj.13566/abstract); 中・未刊
                - Chloroplastic ATP synthase builds up *proton motive force* for preventing reactive oxygen species production in photosystem I
                - 神戸大三宅グループ
                - 変異体作成からやってるしんどそうな研究
                - abstractを見た感じ、あんまり新しい要素がなさそうに思えるが...

            99. [Ibaraki & Matsuura 2005; J Agric Meteorol](https://www.jstage.jst.go.jp/article/agrmet/60/5/60_1073/_article/-char/ja/); 20170407済
                - Non-destructive evaluation of the photosynthetic capacity of PSII in micropropagated plants
                - *F*<sub>v</sub>/*F*<sub>m</sub>イメージング
                - *F*<sub>v</sub>/*F*<sub>m</sub>既知のreference葉を並べて測定することで、距離係数のkを算出

        - 07

            100. [Charbonnier et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12964/abstract); 20170716摘
                - Increased light-use efficiency sustains net primary productivity of shaded coffee plants in agroforestry system
                - 知らない人ばかり
                - 植生による遮光下での受光量の低下と光利用効率の向上を個体レベルから圃場レベルで解析
                - 2年間の経時データを使った大規模なやつ
                - “遮蔽された葉は、受光量の低下を光利用効率の向上で多少なりとも補うことで、空間的均一性を高める”というのはどーなのか
                - 受光量60%減 & LUE50%増だと、積は40%減だから、NPPステイブルはウソじゃない...？
                    - “We found that although irradiance was reduced by 60% below crowns of shade trees, coffee light-use efficiency increased by 50%, leaving net primary productivity fairly stable across all shade levels.”
                - introが“2050年には100億人を養わないといけない”、からはいった時点で読む気を失った

            101. [Trouwborst et al. 2016; EEB](http://www.sciencedirect.com/science/article/pii/S0098847215000854); 20170407済 (再)
                - Plasticity of photosynthesis after the ‘red light syndrome’ in cucumber
                - PFD vs Y<sub>II</sub>の部分を確認するついでに読み直し

        - 09

            102. [Harbinson & Yin 2017; Physiol Plant](http://onlinelibrary.wiley.com/wol1/doi/10.1111/ppl.12572/abstract); 20170716済
                - A model for the irradiance responses of photosynthesis
                - ある程度かぶっていそうな、嫌な予感がする
                - 20170716読み進め、被ってはいない。非常によろしい論文だ。
                    - あと１年早く出せてたら引用してもらえていただろうか？
                - 筆頭著者とは残念な発表をしたオーストラリアで面識がある
                    - 遺伝・統計・光合成生理を扱うWageningenのひと
                    - 多くの統計屋がそうであるように、beautifullyとかelegantとかnaturally emergesとか、ポエティックな言葉づかい
                    - M先生曰く、Foyerと組んだり、Aroと組んだり、と変な経歴らしい
                - PSIがリミットする状態が多いからP700だけでモデルを組む、というスタンス
                - 定常状態での酸化還元・電子フローをモデル化してる
                - 大枠はつかめたが、再読必須

            103. [Luján et al. 2017; Photosynth Res](https://link.springer.com/article/10.1007/s11120-017-0375-x); 低
                - A simple and efficient method to prepare pure dimers and monomers of the cytochrome *b*<sub>6</sub>*f* complex from spinach
                - 簡単ならやりたいが、single size-exclusion chromatography (？) という技術が必要

            104. [Fujiuchi et al. 2017; Biothechnol Bioeng](http://onlinelibrary.wiley.com/doi/10.1002/bit.26303/full); 無
                - Effects of plant density on recombinant hemagglutinin yields in an *Agrobacterium*-mediated transient gene expression system using *Nicotiana benthamiana* plants
                - 藤内さん

        - 12

            105. [Jokinen et al. 2017; Sci Rep](http://www.nature.com/articles/srep45707); 無
                - Solar eclipse demonstrating the importance of photochemistry in new particle formation
                - Helsinkiの物理グループ
                - 植物じゃなかった...
                - OA誌でちゃんとSupplementalを出すのは良いこと

        - 13

            106. [Walker et al. 2017; Photosynth Res](https://link.springer.com/article/10.1007/s11120-017-0369-8); 低
                - Uncertainty in measurements of the photorespiratory CO<sub>2</sub> compensation point and its impact on models of leaf photosynthesis
                - Ortグループ
                - どこかの項が0に漸近する系の誤差の出方なんだろうと思う

        - 14

            107. [Pearce et al. 2017; Plant Physiol ](http://www.plantphysiol.org/content/early/2017/04/13/pp.17.00361.short?rss=1); 低・未刊
                - Night-break experiments shed light on the Photoperiod 1-mediated flowering
                - タイトルがいかしている

            108. [Karpinska et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12960/abstract); 中・未刊
                - The redox state of the apoplast influences the acclimation of photosynthesis and leaf metabolism to changing irradiance
                - Foyerグループ

        - 16

            109. [Demmig-Adams et al. 2017; Curr Opin Plant Biol](http://www.sciencedirect.com/science/article/pii/S1369526616301704); <FONT color="green">20170416済</FONT>
                - Environmental regulation of intrinsic photosynthetic capacity: an integrated view
                - 最大光合成能力の環境応答を制御する要因について
                    - おもに気温・光に着目
                - conduitsってなんだと思ったら導管

            110. [Hüner et al. 2016; J Plant Physiol](http://www.sciencedirect.com/science/article/pii/S0176161716300360); <FONT color="green">中</FONT>
                - Photosynthetic acclimation, vernalization, crop productivity and ‘the grand design of photosynthesis’
                - `Demmig-Adams et al. 2017`から
                - J M Anderson のあれをイメージさせるなぁ

            111. [Yin et al. 2009; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1365-3040.2009.01934.x/full); 高
                - Using combined measurements of gas exchange and chlorophyll fluorescence to estimate parameters of a biochemical C<sub>3</sub> photosynthesis model: a critical appraisal and a new integrated approach applied to leaves in a wheat (*Triticum aestivum*) canopy
                - `Yin et al. 2014`から
                    - “To estimate Φ<sub>2LL</sub>, we used the equation that describes the decline of Φ<sub>2</sub> with increasing irradiance (Yin et al. 2009).”

            112. [Zhang et al. 2017; Front Plant Sci](http://journal.frontiersin.org/article/10.3389/fpls.2017.00328/full); 低
                - Can the responses of photosynthesis and stomatal conductance to water and nitrogen stress combinations be modeled using a single set of parameters?
                - 前にメールで`Murakami et al. 2016`への質問をくれた人
                - ヘヴィな実験っぽい

        - 18

            - Plant DirectというOA論文が、SEB、ASPB、Wileyのコラボで始まるらしい
                - ちょっと気になる

            113. [Singsaas et al. 2001; Oecologia](https://link.springer.com/article/10.1007/s004420000624); <FONT color="blue">20170418済</FONT>
                - Variation in measured values of photosynthetic quantum yield in ecophysiological studies
                - `Yin et al. 2014`から
                - “初期勾配が文献で結構小さいけど、変じゃない？ちゃんと測定できてないだけじゃない？”という渋い話
                    - PFD-*P*<sub>n</sub>カーブの非直線領域まで入れるな
                    - *C*<sub>i</sub>をちゃんと固定しろ
                - 光質一緒じゃないのに議論になるのか？
                - あたりまえ感を受けるが、生態学系の論文だとこれでもOKなのか？

            114. [Matthews et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/04/17/pp.17.00152.short?rss=1); 低・未刊
                - Diurnal variation in gas exchange: the balance between carbon fixation and water loss

            115. [Belgio et al. 2017; Photosynth Res](https://link.springer.com/article/10.1007/s11120-017-0385-8); 低
                - High light acclimation of *Chromera velia* points to photoprotective NPQ
                - [Chromera](http://photosyn.jp/pwiki/index.php?%E3%82%AF%E3%83%AD%E3%83%A1%E3%83%A9%E9%A1%9E)はchl *a*のみを持つ単細胞生物
                - 強光成育株は、PSIIコア-コア間の距離が遠くなり、エネルギー遷移が起こりにくい
                    - 強光成育株で、アンテナ/コア比が上がっているような絵
                    - 生態的には逆のような...？

            116. [Neto et al. 2017; Plant Biol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/plb.12573/abstract); 低・未刊
                - Cyclic electron flow, NPQ and photorespiration are crucial for the establishment of young plants of *Ricinus communis* and *Jatropha curcas* exposed to drought
                - 乾燥に対して耐性のJatropha vs 非耐性のRicinusの幼植物で、drought時のexcess energyの逃し方について比較
                - JatrophaではNPQ・CEF、Ricinusでは光呼吸が上昇、両方ともAPX・SODは増える
                - “the modulation of different photoprotective mechanisms is crucial to mitigate the effects caused by the excess energy”
                - matureだとどうなるのか？

        - 19

            - PRI (`Gamon et al. 1997`) の文献掘り (PRIサーベイ)

            117. [Gamon & Surfus 1999; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1046/j.1469-8137.1999.00424.x/abstract); 20170519済・引
                - Assessing leaf pigment content and activity with a reflectometer
                - ~~場所確保の色がつよい~~ ちゃんと読んだら研究要素が強かったので訂正
                    - “..., leaf reflectance has not been regarded as a particularly accurate method for assessing leaf pigment content... (because) pigments in the intact leaf are integrally bound with leaf structures.”
                - PRIの経時変化について言及 (Fig. 4)
                    - イントロでは、“Under typical room temperatures (25–30°C), a complete transition usually takes *c*. 5 min, but this can vary depending on the physiological state of the leaf.”
                    - 妙に照射後8 minにこだわっている
                    - この時点でも、ΔPRI (`Gamon & Berry 2012`や`Hmimina et al. 2014`で出てくる) で解析している
                - スペクトルの解析手法がいくつか挙げられている
                - “shade環境の葉でも、xanthophyllをfull-sunlightの半分くらいは持っているが、昼間でもcycleはほとんど回していない (Fig. 6b)。無駄な投資に思えるが、これはsun-fleckに備えた‘bet-hedging’だろう。陽性のヒマワリだから遺伝的に調節幅がなくて多くなっているのかも。”
                - 非常にエレガントな論文  

            118. [Peñuelas & Filella 1998; Trend in Plant Sci](http://www.sciencedirect.com/science/article/pii/S1360138598012138); <FONT color="green">20170420済</FONT>
                - Visible and near-infrared reflectance techniques for diagnosing plant physiological status
                - ざっくりレビュー

            119. [Sims & Gamon 2002; Remote Sens Environ](http://www.sciencedirect.com/science/article/pii/S003442570200010X); 中
                - Relationships between leaf pigment content and spectral reflectance across a wide range of species, leaf structures and developmental stages
                - Systemic regulationのSims (`Sims et al. 1997`)と同一人物？

            120. [Barton & North 2001; Remote Sens Environ](http://www.sciencedirect.com/science/article/pii/S0034425701002243); 中
                - Remote sensing of canopy light use efficiency using the photochemical reflectance index: Model and sensitivity analysis
                - 入射角度なんかの感度分析

            121. [Garbulsky et al. 2011; Remote Sens Environ](http://www.sciencedirect.com/science/article/pii/S0034425710002634)<FONT color="green">高・引</FONT>
                - The photochemical reflectance index (PRI) and the remote sensing of leaf, canopy and ecosystem radiation use efficiencies: A review and meta-analysis

            122. [Filella et al. 2009; Int J Remote Sens](http://www.tandfonline.com/doi/full/10.1080/01431160802575661?scroll=top&needAccess=true); 高
                - PRI assessment of long-term changes in carotenoids/chlorophyll ratio and short-term changes in de-epoxidation state of the xanthophyll cycle

            123. [Gamon et al. 2001; Photosynth Res](https://link.springer.com/article/10.1023%2FA%3A1010677605091?LI=true); 20170424済・引
                - Assessing photosynthetic downregulation in sunflower stands with an optically-based model
                - standに対してPRIで光合成機能の評価
                - 下葉だとEPSとPRIが完全にはリンクしない
                - 推定Pn自体は、値が小さいせいもあり、ずれていないように見えるが、これは推定がうまくいっているという訳ではない
                    - 最下部葉から新出葉への光合成産物系のシグナル自体は、無視してもいいと解釈できる
                    - シグナリングの重みづけがさほど重要ではないということ
                - 間違いなく引用することになるが、この論文は力技でねじ込んでる感あるなぁ
                    - “the results of this study are consistent with a large body of literature...”
                    - “remote sensing can be applied to predict whole-stand photosynthesis using the simple light-use efficiency model depicted in Equation (2).”

            124. [Peñuelas et al. 2011; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1469-8137.2011.03791.x/full); <FONT color="green">20170419済・引</FONT>
                - Photochemical reflectance index (PRI) and remote sensing of plant CO<sub>2</sub> uptake
                - 衛星ベースのPRIの限界について、`Grace et al. 2007`を簡単にまとめると、群落構造、バックグラウンドから来るドリフト、反射強度の入射角・計測角に対する依存性
                    - “In brief, these problems are related to the structural differences of the canopies, to varying ‘background effects’ (e.g. soil color, moisture, shadows, or presence of other nongreen landscape components) or to the different reflectance signals derived from illumination and viewing angles variations (Filella et al., 2004; Sims et al., 2006; Hilker et al., 2010).”
                    - 環境調節条件下であれば、いずれも軽減できるので、自分の研究ではあまり影響なし

            125. [Grace et al. 2007; Global Change Biol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1365-2486.2007.01352.x/full); <FONT color="green">中</FONT>
                - Can we measure terrestrial photosynthesis from space directly, using spectral reflectance and fluorescence?
                - Fig. 1のスケールおかしくね？

            126. [Gamon et al. 1990; Oecologia](https://link.springer.com/article/10.1007%2FBF00317336?LI=true); 20170420済
                - Remote sensing of xanthophyll cycle and chlorophyll fluorescence in sunflower leaves and canopies
                - 531, 685, 738 nm の光照射開始後の変化を調べ、その出所を解析
                - PRIのスタート

            127. [Porcar-Castell et al. 2012; Oecologia](https://link.springer.com/article/10.1007/s00442-012-2317-9); 中
                - Physiology of the seasonal relationship between the photochemical reflectance index and photosynthetic light use efficiency
                - PRIは短期的には、うまく光合成状態を反映するが、長期的には色素組成の変化に影響される
                - `Porcar-Castell et al. 2014; JXB`も深いし、この人はフォローすべき
                    - “the seasonal variation in leaf-level PRI seems to be controlled by the slow changes in pigment pools rather than NPQ (Stylinski et al., 2002; Filella et al., 2009; Porcar-Castell et al., 2012).”

            128. [Zhang et al. 2016; Remote Sens](http://www.mdpi.com/2072-4292/8/9/677/htm); <FONT color="green">~~中~~ 20170515済</FONT>
                - Affecting Factors and Recent Improvements of the Photochemical Reflectance Index (PRI) for Remotely Sensing Foliar, Canopy and Ecosystemic Radiation-Use Efficiencies
                - 水生植物、コケ類、地衣類でもいけるらしい
                    - “PRI has also been useful for studying aquatic vegetation [47], mosses [48–50] and lichens [51].”
                - 衛星からの文献
                    - “PRI obtained from MODIS (Moderate Resolution Imaging Spectroradiometer) [25,29,56–58], AVIRIS (Airborne Visible/Infrared Imaging Spectrometer) [59] and CHRIS/PROBA (Compact High Resolution Imaging Spectrometer launched aboard the Proba satellite) [60] can also track changes in photosynthetic performance and primary productivity at larger spatial scales.”
                - Table 1のleaf-scaleはざらっと見ておくべし
                    - Diurnalの話が多い
                    - 分レベルでのinductionについては、あまりない
                    - とくに面的イメージングでleafレベルはなさそう？
                    - ただし、`Rascher et al. 2007`を落としているように、確実視できるわけではない

        - 20

            129. [Renzaglia et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/04/18/pp.17.00156.short?rss=1); 無
                - Hornwort stomata: Architecture and fate shared with 400 million year old fossil plants without leaves
                - 原始的な植物であるツノゴケを使って、気孔の起源と機能を解析

            130. [Bernacchi et al. 2013; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12118/full); <FONT color="green">低</FONT>
                - Modelling C<sub>3</sub> photosynthesis from the chloroplast to the ecosystem

            131. [Nomura et al. 2012; Nat Commun](https://www.nature.com/articles/ncomms1926); 低
                - Chloroplast-mediated activation of plant immune signalling in *Arabidopsis*
                - ゼミで引用されていた、葉緑体免疫シグナルについて
                - いちおう[プレスリリース](http://www.kpu.ac.jp/contents_detail.php?frmId=2667)

            132. [Peñuelas et al. 1995; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1469-8137.1995.tb03064.x/abstract); 20170420済
                - Assessment of photosynthetic radiation-use efficiency with spectral reflectance
                - 光強度変化への応答は、PRIではY<sub>II</sub>より遅い
                - “some species exhibited additional complicating features that could have influenced *R*<sub>531</sub>, including significant chloroplast movement in *Phaseolus vulgaris* and a small xanthophyll content in the shade-adapted leaves of *Hedera canariensis* (unpublished).”

            133. [Gamon et al. 1992; Remote Sens Environ](http://www.sciencedirect.com/science/article/pii/003442579290059S); 20170420済
                - A narrow-waveband spectral index that tracks diurnal changes in photosynthetic efficiency
                - `Gamon et al. 1990`で、531 nm がxanthophyll cycleを反映することを示し、この論文では正規化のref波長を主成分分析で決定
                - この論文だと、refは550 nm だけど、後続は570 nm がメイン

        - 21

            134. [Albanese et al. 2017; BBA](http://www.sciencedirect.com/science/article/pii/S0005272816305710?dgcid=Newsletters%20%26%20Alerts_email_SDPR-EXP3-VAR1); 中
                - Dynamic reorganization of photosystem II supercomplexes in response to variations in light intensities
                - トリノ工科大学のBioSolar Labなる機関のグループ
                - PSII超複合体の構造 (リン酸化かな？) の短期的な光強度応答

            135. [Willocquet et al. 2017; Trend Plant Sci](http://www.sciencedirect.com/science/article/pii/S1360138517300237?dgcid=Newsletters%20%26%20Alerts_email_SDPR-EXP3-VAR1); <FONT color="green">無・未刊</FONT>
                - Multiscale phenotyping and decision strategies in breeding for resistance
                - とりあえず

            136. [Weng et al. 2010; Tree Physiol](https://academic.oup.com/treephys/article/30/4/469/1682565/Relationship-between-photochemical-efficiency-of); 高
                - Relationship between photochemical efficiency of photosystem II and the photochemical reflectance index of mango tree: merging data from different illuminations, seasons and leaf colors
                - PRIとY<sub>II</sub>の相関を、光条件、季節、葉色の異なる複数条件からマージ

        - 22

            137. [Earles et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/04/21/pp.17.00223.short?rss=1); 高・未刊・未取得
                - Excess diffuse light absorption in upper mesophyll limits CO<sub>2</sub> drawdown and depresses photosynthesis
                - 散乱光は、個葉レベルではCO<sub>2</sub>固定にネガティブ
                    - 1次元の有限要素法で鉛直方向の光環境をシミュレートしているらしい
                    - Rで組んだよ、とのことなのでコードを読みたい
                - 葉-個体-群落の光系スケーリングでは、多くの場合、スケーリングが成り立つがこれはそうでもないらしく、結構おどろき
                - Brodersenは、Vogelmannとよく組んでるあの人と同一っぽい
                    - ミドルネーム入れるか入れないか、統一してほしいなぁ

            138. [Armbruster et al. 2017; Curr Opin Plant Biol](http://www.sciencedirect.com/science/article/pii/S136952661730002X); <FONT color="green">20170422済</FONT>
                - The regulation of the chloroplast proton motive force plays a key role for photosynthesis in fluctuating light
                - pmfの概説に良かった
                    - pmfのうち、ψとΔpHはそれぞれPSII阻害・PSI阻害に対応するイメージ
                    - 後者の方が、修復しにくい点でネガティブ
                - γ-subunitの構造変化で、ATP合成へのpmf要求度が変わる
                    - “Flux of protons via the chloro- plast ATP synthase, and thus pmf, can additionally be regulated by structural changes in the g-subunit, which occur in response to oxidation/reduction of two redox sensitive cysteines and change the requirement for pmf to drive ATP synthesis [22,23].”
                - 最近の英語って、なんだかカンマが減っているような感じがする
                    - “When grown in the field *best1/vccn1* mutants have increased levels of PSII photoinhibition”
                    - “in the filed”のあとに入れたくなる

        - 24

            139. [Junge & Nelson 2015; Annu Rev Biochem](http://www.annualreviews.org/doi/full/10.1146/annurev-biochem-060614-034124#article-denial); <FONT color="green">低・引</FONT>
                - ATP synthase
                - えらいばっくりしたタイトルだけど、とりあえず

            140. [Hikosaka 2005; Ann Bot](https://academic.oup.com/aob/article/95/3/521/322923/Leaf-Canopy-as-a-Dynamic-System-Ecophysiology-and); <FONT color="green">低</FONT>
                - Leaf canopy as a dynamic system: ecophysiology and optimality in leaf turnover
                - `Hikosaka et al. 1994`の横に這わせる実験を参考にしていて

        - 25

            141. [Zhu et al. 2012; Curr Opin Plant Biol](http://www.sciencedirect.com/science/article/pii/S1369526612000222); <FONT color="green">20170425済</FONT>
                - Elements of a dynamic systems model of canopy photosynthesis
                - 群落レベルでの光合成モデルを“dynamic systems model”へ発展させるためには、何が必要か？がテーマ
                - maximal productivity model/resource-use efficiency model/big-leaf model/sunlit– shaded model/multi-layer modelをレビュー
                - 複雑化され、全体をとらえたdynamic systems modelモデルは、最適化に向けた具体的なアプローチの提案に便利
                    - “A dynamic systems model of photosynthesis ... would provide a robustframework to systematically re-evaluate the potential of different canopy features ... to improve Ac from a whole systems’ energy and resource use efficiency perspective.”
                    - ただ、パラメタライズに計測はやっぱり多く必要になる
                    - phenotyping系の技術をプッシュする

            - 生態学会誌の葉寿命特集号

            142. [及川 & 長田 2013; 日本生態学会誌](http://ci.nii.ac.jp/naid/110009604255); <FONT color="green">高</FONT>
                - 葉の枯死と個体の炭素収支

            143. [長田ら 2013; 日本生態学会誌](http://ci.nii.ac.jp/naid/110009604252); <FONT color="green">高</FONT>
                - 環境条件に応じた葉寿命の種内変異：一般的傾向と機能型間の差異

            144. [小野 & 永野; 日本生態学会誌](http://ci.nii.ac.jp/naid/110009604254); <FONT color="green">高</FONT>
                - 葉の老化に影響を与える環境要因と葉の老化の制御機構
                - 枯死は急激な変化に起因するものだ、という

        - 27

            145. [Gamon et al. 2015; Biogeosciences](http://www.biogeosciences.net/12/4149/2015/); 20170427概
                - Monitoring seasonal and diurnal changes in photosynthetic pigments with automated PRI and NDVI sensors
                - NDVIとPRIは相補的
                - 安いセンサーがイイね
                    - “... new small and inexpensive optical sensors are emerg- ing that can monitor dynamic vegetation indices such as PRI and NDVI (Garrity et al., 2010; Ryu et al., 2010; Eklundh et al., 2011; Harris et al., 2014).”
                - SRSというDecagonのPRIセンサーを使ったラージスケールの話で、読む必要はなさそう

            146. [Hoang et al. 2017; PCTOC](https://link.springer.com/article/10.1007/s11240-017-1219-2); 無
                - A comparative study on growth and morphology of wasabi plantlets under the influence of the micro-environment in shoot and root zones during photoautotrophic and photomixotrophic micropropagation
                - 府大北宅グループ

        - 28

            147. [Imada et al. 2016; Plant Pathol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/ppa.12443/abstract); 無
                - Magnesium oxide nanoparticles induce systemic resistance in tomato against bacterial wilt disease
                - 研究室内の課題
                - MgOは溶液としてではなく、不溶性の粒子自体が根に接触することが重要らしい

        - 30

            148. [Savvides et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12835/full); 中
                - Phenotypic plasticity to altered apical bud temperature in *Cucumis sativus*: more leaves-smaller leaves and vice versa
                - Wageningenグループ
                - このネタ結構つづいているなぁ

    - 5

        - 3

            149. [Ruban 2009; Commun Integr Biol](); <FONT color="green">低</FONT>
                - Plants in light
                - 初雑誌
                - 異分野向け概説

            150. [Demmig-Adams et al. 1996; Physiol Plant](http://onlinelibrary.wiley.com/wol1/doi/10.1034/j.1399-3054.1996.980206.x/abstract); 概
                - Using chlorophyll fluorescence to assess the fraction of absorbed light allocated to thermal dissipation of excess excitation
                - 陽葉vs陰葉でPSII周りのエネルギーの流れ、とくにNPQ、を解析した比較的古い文献
                - これまでに読んでなかったらしい

        - 5

            151. [Matsuda et al. 2017; J Biosci Bioeng](http://www.sciencedirect.com/science/article/pii/S1389172317300853); 無・未刊
                - Effect of temperature post viral vector inoculation on the amount of hemagglutinin transiently expressed in *Nicotiana benthamiana* leaves
                - 松田先生

        - 8

            152. [Kanazawa et al. 2017; Front Plant Sci](http://journal.frontiersin.org/article/10.3389/fpls.2017.00719/full); 低
                - Chloroplast ATP synthase modulation of the thylakoid proton motive force: implications for photosystem I and photosystem II photoprotection
                - Kramerグループ
                - この人は日本人なのだろうか、よくみかける
                - *pmf*流行っている感あるなぁ

            153. Gamon et al. 1993; Curr Top Plant Physiol  ; 20170508済
                - The dynamic 531-nanometer reflectance signal a survey of twenty angiosperm species
                - 公式ページ見つからず、ResearchGateから
                - leaf-level reflectrometerを作る話
                    - 分岐ファイバの片方から励起・測定光として使うハロゲン光を葉に照射、他方のファイバから分光
                    - 前日から暗順応した (\*コレは他の論文では違う場合もある) 葉にファイバを当てて光照射
                    - 照射開始から5秒以内にoriginを取る
                    - その後、10分推移を見る
                    - 531nm reflectanceのドリフトは、およそ0.02

            154. [Gamon et al. 2016; PNAS](http://www.pnas.org/content/113/46/13087.full); 20170508概
                - A remotely sensed pigment index reveals photosynthetic phenology in evergreen conifers
                - chlorophyll/carotenoid index (CCI) でフェノロジー
                    - Modis band 11/1 が531/645 nm なのでそれを使う
                - フェノロジーは、全球光合成モデルの季節項のようなものに必要らしい
                    - 風呂敷感があって非常にうまい

            155. [Rascher et al. 2007; Photogramm Eng Remote Sens](http://www.ingentaconnect.com/content/asprs/pers/2007/00000073/00000001/art00003); 20170508済
                - Monitoring the spatio-temporal dynamics with a portable hyperspectral imaging system
                - 初雑誌
                - `Grace et al. 2007`から
                - PRIの2Dイメージングをマルチスペクトルカメラで出している
                    - カメラ性能もあり、イケている画像ではない
                        - 主成分分析をかけてPCでスムージングをするというハイソな方法でスペクトルを平滑化している
                    - 時間分解能は分レベル
                    - Fig. 3では、光照射開始以降の推移が安定しているが、Fig. 5を見る限り、個体差は大きい
                - いくつか文献を読まないと
                    - “The PRI ... is negatively correlated with NPQ and has been successfully used to detect changes in photosynthetic efficiency at the leaf level (Peñuelas et al., 1995b and 1997; Gamon et al., 1997; **Guo and Trotter, 2004**), small canopy level (Gamon et al., 1992; Filella et al., 1996; **Stylinski et al., 2002**; **Trotter et al., 2002**), and recently at the ecosystem level (Peñuelas and Inoue, 2000; Rahman et al., 2001; Nichol et al., 2000 and 2002)”
                - いわく、「PRIは光合成反応に直接関係する唯一の反射指標」
                    - “Nevertheless, PRI still remains as the only valid reflectance index directly implicated in the photosynthetic reactions.”
                    - 強気だ
                    - Sunlight-induced chlorophyll fluorescenceとか...

        - 9

            156. [Gamon et al. 1997; Oecologia](https://link.springer.com/article/10.1007/s004420050337); 20170519済・引
                - The photochemical ref̄ectance index: an optical indicator of photosynthetic radiation use effciency across species, functional types, and nutrient levels
                - PRIのPPFD・CO<sub>2</sub>への時間応答
                    - 時間応答系だと、あとは、`Peñuelas et al. 1995`、`Méthy 2000` (個人的に不信)、`Rascher et al. 2007` (イメージングでやっている)、`Rahimzadeh-Bajgiran et al. 2012`
                - 531nmのシグナルは、526/545の２コンポーネントだけど、545の方は膜pH勾配由来のもので、強度依存性はほぼなし
                    - “The 545-nm component apparent in the reflectace dierence spectra (Fig. 7) is most likely related to chloroplast conformational changes associated with the buildup of the pH gradient, and not directly to the conversion of violaxanthin to antheraxanthin and zeaxanthin.”

            157.  [Fankhauser & Batschauer 2016; Cell](http://www.sciencedirect.com/science/article/pii/S0092867415017079); <FONT color="cyan">20170509済</FONT>
                - Shadow on the plant: a strategy to exit
                - Mendeleyのメールアラートから
                - SAS (shade avoidance syndrome) というフレーズが、最近プッシュされている
                    - syndromeって少なくとも日本語ではネガティブな意味を持つから気持ち悪いフレーズ
                    - 英語でもポジティブ要素はない (Cambridge dictionary: “US: a combination of medical problems that commonly go together and that show the existence of a disease”, ‘UK: a type of negative behaviour or mental state that is typical of a person in a particular situation:’)
                - 同誌の`Pedmale et al. 2016`では、弱青色光のもとではcry1/2とPIF4/5が協調し、同一のSASプロモータに影響していることを示しているらしい
                - 「R/FR比センシングに最適化されたPhy系に加え、他波長帯の受容体が存在する意義は何か？」について
                    1. 群落内のノイジィな光環境に応答するため (共変量だから説明できない、と思う)
                    2. 遮蔽が起こっていなくてもFRの高反射によりR/FRが低下しうるため、光量・光質のダブルチェックがベター (Rへの応答とR/FRへの応答を重複させる、という解決でもいいからあまりリーズナブルな説明ではない)
                    3. 応答速度の異なる反応 (青色光反応の方が遅いらしい) を併用することが、“a sustanable program to escape from shade”
                - PHY/PIF7系はおもにauxin生成量と分配量のupregulationに起因、CRY/PIF4/5系はおもに“cell wall modification”に起因するらしく、メカニズムが違う
                - CRYのblue/green可逆についてもちらっと
                    - CRYの色素団のFADのredoxで吸収帯が変わる

            158. [Pedmale et al. 2016; Cell](http://www.sciencedirect.com/science/article/pii/S0092867415016426); 無
                - Cryptochromes interact directly with PIFs to control plant growth in limiting blue light
                - `Fankhauser & Batschauer 2016`から
                - 一応、って感じ

            159. [Karasov et al. 2017; Plant Cell](http://www.plantcell.org/content/29/4/666.short?rss=1); <FONT color = "green">高・未刊・未取得</FONT>
                - Mechanisms to mitigate the trade-off between growth and defense
                - はじめて見るグループ (Max Planck Inst.とChicago Univ.)
                    - abstにreviewってあるが...
                    - “Exciting new evidence ... lending plants shape their microbiome to enhance” defense
                - まだアクセス権がないので、印刷待ち

            160. [Thomas et al. 2017; Funct Plant Biol](http://www.publish.csiro.au/FP/FP16127); 20170512済
                - Observation of plant–pathogen interaction by simultaneous hyperspectral imaging reflection and transmission measurements
                - Univ. BonnのMahleinグループ
                    - ResearchGate経由でRequest
                    - 即日でいただいた。ありがたい。
                - オオムギ葉のうどん粉病の検出
                - ハイパースペクトル画像に波長で主成分分析をかけるクラシカルな方法
                    - ローディングを見る限り、可視の葉色の変化成分 (PC1) と光合成色素のバンドに対応しているクロロフィルっぽい成分 (PC2) を分離している
                    - 反射 (表面側) 画像は早期検出
                    - 透過 (whole-leaf) 画像は、反射との差から、病害の進行の仕方を解析するのに向いている
                - FPBはいい論文が多いのに人気はないのが不思議
                    - CSIRO/ANUの人がやんごとなき理由で出してる？

            161. [Rascher & Pieruschka 2008; Precis Agric](https://link.springer.com/article/10.1007/s11119-008-9074-0); 20170509済
                - Spatio-temporal variations of photosynthesis: the potential of optical remote sensing to better understand and scale light use efficiency and stresses of plant ecosystems
                - CO2・O3のSoy-FACEに対してPRIで光合成への影響を解析
                    - いずれの区もリング外でPRIが上がっており、期待にあわず
                        - “We assume that these differences are related to the manual selection of the regions of interest.”
                    - CO2リングとO3リングでPRIの絶対値に隔たりがあるのは、1時間空いて太陽高度などが代わったせいだろう、と解釈
                - 残りはLIFT vs PAMや太陽光クロロフィル蛍光などに話題がシフト
                - あまり完成度が高い論文ではない

            162. [Méthy 2000; Photosynthica](https://link.springer.com/article/10.1023/A:1012449104831); 20170509済
                - Analysis of photosynthetic activity at the leaf and canopy levels from reflectance measurements: a case study
                - PRIと光利用効率は群落レベルだと相関がとれない、という`Rascher & Pieruschka 2008`の引用から
                - Fig.3Bが問題の図
                    - 渦相関で出したCO<sub>2</sub> FluxとPRIの時系列
                    - {CO<sub>2</sub> Flux / PPFD} vs PRIで書いていないから議論にならない
                    - Discussionで相関がとれない文献として引いている`Carter 1998` はPRI vs photosynthetic capacityなので不適、`Gamon et al. 1992`は老化した下位葉では相関がとれない、という話なのでイマイチ引用
                - Fig.1の尋常じゃなく速いPRI応答とFig.2の尋常じゃなくよいPSII-PRI回帰のこともあり、この論文を信じることができない

        - 10

            LIFTサーベイ
                - いずれもOsmond@ANUのグループ


            163. [Ananyev et al. 2005; Global Change Biol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1365-2486.2005.00988.x/full); 20170510済
                - Remote sensing of heterogeneity in photosynthetic efficiency, electron transport and dissipation of excess light in Populus deltoides stands under ambient and elevated CO<sub>2</sub> concentrations, and in a tropical forest canopy, using a new laser-induced fluorescence transient device

            164. [Kolber et al. 2005; Photosynth Res](https://link.springer.com/article/10.1007/s11120-005-5092-1); 20170510済
                - Measuring photosynthetic parameters at a distance: laser induced fluorescence transient (LIFT) method for remote measurements of photosynthesis in terrestrial vegetation
                - PSIIの光吸収断面積も出せるらしい (PCEの論文に引用できていない...)
                - 高PFD条件だとMINI-PAMと比べてノイジィなデータになっているが、たぶんS/N比の問題だろう、と解釈
                    - “... at high irradiance the LIFT-based ETR values are much noisier than the Mini-PAM data (Figure 2b)”.
                    - 強励起光下では、
                        - Q<sub>A</sub>の酸化還元レベルの変動幅が小さい
                        - 励起光による蛍光とそのノイズが卓越する
                - *F*<sub>v</sub>/*F*<sub>m</sub>が、9%程度ずれており、そのくらいの系統誤差はあるだろう、と考えている (どっちが高いのかは書いていない)
                - 光照射後のNPQ誘導は複相で、それぞれ半減期が60秒、15--30分
                    - “The wild type (Figure 4a) displayed two characteristic components in the NPQ response; a fast component, with a t<sub>1/2</sub> of about 60 s, and a slow one, with t<sub>1/2</sub> of about 15–30 min”
                - Light on直後のNPQのマイナス方向の変化 (i.e. *F*'<sub>m</sub>のプラス方向の変化) についてはうまく説明できない、という結果
                    - *F*<sub>m</sub>時にPAM方で使っているExcitation energyの方がよっぽど大きいので、そこの問題ではないとのこと

            165. [Osmond et al. 2004; Global Change Biol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1529-8817.2003.00747.x/full); <FONT color = "cyan">低</FONT>
                - Changing the way we think about global change research: scaling up in experimental ecosystem science
                - `Kolber et al. 2005`で“LIFTはもともと...”、というようなところで触れられていたので
                    - “The LIFT method was developed primarily for continuous monitoring of the photosynthetic properties in the relatively inaccessible outer canopy of trees over long time periods (Osmond et al. 2004; Ananyev et al. 2005).”

            166. [Pieruschka et al. 2012; Book chapter](https://link.springer.com/protocol/10.1007/978-1-61779-995-2_5); <FONT color = "cyan">20170510済</FONT>
                - Remote chlorophyll fluorescence measurements with the laser-induced fluorescence transient approach
                - ResearchGateから
                - とても簡単なLIFTのサマリー
                - Osmondグループのセットアップだと、およそ680 µmol m<sup>-2</sup> s<sup>-1</sup>で直径9cm程度
                - コリメートしたらポンプ&プローブで簡単にいけないかなぁ

            167. [Malenovslý et al. 2009; JXB](https://academic.oup.com/jxb/article/60/11/2987/533160/Scientific-and-technical-challenges-in-remote); <FONT color = "cyan">低</FONT>
                - Scientific and technical challenges in remote sensing of plant canopy reflectance and fluorescence
                - リモートセンシングでの反射・蛍光計測型の手法に関する全般的なレビュー

        - 11

            168. [Hmimina et al. 2014; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12171/full); ~~20170511済 (イントロ未)~~ 20170512済
                - Relationship between photochemical reflectance index and leaf ecophysiological and biochemical parameters under two different water statuses: towards a rapid and efficient correction method using real-time measurements
                - 明条件下でのPRIから暗条件下での値を引いて、補正PRIを算出すると、色素濃度などの影響をオフセットできる、というシンプルな方法
                - これもPRIのタイムコースを追っている
                - やや注意不足で不安な論文
                    - LUEの計算法がなく0.02程度のレンジ
                        - よくわからん
                        - 単純に*P*<sub>n</sub>/PFDでよさそう
                    - 反射率が0.4% (単純に1/100)
                    - コンダクタンスの単位は？
                    - wavelengthではなくlambda...
                    - なぜ赤青で色つけたのに散布図を形で認識させようとする...

            169. [Gamon & Berry 2012; Isr J Plant Sci](http://www.tandfonline.com/doi/abs/10.1560/IJPS.60.1-2.85); ~~20170511概~~ 20170512済
                - Facultative and constitutive pigment effects on the Photochemical Reflectance Index (PRI) in sun and shade conifer needles
                - `Hmimina et al. 2014`より、PRIの定数部分 (cPRI) と変動部分 (ΔPRI) について
                - cPRIが色素組成とリンクしている
                    - xanthophyll (V+A+Z) ではなく、lutein量と相関
                    - “constitutive carotenoid pigment pool sizes, not xanthophyll cycle pigments, are the primary source of PRI variability across species and canopy positions.”
                - sun-leafのdark-light transitionでのPRI変動を100%とすると、shade-leafでのdark-light時変動は60%
                - ΔPRIと*Y*<sub>II</sub>と来るかと思えばそうでもなし
                - Gitelsonさんの70歳祝いらしい
                - 変動成分のdark-light (full sunlight) transition は10分程度
                - lutein絡みのepoxidation cycleについても言及
                    - “..., the lutein deepoxidase cycle appears to be involved in energy dis- sipation (García-Plazaola et al., 2007)”
                    - “..., the lutein deepoxidation cycle has been observed in many species, including some trees (García-Plazaola et al., 2002; Matsubara et al., 2007), but to our knowledge its presence or function in conifers has not yet been conclusively demonstrated.”

        - 12

            170. [Soudani et al. 2014; Remote Sens Environ](http://www.sciencedirect.com/science/article/pii/S0034425714000303); 低
                - Relationships between photochemical reflectance index and light-use efficiency in deciduous and evergreen broadleaf forests

            171. [Hmimina et al. 2015; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12509/abstract); 20170512概
                - Deconvolution of pigment and physiologically related photochemical reflectance index variability at the canopy scale over an entire growing season
                - `Hmimina et al. 2015`のLUEはこれと同じなら*P*<sub>n</sub>/PPFD
                    - どうせモデルで出しているんだから、*R*<sub>d</sub>も補正した方がいいのに
                - $PRI(t) = PRI_\rm{o} + \Delta PRI ~ \times ~ error\_funct(\dfrac{PPFD(t)}{PPFD_\rm{sat}})$でPRIをモデル化
                    - 誤差関数の扱いが変じゃないか？
                    - kineticsにするなら、履歴系の関数にする必要があるような
                - Fig. 4は重複データなような？
                    - そもそもガス交換の測定の詳細がないから十分に理解できない
                - 引用には使いづらい

            172. [Nakaji et al. 2006; Int J Remote Sens](http://www.tandfonline.com/doi/abs/10.1080/01431160500329528); 高・未取得
                - Seasonal changes in the relationship between photochemical reflectance index and photosynthetic light use efficiency of Japanese larch needles
                      - ResearchGate経由でRequest
                - `Hmimina et al. 2014, 2015`から
                    - “Good relationships between the PRI and LUE over short periods have been shown for several species at the leaf (Gamon et al. 1992, 1997; Penuelas et al. 1995; Guo & Trotter 2004; Nakaji et al. 2006) and canopy scale (Filella et al. 1996; Trotter et al. 2002; Wu et al. 2010).”
                - 光合成研究の`中路 2009`の詳細？

            173. [Hall et al. 2008; Rmote Sens Environ](http://www.sciencedirect.com/science/article/pii/S0034425708001144); 低
                - Multi-angle remote sensing of forest light use efficiency by observing PRI variation with canopy shadow fraction
                - `Gamon & Berry 2012`の最後の方で触れられていた
                    - 最後の方でちらっと振れるのは多くの場合、「これいいじゃん。直接は本筋とは関係ないけど、普及させたい。」だと思うので
                    - “Recent studies that correct for sunlit fraction (Hall et al., 2008) are an exciting step in this direction, ...”
                - 樹冠レベルでのPRI測定は複数角度で測るべし、って話


            <!-- 173. [Takizawa et al. 2007; BBA](http://www.sciencedirect.com/science/article/pii/S0005272807001557) -->
            <!--     - The thylakoid proton motive force *in vivo*. Quantitative, non-invasive probes, energetics, and regulatory consequences of light-induced *pmf* -->
            <!--     - WSU Kramerグループ -->
            <!--     - `Hmimina et al. 2015`から -->
            <!--         - “The speed of xanthophyll de-epoxidation, which is associated with changes in the PRI, followed a Gaussian curve with changes in light intensity (Takizawa et al. 2007).” -->
            <!--     - まさかPRIから*pmf*まで飛ばされるとは、Hmiminaさん、手広い -->
            <!--         - が、もう少しいい文献がある気がする -->

            - 雑記
                - ラボにデスクチェアが届いた
                - 私物も事務に届くという羞恥プレイなのか...
                - K大K氏からお誘い

        - 14

            174. [Rahimzadeh-Bajgiran et al. 2012](https://link.springer.com/article/10.1007/s11120-012-9747-4); 20170514済
                - Relationships between the photochemical reflectance index (PRI) and chlorophyll fluorescence parameters and plant pigment indices at different leaf growth stages
                - 大政研の知らない人だ
                - PRIドリフトの補正でCPRIという指標を提案
                    - `Gamon & Berry 2012`や`Hmimina et al. 2014`の指標と比べてどうだろう
                    - CPRIとdark-adapted PRIの相関を取ればわかるが...

            - 雑記
                - PRIの像を掴んだので、一瞬で読めるになっている
                - あとはreview/meta-analysis系の数報を読んでインプットはお終い

        - 15

            175. [Wong & Gamon 2015a; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.13159/full); 20170515摘
                - Three causes of variation in the photochemical reflectance index (PRI) in evergreen conifers
                - 色素組成変化 > 極度の低温により生じるアルベドの変化 > xanthophyll cycle
                - アルベド変化は当面は気にしなくていい

            176. [Gamon & Bond 2013, Remote Sens Environ](http://www.sciencedirect.com/science/article/pii/S0034425713001193); 20170515摘
                - Effects of irradiance and photosynthetic downregulation on the photochemical reflectance index in Douglas-fir and ponderosa pine
                - 光合成速度・気孔コンダクタンスのmidday depressionがPRIでも確認されている

            177. [Wong & Gamon 2015b; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.13251/full); 低
                - The photochemical reflectance index provides an optical indicator of spring photosynthetic activation in evergreen conifers

            - 雑記
                - Remote Sensing を出しているMDPIはBeall's list に載ったようだが、`Zhang et al. 2016`を読むに、いいんでないか？
                - グループがいいだけ、って話もあるので要観察

        - 16

            178. [Kramer et al. 2016; HortTechnology](http://horttech.ashspublications.org/content/26/5/558.abstract); <FONT color="green">中</FONT>
                - Statistics in a horticultural journal: problems and solutions
                - サーベイとレビューまで、といったところ？
                - 要旨までみても“solutions”に対応する何かは“教育”にしか読めない
                - ある程度統計をやると、どのアプローチも統計的には完全ではないことがわかるせいで苦しむことになるんだよなあ

            179. [Konishi et al. 2008; ](https://link.springer.com/chapter/10.1007/978-1-4020-6709-9_141); 20170516済
                - Spatiotemporal changes in PRI and NPQ under different light intensity gradients on leaf surfaces
                - 大政研の小西さん
                    - 大政先生が共著のは全部個人ページにアーカイブされているが...大丈夫なのか...？
                - 光合成のinduction時のNPQとPRIのleaf-scaleでの空間分布を出している
                - NPQは葉脈でコンパートメント化しているが、PRIは均一、という論調だが、Fig. 1は逆のように見える
                    - “In Fig 1, NPQ on the leaf was heterogeneously observed (A),while PRI was homogeneously distributed (B)”
                - PRIの変化は小さい、みたいなフレーズがあるが、画像を見る限り相対値の勾配はNPQと同レベルでありそう？
                    - “In spite of the relatively large NPQ grdation, the pigment changes were not large enough to be detected by PRI”

            - 雑記
                - ボスと論文の流れのディスカッションを少し
                − 光合成学会のポスターで丸一日
                - 凝り性を発揮して、仕事が遅い

        - 17

            180. [Ibaraki & Shigemoto 2013; J Agric Meteorol](https://www.jstage.jst.go.jp/article/agrmet/69/2/69_69.2.1/_article/-char/en/); 20170617済 (再)
                - Estimation of supplemental lighting efficiency based on PPFD distribution on the canopy surface
                - 装置の確認

            181. [Ooms et al. 2016; Nat Commun](https://www.nature.com/articles/ncomms12699); <FONT color="green">無</FONT>
                - Photon management for augmented photosynthesis
                - 藻類培養での光利用について
                - いつまで続くか...

            - 雑記
                - ポスターを完成して共著者へ送信
                    - 結局、作業1.5日、構想で2日くらい？
                - 統計と似たもので、文献読みも多くやると、「これももうやられている」「あれのマイナーチェンジでしかない」という苦しみが生じる
                    - 引用が少ない研究者は、エンジニアタイプで解決すべき問題ありきだから、読む必要を感じていない
                    - あるいは、努力する気がない (学生は多くの場合これか)

        - 18

            182. [Walter et al. 2004; Plant Biol](http://onlinelibrary.wiley.com/wol1/doi/10.1055/s-2004-817828/abstract); 低
                - Transitions in photosynthetic parameters of midvein and interveinal regions of leaves and their importance during leaf growth and development

            183. [Hemming et al. 2008; Acta Hort](http://www.actahort.org/books/797/797_68.htm); 20170518概
                - Diffuse greenhouse covering materials – material technology, measurements and evaluation of pptical properties
                - 散乱フィルムを買おうと思ったので参考に
                - Made in Japanだし、Fクリーンがいいが...小売していないんだよなぁ
                    - 問い合わせた

            - 雑記
                - キャンパス内で牛が鳴いていてうるさい...
                - キャンパス内でホタルも見えるらしい
                - 遠いところに来たものだ、という感慨

        - 19

            184. [Dall'Osto et al. 2017; Nat Plant](https://www.nature.com/articles/nplants201733); 20170519概
                - Two mechanisms for dissipation of excess light in monomeric and trimeric light-harvesting complexes
                - Dall'Osto, Niyogi, Bassiというメンツ
                    - Nature Plantsは強ラボの草刈り場感があるなぁ...
                - 「PSIIのLHCII-trimerは維持したままLHCII-monomerをtriple know-outした株 (NoM) を作ったから解析するぜ」
                    - 光合成系はかなり重要そうなコンポーネントを壊しても成育するから不思議
                    - fail safe設計がしっかりしている
                    - NoM npq1 lut2とかいうクインティプルが...
                - NoMは２層性NPQ誘導のうち、速い方を示さない
                - 哀しいことに、Nature Plantsは購読されていないので、研究遂行経費購入

            185. [Guo & Trotter 2004; Funct Plant Biol](http://www.publish.csiro.au/fp/FP03185); 20170519済
                - Estimating photosynthetic light-use efficiency using the photochemical reflectance index: variations among species
                - ７種のPRIをY<sub>II</sub>・LUEと相関
                    - *P*<sub>n</sub>とLUEの図はどっちかでいい (Fig. 1)
                        - ただ固定のPPFDで割っているだけ、のはず
                        - なのに*C. robusta*だけLUEでバーが拡大しているのはなんなんだ
                    - 同図でPRI vs LUEを出しているので、PRI vs *P*<sub>n</sub>の相関は必要ない (Fig. 5)
                        - *Y*<sub>II</sub> vs *P*<sub>n</sub>は固定PPFDで抜き出しているのに (Fig. 4)
                        - “PRIだと種でばらつきますよ”、を強くみせるフェアじゃないやりかた
                    - 図の重複が多い論文だ
                - carotenoid量と光合成の下流の能力の関係についての考察はイカン
                    - *P*<sub>max</sub>の高い強光型でcar/chl比が低い→光防御の必要が小さいからだ、という解釈
                    - carotenoid総量は強光型の植物で多い傾向 (Table 2) にあり、熱放散のキャパシティも絶対値は大きい
                    - 強光型は (水不足とかで) いざ阻害を受けるとなれば被害が大きいから、防御能も高い
                    - 集光との関係性として議論すべきところ
                - データはいいとして、いろいろイマイチな論文
                - 哀しい私費その2
                    - Funct Plant Biolはいい雑誌なのに...

            - 雑記
                - 山口大の文献複写サービスを使って上ふたつを閲覧
                    - 最新号はリクエストできない
                    - 値段は届いてからわかる
                    - およそ１週間かかる
                        - 今回は11日リクエストで、19日着、682円也
                    - 科研費払いにするには、事前に事務に許可を貰う必要がある (事後建て替えはNG)
                        - 値段が事前にわからない時点でアレなかんじ
                        - 誰も幸せにならないシステムだなぁ
                        - 不正をして後世に面倒事を残した人を恨むのみ
                        - どうせ研究遂行経費払いにするんだけども...
                - PCEの論文の著作権譲渡確認書類にサイン、そろそろpreview版がアップされるころ

        - 21

            - 雑記
                - 装置２台の故障とドライバ問題の確認
                    - 自責で壊した・使えなくなったときに、どうにかせずに去るやつはどうしようもない
                    - ストレスフル
                    - 会社の対応の差が沁みる
                        - すごく頑張ってくれる会社
                        - 金はしっかり要求するが仕事はしっかりしている会社
                        - 社内で情報が伝わっていない会社

        - 22

            186. [Wang & Sonobe 2016; Geoscience and Remote Sensing Symposium (IGARSS)](http://ieeexplore.ieee.org/abstract/document/7729441/); 高・未取得
                - Tracing photosynthetic electron transport rate based on hyperspectral reflectance
                - 文献複写依頼
                - dmNDなる3波長利用指標がよろしいとのこと
                    - LUEではなく、ETRで書くあたり、かなり厳密？
                    - 過学習的なアレかも？
                - IEEEってやつがいまだによくわかっていない
                    - Proceeding扱いか、論文扱いか
                    - “sign in to view”ってfigの欄に書いてあるから、わざわざアカウント作ったら、“is outside your subscription”ときたもんだ

            187. [Sonobe & Wang 2015; Funct Plant Biol](); 低・未取得
                - Assessing the xanthophyll cycle in natural beech leaves with hyperspectral reflectance
                - RGリクエスト送付

        - 23

            - 雑記
                - 装置の動作確認
                    - 「あの装置にはこのソフトないと動かないんでした、すみません」からの「お送りしたソフトがそちらの研究室の装置とバージョンが違ったのかもしれません。装置のシリアル番号を確認してみて貰えますか？」じゃねーよ。ガキの使いかよ。といいたい。
                    - 「実はVAIOとちょっと相性悪くってー」ってPC新しく装置用に買うけどこれでいいか？って確認したじゃん。
                    - この会社は独立しても絶対に使わない決意をした。
                - 移動してからストレスが溜まっているなぁ。

        - 24

            188. [Miyaji et al. 2015; Nat Commun](http://www.sciencedirect.com/science/article/pii/S1360138596800197#); <FONT color = "green">無</FONT>
                - AtPHT4;4 is a chloroplast-localized ascorbate transporter in *Arabidopsis*
                - xanthophyll cycleのイラストを探していた (Fig. 6a)

        - 25

            189. [Bailey-Serres & Ma 2017; Nature](http://www.nature.com/nature/journal/v545/n7655/full/nature22497.html); <FONT color = "cyan">20170525済</FONT>
                - An immunity boost combats crop disease
                - Natureメールアラートの[ハイライト](http://www.natureasia.com/ja-jp/nature/highlights/86058)から誘導で
                - 生産性を損なわずに病害抵抗性を付与した、という連続した２本のレターについて
                    - translatome解析でimmunity-enhancing geneの調節機構の把握
                    - 遺伝子操作でコレを応用 (直下の`Xu et al. 2017`)
                - 基礎的な生物学の知識をそろそろ本格的につけねば
                    - っていっつも思うけど、やらないんだよなあ
                    - たぶん、バイオ実験をやりたくないからというのが大きい

            190. [Xu et al. 2017; Nature](http://www.nature.com/nature/journal/v545/n7655/full/nature22372.html); 低
                - uORF-mediated translation allows engineered plant disease resistance without fitness costs
                - 染色写真がサイケデリックでイケてる
                - 最近のNature系の図は、なんでexcel風イケてない配色になっているのか...

            - 雑記
                - 床に光合成学会用ポスターを敷いて眺めていたら思いがけない交流が生まれた

        - 26

            191. [Parent et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/05/25/pp.17.00372.abstract); 低
                - Quantifying wheat sensitivities to environmental constraints to dissect G x E in the field
                - いくつかのLociの応答を2genotypeの高温*乾燥ストレス断面で評価
                - この`G*E`形式の表現がとても好き
                    - 書き始めたのは誰だろう、Rユーザーっぽいけど
                    - `G:E`といいつつ、`G`固定で`Y ~ E:応答する遺伝子`の相互作用を解析する場合が多い気がする
                - この論文は、`G`が2水準だから、一応`G:E`で、`E ~ H*D`だから`Y ~ G*H*D*応答する遺伝子`になっている模様
        
        - 28
        
            - 光合成学会の発表でいくつか気になったもの
                - 矢守さんのunpublishが楽しみ
        
            192. [Yoshida et al. 2015; JBC](http://www.jbc.org/content/290/23/14278); 無
                - Thioredoxin selectivity for thiol-based redox regulation of target proteins in chloroplasts
                - trxファミリーの選択的redox制御を解析
                - ペプチド付与によりS-S鎖を切ることでSDS-PAGEのバンドをシフトさせ、redoxステートを解析する手法 (`Yoshida et al. 2014 PCP`) を使って
                
            193. [Heltle et al. 2013; Mol Cell](http://www.sciencedirect.com.egate.lib.yamaguchi-u.ac.jp/science/article/pii/S1097276512009896); 無
                - PGRL1 is the elusive ferredoxin-plastoquinone reductase in photosynthetic cyclic electron flow
                - trxの作用でPGRL1がdimerからmonomerになり、PRG5経路を制御するのでは？という話らしい
                - 吉田さんはネガティブな意見
                    - そもそもPGRL1がmonomer状態だったため
                    - PGRL1/PGR5のheterodimerがPFD依存的に制御されているようなデータ
                
            194. [Kämäräinen et al. 2017; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.14353/abstract); 中
                - Aroグループ
                - ポスター発表にて、
                    - NADPH <-> NADP変換に効く
                    - 弱光かつMixoでは欠損が成長遅延、強光や光独立栄養ではWTと差なし
                        - なんだこれ
                        
        - 29

            195. [Jiang et al. 2017; Sci Hort](http://www.sciencedirect.com/science/article/pii/S0304423817302613); 20170529概
                - Photosynthesis, plant growth, and fruit production of single-truss tomato improves with supplemental lighting provided from underneath or within the inner canopy
                - 千葉大丸尾グループ
                - 下から補光 vs interlighting を比較した渋い研究
            
            196. [Zhu et al. 2016; Funct Plant Biol](http://www.publish.csiro.au/FP/FP16222); 20170529済
                - The half-life of the cytochrome *bf* complex in leaves of pea plants after transfer from moderately-high growth light to low light
                - Chowグループ
                    - AusPhenoのときに見せてもらったデータ
                    - いいデータだよなぁ
                - 光強度の低下に対して、Cyt *f* は1.69 d で半減し*P*<sub>max</sub>を低下させる
                - 明期中のある程度時間の光照射だけでは減少は抑えられない
                    - どうにかdelayできれば？
                    - 何が鍵なのか？
                    
            197. [Hojka et al. 2014; Plant Physiol](http://www.plantphysiol.org/content/165/4/1632.abstract); 中
                - Inducible repression of nuclear-encoded subunits of the cytochrome b6f complex in tobacco reveals an extraordinarily long lifetime of the complex
                - `Zhu et al. 2016`でappreciateされている
                - RNA干渉で、Cytタンパクの発現を抑制すると、expanding leafのETRは低下するが、mature leafでは低下しない
                    - 合成は初期フェーズで重要
                - 光合成系のタンパク合成・分解のタイムコースはPSIIではよくわかっているが、その他のタンパクについては不明なことが多く、とくに高等植物ではほとんどわかっていない
                    - “In C. reinhardtii, ..., the decay of the cyt-*bf* was slower, with a halftime well above 21 h (Gong et al., 2001)”
        
        - 30
        
            198. [Anderson et al. 2012; Phil Trans R Soc B](http://rstb.royalsocietypublishing.org/content/367/1608/3515.short); <FONT color = "green">低</FONT>
                - Towards elucidation of dynamic structural changes of plant thylakoid architecture
                - Why grana?
        
        - 31
        
            199. [Lobet 2017; Trend Plant Sci](http://www.sciencedirect.com/science/article/pii/S1360138517300912); 20170531概・未刊
                - Image analysis in plant sciences: publish then perish
                - ソフトウェアの信頼性など
                - 開発するのは自分の次の研究のためだから、しゃーない
                - 成育モデル作ったけど公開しないし使わせません、とかいう某  グループもいるし
            
            200. [Apelt et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/05/30/pp.17.00503.short?rss=1); 低・未刊・未取得
                - Circadian, carbon, and light control of expansion growth and leaf movement
                - 時系列並べてt検定するやつ
                - たぶん読まない

    - 6
    
        - 01
        
            201. [Taboada et al. 2017; PNAS](http://www.pnas.org/content/114/14/3672.short); 無
                - Naturally occurring fluorescence in frogs
                - 蛍光を発するカエルのWTが見つかったとのこと
                - Natureのニュースから
                - 見つけたぜ、系かと思ったら、めちゃくちゃしっかり解析されている
                - オウムも蛍光を発するのか...
                
            - 雑記
                - 生環工へ参加・発表登録
                - PCEのproof
                    - 48 hrs締めは結構きつい
                    - onlineのproofシステムがストレスフルだった
                    - 変更部位をドラッグしてdeleteぽちってinsertぽちって、ってもう
                    - なぜか頑なにハイフンを消す担当者
                    - Springerもそうだったが、この方向性は簡便してくれんかな
        
        - 02
        
            202. [Allen 2017; Physiol Plant](http://onlinelibrary.wiley.com/wol1/doi/10.1111/ppl.12577/abstract); <FONT color="green">低</FONT>
                - Why we need to know the structure of phosphorylated chloroplast light-harvesting complex II
                
        - 06
        
            203. [Darko et al. 2014; Phil Trans R Soc B](http://rstb.royalsocietypublishing.org/content/369/1640/20130243); <FONT color="green">無</FONT>
                - Photosynthesis under artificial light: the shift in primary and secondary metabolism
                - 知らないグループとメンバー
                - レビューだが、十分に拾えている印象ではなく、目的もよくわからん
                    - “The capacity of LEDs to mimic the effects of natural light in terms of energy and information, thus ensuring the growth and development of photosynthetic organisms, and the potential for manipulating the plant metabolism to produce functionalized foods through changes in the intensity and wavelength are also reviewed here using selected examples.”
                - 読まないでいいと判断
                
        
        - 07
        
            204. [Chiang et al. 2017; Ann Appl Biol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/aab.12362/abstract); 低
                - A discussion on disease severity index values. Part I: warning on inherent errors and suggestions to maximise accuracy
                - 病害程度の指標化の問題点について
                - 面積ベースで指標化すると、系統誤差が出る
                - abstractを読んだ限り、解決法は書いていないっぽい
                - 自分と近い、「人の登るはしごを揺らす族」
                
            205. [Kochetova et al. 2018?; Photosynthetica](https://link.springer.com/article/10.1007/s11099-017-0736-x); 無
                - Long-term acclimation of barley photosynthetic apparatus to narrow-band red and blue light
                - モスクワ州大グループ (コレスポが指定されていないので分からないが、Averchevaグループ？)
                - この内容で松田論文、Trouwborst論文などを引いてなくてサーベイ甘そうなので読まず
                - F685/F735とか
                - Rだけだとmalfunctionalっぽい、って話には触れない
            
            206. [Stutz et al. 2017; JXB](https://academic.oup.com/jxb/article/doi/10.1093/jxb/erx155/3858257/Inside-out-efflux-of-carbon-dioxide-from-leaves#87685941); 低
                - Inside out: efflux of carbon dioxide from leaves represents more than leaf metabolism
                - タイトルが回りくどいのはあまりよろしくない
                - 呼吸速度が転流を反映するという話っぽい
                - 新しさ...?
        
        - 08
        
            - 雑記
                - データ解析と測定に追われる
                - 解析スクリプトが安定してきたので、そろそろ落ち着くはず
                - 重い某メールを送らないと...
        
        - 09
        
            - 雑記
                - デスクワーク不足
                - MacBookAirをぽちった
                    - 自宅でのコーディング用として
                    - さきぼそりのカタチが気に食わないけど、MBPまではいらないしなぁ、という判断
        
        - 10
        
            - 雑記
                - `EBImage::readImage`は画像の型を指定してもそんなに速くならない...?
        
        - 12
        
            207. [Huang et al. 2017; Photosynth Res](https://link.springer.com/article/10.1007%2Fs11120-017-0389-4); 20170612概
                - Superoxide generated in the chloroplast stroma causes photoinhibition of photosystem I in the shade-establishing tree species *Psychotria henryi*
                - Psychotria henryiは強光でPSI阻害が起こる珍しい植物
                - Ctrl vs +MV vs +tocophenol の比較で議論している
                - Psychotria henryiは日本語では出てこないアカネ科ボチョウジ属の植物でwikiによると現在も種数が増えているらしい
                - 新規な光合成システムが構築されうる種なのか？
        
        - 13
        
            - 雑記
                - 春先から探していた中古のPanasonicのインキュベータ (MIR-554) をようやく確保
                
        - 14
        
            208. [Atherton et al. 2017; Front Plant Sci](http://journal.frontiersin.org/article/10.3389/fpls.2017.00309/abstract); 低
                - Spatial variation of leaf optical properties in a boreal forest is influenced by species and light environment
                - Porcar-Castell グループ
                - 新しさはないように思う
                
            209. [Rahimzadeh-Bajgiran et al. 2017; Remote Sens](); 20170614概
                - Estimating chlorophyll fluorescence parameters using the joint Fraunhofer line depth and laser-induced saturation pulse (FLD-LISP) method in different plant species
                - 大政研
                - レーザーで飽和パルスを焚く
                    - 以前に現ボスとも話をしたが、葉を焼きそう
                    - エンジニアリング的には面白い
                    - Kolber式のLIFTの方が圧倒的にエレガント
                - いまいちわかってないが、レーザー飽和を使うと「広域で使える」という太陽光クロロフィル蛍光のメリットを殺さない？
                
        - 15
        
            210. [Ridley 1977; Plant Physiol](http://www.plantphysiol.org/content/59/4/724.short); 20170615摘
                - Interaction of chloroplasts with inhibitors. induction of chlorosis by diuron during prolonged illumination *in vitro*
                - DCMU入れたらNPQ上がるよね...って不安になってざっと漁った結果
                
            211. [Gilmore & Yamamoto 1992; PNAS](http://www.pnas.org/content/92/6/2273.short); 20170615済
                - Dark induction of zeaxanthin-dependent nonphotochemical fluorescence quenching mediated by ATP
                - レタスはNPQは大きく変動する割に、constitutive成分が小さい。これは、レタス近縁種にユニークなlutein置換できる色素のせいでは？とのこと
                    - “The reason for low constitutive NPQ in lettuce ... may be related to lactucaxanthin, a xanthophyll that is unique to *Lactuca sativa* L. and closely related species (35). Lactucaxanthin appears to partialy substitute for lutein in the light-harvesting Chl-a/b protein complex in lettuce.”
                    
            - 雑記
                - 去年の学会でアポをとったセンセイに客員研究員の受入依頼を送信した
                    - だいたいのことは「案ずるよりなんとやら」ではあるが、いつだって産むまでがつらい
                    - さっそくお返事があって、おっけーよ、とのことで恐らく来年４月から南半球
                    - 奇遇にもいま日本で休暇中とのこと
            
        - 16
            - 昨日につづき、NPQ周りを掘り
        
            212. [Müller et al. 2001; Plant Physiol](http://www.plantphysiol.org/content/125/4/1558.full); 20170616済 (再)
                - Non-photochemical quenching. A response to excess light energy
                - Niyogiグループ
                - qEがやっぱりしっくりこない
                    - lumen pH が低いときにはNPQが高いのは確かにそうだけど、pH勾配がNPQの直接の原因ではないように思う
                    - 例えばフラッシュでPQが完全還元されたときのYii低下は、アクティブに熱放散されたというよりは、受動的な起こる副作用、と解釈したほうが気持ちいい
                    - と、論文で書こう
                - xanthophyll cycle は分スケール
                    -  “This interconversion occurs on a timescale of minutes as part of a xanthophyll cycle...”
                    
            213. [Derks et al. 2015; BBA](http://www.sciencedirect.com/science/article/pii/S000527281500033X); <FONT color = "green">高</FONT>
                - Diverse mechanisms for photoprotection in photosynthesis. Dynamic regulation of photosystem II excitation in response to rapid environmental change
                - 初見っぽい (Bruceグループ, カナダBrock Univ.)
            
            214. [Merlier et al. 2017; Photochem Photobiol Sci](http://pubs.rsc.org/en/content/articlelanding/2017/pp/c6pp00416d#!divAbstract); 低
                - Potential use of the PRI and active fluorescence for the diagnosis of the physiological state of plants under ozone exposure and high atmospheric vapor pressure deficit
                - with Hmimina & Soudani
                - とりあえず落としたが、優先度はひくそう
                - abstractに“poorly understood”と書くと、かなり印象が悪いな
                - $\Delta$PRI (厳密には違う) が、NPQと相関など
            
            215. [Cazzaniga et al. 2013; Plant J](http://onlinelibrary.wiley.com/wol1/doi/10.1111/tpj.12314/full); 20170616概
                - Interaction between avoidance of photon absorption, excess energy dissipation and zeaxanthin synthesis against photooxidative stress in *Arabidopsis*
                - VeronaのBassi & 九大の和田グループ
                - xanthophyll cycleとphototropismの光阻害への寄与を比較する
                - *phot2*, *npq1* (Zea synthesis), vs *npq4* (PsbS)
                - 予想通り、additiveに作用する
        
        - 17
        
            - 雑記
                - MacBook Airが届いたのでセットアップ
                    - Chrome, R, Rstudio, TeX, Dropbox, Githubあたり
                    - 現環境は回線速度が遅いようでTeX (3.1GB) のダウンロードに数時間を要した
        
        - 20
        
            - 雑記
                - ３日とおしで測定
                    - ぐったりした
                    - コンディション悪いときにゼミでぐだると攻撃的になる
                    - 大人になりたい
                - チャンバ納品完了
                - 光源周りがまだ届かない
                - 全体的に納品遅いな
                
        - 21
        
            - 雑記
                - 解析日
                - surface pro2, Mac mini, Macbook airとも、file mtimeのミリ秒は保持しないくさい (f*ck)
            
        - 22
        
            216. [Huang et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/06/21/pp.16.01465/tab-article-info); 20170622摘・未刊・未取得
                - A light harvesting complex-like protein in maintenance of photosynthetic components in *Chlamydomonas*
                - Fang Huang (not Wei Huang) グループとRochaix
                - ChlamyのPSIのアセンブリに関係するファクタらしいMsf1 (Maintanance factor of PSI; sどこからきたの...)
                - アセンブリ因子はどこを潰しても色々効くからなんだかなぁ、って感じもある
                
            217. [Wang & Zhang 2017; Trend Plant Sci](http://www.cell.com/trends/plant-science/abstract/S1360-1385(17)30116-4); <FONT color = "green">20170622摘・未刊・未取得</FONT>
                - Boosting rice yield by fine-tuning *SPL* gene expression
                - Plant architecture (分蘖や分枝の構造のことの模様) に関係する遺伝子をうまいことやりましょう、という話
                - SQUAMOSA PROMOTER BINDING PROTEIN (SBP)-like でSPLらしい
                    - 再帰的だ
                
            - 雑記
                - データ解析が概ね終わり、ぼちぼち満足のいくデータ
                - 若干の修正と反復測定
                - DUAL-PAM/Fについての問い合わせ
                    - Y<sub>ND</sub>・Y<sub>NA</sub>は測定が難しく、絶対値で議論するものではないと思う
                    
        - 23
        
            218. [Park & Runkle 2017; Environ Exp Bot](http://www.sciencedirect.com/science/article/pii/S0098847216302738); 20170623概
                - Far-red radiation promotes growth of seedlings by increasing leaf expansion and whole-plant net assimilation
                - アメリカの施設園芸研究はサイエンスではなくエンジニアリング
                - 新しいことは含まれておらず、読んで楽しいものでない
                - 実用への要求が強いんだろうなぁ
                
            219. [Son et al. 2016; Hortic Environ Biotechnol](https://link.springer.com/article/10.1007/s13580-016-0068-y); 20170623摘
                - Application of supplementary white and pulsed light-emitting diodes to lettuce grown in a plant factory with artificial lighting
                - 図のみちらみ
                - M1N氏に投げたいが...読んでくれなさそう
                - アジア人、とくに中韓の苗字バリエーションの少なさがファイル整理と個人認識の重大な障害になりつつある...
                
            - 雑記
                - 学振PD＆科研費のダブル持ちを目指すべく、テーマをもにょもにょ考える
                    - 両方伸ばせる感じにしたい
                    - 物品見積り依頼をいくつか
                - 若者の論文よまなさがやばいなぁ
                - 学振PDになったが、いまだ自分で研究費を使えない。
                    - ちょっとしたものを買うのにも、先生に購入申請をお願いする→先生が大学の申請ページから注文申請をする、という２段階プロセスを踏む必要がある
                    - 旧ボス風にいうと、間違いなく日本のGDP下げている
                    - 学振PDは大学と雇用関係がないので、研究費使用に必要なアカウントを作成できない、という理由らしい
                    - 子アカウントから申請依頼くらいは投げられるようにすればいいのに
                    - 年間30万円くらいのうちの課題の間接経費は電気代に溶けているのか？
                    - 国立大全体で一括のシステムとか作れないものなのか？
                    - ブログ行き案件かと思ったけど、to whomだ
            
        - 28
        
            220. [Samodelov & Zurbriggen 2017; Trend Plant Sci](http://www.cell.com/trends/plant-science/abstract/S1360-1385(17)30106-1); <FONT, color = "green">低</FONT>
                - Quantitatively understanding plant signaling: novel theoretical–experimental approaches
                - みんなここに向かうんだよなあ
                
        - 29
        
            221. [Köhl et al. 2017; Funct Plant Biol](http://www.publish.csiro.au/fp/FP17051); 20170629摘
                - Performance of *Arabidopsis thaliana* under different light qualities: comparison of light-emitting diodes to fluorescent lamp
                - 複写依頼で585円也
                - Max Planckのグループ
                - 「蛍光灯じゃなくてLEDでいいでしょ」、を言うための研究
                - 研究所の刷新に合わせてやった感？
                - `G`だけの１元解析ならいいけど、結局`GxE`項がないことを示すべき、ということになるんじゃないかなぁ
                - `Schöttler & Tóth 2014`で光分配の話しているらしいので落とそう
                    - と思ったらレビューか
            
            222. [Schöttler & Tóth 2014; Front Plant Sci](http://journal.frontiersin.org/article/10.3389/fpls.2014.00188/abstract); <FONT, color = "green">中</FONT>
                - Photosynthetic complex stoichiometry dynamics in higher plants: environmental acclimation and photosynthetic flux control
                
    - 07
    
        - 02
        
            - 雑記
                - 生環要旨を仕上げ
                - 予定では土曜あがりだったのに、コンディションを崩す
                - 夏風邪？
            
        - 03
        
            223. [Pantazopoulou et al. 2017; PNAS](http://www.pnas.org/content/early/2017/06/21/1702275114.short); 高
                - Neighbor detection at the leaf tip adaptively regulates upward leaf movement through spatial auxin dynamics
                - UtrechtとWageningen (生態のAnten、functional structual modelingのEvers)
                - Auxin mutantを使って、スポットFRでsystemic signalingを作って、FSMでhyponastyの光獲得適応度解析、かな？
                
        - 04
        
            224. [Frank et al. 2017; Global Change Biol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/gcb.13802/abstract); 20170704摘
                - Risk of genetic maladaptation due to climate change in three major European tree species
                - タイトル面白そう
                - 分野違いのテクニカルタームが多く、やや掴みかねるが、seed source climate (種子形成期条件？) を入力として、multicariate genecological modelなるもので、その種子由来の苗のパラメータを出して、将来の気候条件でのリスクを出す
                    - 多変量の重回帰をAICあたりでモデル選択しているっぽい
                - この論文だと、maladaptationのニュアンスは、「順化が変な方向に向かっている」ではなく、「順化が生育条件におっついていない」という感じ？
            
            225. [Tian et al. 2017; JXB](https://academic.oup.com/jxb/article-lookup/doi/10.1093/jxb/erx213); 高
                - Effects of periodic photoinhibitory light exposure on physiology and productivity of Arabidopsis plants grown under low light
                - Rubanグループ
                - これはタイトルは面白くなさそうだけど内容は非常によろしい
                - 変動光への順化は来るだろうなぁ、と思ってたけどようやく来たか
                - 30 min 強光1800の阻害処理を１日３回でしばらく栽培
                    - HL-rossete, HL-seedlingは、systemicな話ではなく、処理開始ステージ
                - 2 week の阻害処理後には、無処理のctrlと同程度の光合成フェノーム
                    - 暗順化時のqPでredox解析
                    - CEFフラックスとか光分配とか、変わってないかなぁ
                    - 当然調べていそうだけど出していないということはそういうこと？
                - 阻害処理により葉面積は小さくなるが、DWは大きくなる
                    - 総受光量を考えればそりゃそうか？
                    - fatalな阻害 (頻度・持続時間を変える) だと？
                    - 程度の問題で、fatalにもpositiveにもなりそう
            
            - 雑記
                - 院生室にvisiting scholarが３人増えた
                - となりのこの人はFacebookするため日本まで来たのかなぁ...
            
        - 05
            
            226. [塩見 2008; 蛋白質 核酸 酵素](http://mol.medicalonline.jp/library/archive/search?jo=ac0tkksb&ye=2008&vo=53&issue=15&UserID=133.62.255.254); <FONT color = "green">20170705済</FONT>
                - ノンコーディングRNA研究の魅力とその現状
                - Hort Resの[non-coding RNA review](https://www.nature.com/articles/hortres201731) (読んでない) を見て、他でも聞いたことあるし読んどくかー的な
                - 生物の遺伝子にポリモーフィズムを実装するための仕組みっぽい
                - やっぱり分子生物学はハードルが高い
                    - 金の小槌を振りかぶることができないと勝負にすらならない
            
        - 06
        
            227. [Springer et al. 2017; Remote Sens](http://www.mdpi.com/2072-4292/9/7/691); 中
                - Parallel seasonal patterns of photosynthesis, fluorescence, and reflectance indices in boreal trees
                - Gamonグループ
                - 分光指標をトラッキングする話
                    - はたからみていると銅鉄実験っぽさがある
                
        - 08
        
            228. [Lanoue et al. 2017; Front Plant Sci](https://doi.org/10.3389/fpls.2017.01076); 20170708概
                - The effect of spectral quality on daily patterns of gas exchange, biomass gain, and water-use-efficiency in tomatoes and lisianthus: an assessment of whole plant measurements
                - 図とDiscussionを斜め読み
                - R, G, B, R+W, RB, HPS, FLなど比較
                - 論文と関係ないけど、FrontiersはいきなりPDFダウンロードではなくブラウザで見られるようにしてほしい
                
            229. [Cope & Bugbee 2013; HortScience](http://hortsci.ashspublications.org/content/48/4/504.short); 20170708概
                - Spectral effects of three types of white light-emitting diodes on plant growth and development: absolute versus relative amounts of blue light
                - 白色LEDを比べる話
                - AusPhenoでもちらっと触れていたような (きおくあいまい)
            
            230. [Golding & Johnson 2003; Planta](https://link.springer.com/article/10.1007%2Fs00425-003-1077-5?LI=true); 20170708済
                - Down-regulation of linear and activation of cyclic electron transport during drought
                - 乾燥ストレス vs CEF-PSIのスターター
                - 図4が図3と一緒というなかなかの誤植: [Erratum](https://link.springer.com/article/10.1007/s00425-003-1188-z)
                - このひとが“photosynthetic control”というフレーズを使い始めたっぽい？
                
            231. [Sonoike 1999; J Photochem Photobiol B](http://www.sciencedirect.com/science/article/pii/S1011134499000305); 20170708概
                - The different roles of chilling temperatures in the photoinhibition of photosystem I and photosystem II
                - いまさら落とした
                - 予備実験とかして絞ったんだろうな、という風なエレガントなデータだ
                
            - 雑記
                - 学祭だったが、関与なし
                - ホームページくそださいな
                - 学祭で花火は新鮮
            
        - 10
        
            232. [Tschiersch et al. 2017; Plant Method](https://plantmethods.biomedcentral.com/articles/10.1186/s13007-017-0204-4); 無
                - Establishment of integrated protocols for automated high throughput kinetic chlorophyll fluorescence analyses
                - Fluorcamとベルトコンベアを作りました、って話
                - ソフト的なところはなんもなし？
            
            233. [Amrhein et al. 2017; PeerJ](https://peerj.com/articles/3544/); 低
                - The earth is flat (*p* > 0.05): significance thresholds and the crisis of unreplicable research
                - 有名な“The earth is round (*p* < .05)”をもじったタイトル
                - 効果量あるいは再現性の話はOA誌とも相性いい
                    - OAで出すならPeerJ・eLifeがいいなぁ
                - ASAのアレ以来、*p*値トークが増えている印象でよろしい
            
            - 雑記
                - 学会参加費の早割をのがしていた...
                - 暫定プログラムでオーラス
                - 共著者に「今週中にお送りします」メールをして自分を追い込むスタイル
            
        - 11
        
            234. [Schymansky et al.2017; Hydrol Earth Syst Sci](http://www.hydrol-earth-syst-sci.net/21/3377/2017/); 無
                - Technical note: An experimental set-up to measure latent and sensible heat fluxes from (artificial) plant leaves
                - 葉の熱収支とガス交換を同時に測定するシステムを作った話
                
            235. [Lee et al. 2017; Trend Plant Sci](http://www.cell.com/trends/plant-science/abstract/S1360-1385(17)30132-2); <FONT, color = "green">低</FONT>
                - Multiple routes of light signaling during root photomorphogenesis
                - 根での光センシングについてのレビュー
            
        - 12
        
            236. [Théroux-Rancourt et al. 2017; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.14687/abstract); 低
                - The bias of a two-dimensional view: comparing two-dimensional and three-dimensional mesophyll surface area estimates using noninvasive imaging
                - 筆頭はUC Davis、Brodersonがシニアに入っている
                - 図 (データじゃなくて) が全てエレガントだ
                - MicroCT (高そう) を使って、3D構造を解析する話
                - 知見自体の新しさはあまりないっぽいような
            
        - 13
        
            - 雑記
                - 博論の未投稿部分を投稿論文化したので、共著者 (元ボスたち) に送信
                - これで一応、キレイな体になれる
                - 2017abcはかたい、dは投稿までは行きそうだけど年をまたぎそう
            
        - 14
        
            237. [Brodribb et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/07/06/pp.17.00552?rss=1); 無・未刊・未取得
                - Optical measurement of stem xylem vulnerability
                - 茎部でのキャビテーションを光学計測する手法について
                - 詳細は読んでないけど、とりあえず
            
            238. [Noridomi et al. 2017; Photosynth Res](https://link.springer.com/article/10.1007/s11120-017-0419-2); 低
                - Opposite domination of cyclic and pseudocyclic electron flows in short-illuminated dark-adapted leaves of angiosperms and gymnosperms
                - 裸子・被子でCEFの組成が違うね、って話っぽい
                - 暗処理した葉への1 s SP後のPSII蛍光の下がりの多項回帰でflv, ndhCEF, pgrCEFを議論  
                
            239. [Tomar & Jajoo 2017; Funct Plant Biol](http://www.publish.csiro.au/fp/FP17121); 低・未取得
                - PSI becomes more tolerant to fluoranthene through the initiation of cyclic electron flow
                - fluorantheneは多環芳香族炭化水素の一種で有機系の阻害剤らしい
                - 環境汚染系？
                    - 大気汚染物質の模様 [大気汚染による植物の環境ストレスを活性酸素消去剤を用いて緩和する方法の検討](https://kaken.nii.ac.jp/ja/grant/KAKENHI-PROJECT-21310023/)(KAKENサイト) など
                    
            240. [Crisp et al. 2017; Plant Cell](http://www.plantcell.org/content/early/2017/07/13/tpc.16.00828?rss=1); 中・未刊・未取得
                - Rapid recovery gene downregulation during excess-light stress and recovery in Arabidopsis
                - Early viewを見た感じ、良さそう
                - omicsは図が強い
                
            241. [Vizsnyiczai et al. 2017; Nat Commun](https://www.nature.com/articles/ncomms15974); 無
                - Light controlled 3D micromotors powered by bacteria
                - 作るの楽しそう
                
            242. [Jackson et al. 2017; eLife](https://doi.org/10.7554/eLife.26023); 無
                - Topological analysis of multicellular complexity in the plant hypocotyl
                - eLifeかっこいいなぁ
            
        - 15
        
            243. [Saudreau et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.13026/abstract); 未刊・未取得・20170715摘
                - Temperature heterogeneity over leaf surfaces: the contribution of the lamina microtopography
                - 葉面での熱的不均一性を、3Dモデルを組んで熱収支計算から解析する話
                - 図を見た感じ、空間分布はあっていないが、平均は合うとのabst
                
            - 雑記
                - なぜPlant Physiolの図はいもいのか...
            
        - 16
        
            - 雑記
                - 優先度: 高をいくつか潰し (Charboninnier et al. 2017; PCE, Harbinson & Yin 2017 Physiol Plant)
                
        - 17
        
            244. [Zivcak et al. 2013; Photosynth Res](https://link.springer.com/article/10.1007/s11120-013-9885-3); 低
                - Photosynthetic electron transport and specific photoprotective responses in wheat leaves under drought stress
                - Allakhverdievグループ
                - `Gas/flu/P700 params ~ PPFD * time * drought`の解析
                - 光分配 a<sub>II</sub>も出てきている
                    - Laisk plotのフィッティング
            
            - 雑記
                - F先生より、論文コメント
                    - 先生、添付忘れてます...
                - C先生より、visiting fellowの手続きについて連絡
                    - CVの書き方がよくわからん...
                
        - 18
        
            245. [Bucksch et al. 2017; FPS](http://journal.frontiersin.org/article/10.3389/fpls.2017.00900/full); <FONT color = "green">低</FONT>
                - Morphological plant modeling: unleashing geometric and topological potential within the plant sciences
                - マウント取りの論文、って感じ
                - 研究論文にメンバーの写真入れるのはちょっと...
                    - なんでこれを通したんだMarcelis
                - Frontiersの印象が下がる一方だ
            
            246. [Stinziano et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12911/abstract); 中
                - The rapid *A*–*C*<sub>i</sub> response: photosynthesis in the phenomic era
                - 動的にCO<sub>2</sub>濃度を変化させることで、高速にA-Ciカーブを得る？
                - 直感的には、気孔開度でバイアスが掛かりそうだが...？
                - 読むべきではある論文？
            
            247. [Hirt et al. 2017; Nat Ecol Evol](https://www.nature.com/articles/s41559-017-0241-4); 無
                - A general scaling law reveals why the largest animals are not the fastest
                - 吸熱・発熱の熱的制御が速度に及ぼす影響が、水棲生物と陸棲・飛行生物で逆転するのもエレガントだし、恐竜のスピードもキャッチーだ
                - 美しいなぁ
                
                
            - 雑記
                - 山口は霧がものすごいなぁ
                - C先生にCVを送信
            
        - 19
        
            248. [Tietz et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12924/abstract); 
                - NPQ<sub>(T)</sub>: a chlorophyll fluorescence parameter for rapid estimation and imaging of non-photochemical quenching of excitons in photosystem-II-associated antenna complexes
                - Kramerグループ
                - F<sub>m</sub>測定の時間コストの問題を回避するために新しい熱放散パラメータを、という論文
            
            - 雑記
                - 夏バテ気味だ
                - 口腔・歯科衛生系のpredatory journalからメールが多いのだが、なぜだ？
                - 相関解析に良さそうなパッケージ -> https://github.com/drsimonj/corrr
                
        - 20
        
            249. [Trchounian et al. 2017; Book chapter ](https://link.springer.com/chapter/10.1007/978-3-319-44081-1_2); 低
                - Plant cell redox homeostasis and reactive oxygen species
                - 本の編者も著者たちも知らない人率高すぎるが、大丈夫か？自分が詳しくないだけか？
                - 無料だったので一応おとす貧乏性
        
            - 雑記
                - M先生より、論文コメント
                    - D論のときにも指摘されたが、ここはなぁ...
                - そこは置いとけるとこだったので、ほかを反映して英文校正に投げた
                    - 研究遂行経費 (非課税私費) でやるか
                
        - 22
        
            250. [Avercheva et al. 2014; Adv Space Res](http://www.sciencedirect.com/science/article/pii/S0273117714001501?via%3Dihub); 低
                - Biochemical, photosynthetic and productive parameters of Chinese cabbage grown under blue–red LED assembly designed for space agriculture
                - 初ジャーナル
                - ロシアはソ連時代からの宇宙志向が植物でも？
                
        - 24
        
            - 雑記
                - PCEのproof読み
                    - いまさらながら、PCEはprefixのマイクロが斜体なのか 
                    - ださいなぁ
                    
        - 25
        
            - 雑記
                - PCE proofを返送
                    - wileyのhtml上での修正システムがやっぱりうまくいっていないくさい
                - 研究の話ができるのがボスだけなのは非常にストレスだ
                    - 考えることを放棄しているのを見るともだもだする
                    - 砂漠に水撒く感じ
            
        - 27
        
            - 雑記
                - 論文を投稿した
            
        - 28
        
            - 雑記
                - 公開の博論審査にお邪魔した
                    - 略歴紹介とか花束贈呈とかあって、ほほうってなる
                    
        - 29
        
            251. [Song et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.13041/abstract); 未刊・未取得
                - The impact of modifying photosystem antenna size on canopy photosynthetic efficiency
                - Don OrtとXinguang Zhu (Systems biologyの人らしい)
            
        - 31
        
            - 雑記
                - ゼミで博士論文スライドを出した (いまさら)
                
    - 08
    
        - 03
        
            - 雑記
                - ここ数日、測定が続きで少しくたびれた
                
        - 04
        
            - 雑記
                - はじめて屋外で研究用の測定したかも
                    - 日陰でやってたのに、ひたすら暑い
                    - フィールド屋さんはすごい
                - physiol plant に投げた論文がeditor assignにまだ届かぬ (5日目)
                
        - 06
        
            252. [Evans et al. 2017; PCP](https://academic.oup.com/pcp/article-abstract/doi/10.1093/pcp/pcx103/4056559/Light-Quality-Affects-Chloroplast-Electron); 必・未刊・未取得
                - Light quality affects chloroplast electron transport rates estimated from chl fluorescence measurements
                - Evans、とvon CaemmererとLI-CORの人
                - 内容は予想できるが、必要に応じて今の原稿で引きたい
                - どの項まで定量してからやっている？
                    - 青色光だとETRを２倍近く過大評価
                    - 深度の問題で解析している？
                    - ETRを比べているので、ネストせずにやるのは難しいはずだから、光分配は解析していないはず
                        - やってないのにabstで非光合成色素に言及せずに深度のみに行くとは考えにくいので、解析しているのか？
                - PCP (Oxford系?) がしばらく読めないのは痛いなぁ
        
            - 雑記
                - 帰りにちょうちん祭りを流す
        
        - 07
        
            - 雑記
                - 科研費申請を考える
                    - KAKENでタイトル眺め
                - 学振から書類が届いたので、スキャンしてC先生にメール
                    - 英文メールしんどい
                    
        - 08
        
            253. [三中 2016; 心理学評論](http://team1mile.com/sjpr59-1/contents_comment/minaka2016/); <FONT color="green">20170808済</FONT>
                - 統計学の現場は一枚岩ではない
                - QRPsっていわれてもプレミアリーグのアレ (QPR) がうかぶ
                    - questionable research practicesらしい
                - 三中先生に限らず、統計屋はたのしそうに論文を書いていて非常によろしい
                - 仮説ありきのStrong inferenceとガチンコバトルになるよなぁ
                - wet研究やるとどうしてもstar countingに走る
            
            254. [久保 2003; 生物科学](http://www.ruralnet.or.jp/seibutsu/054_03.htm); <FONT color="green">20170808済</FONT>
                - 樹木・森林生態学「よく出る」誤用統計学の基本わざ
                - 253から
                
            255. [Johnson 1999; J Wildl Manage](http://www.jstor.org/stable/3802789?seq=1#fndtn-page_scan_tab_contents); <FONT color="green">中</FONT>
                - The insignificance of statistical significance testing
                - wildlifeはwildlで略すのか
                - 同、253から
            
            256. [Sato et al. 2017; PCP](https://academic.oup.com/pcp/article-abstract/doi/10.1093/pcp/pcx110/4061461/FLUCTUATINGlIGHTACCLIMATION-PROTEIN1-conserved-in); 中・未刊・未取得
                - FLUCTUATING-lIGHT-ACCLIMATION PROTEIN1, conserved in oxygenic phototrophs, regulates H+ homeostasis and non-photochemical quenching in chloroplasts
                - 河野さんも共著で入っている東工大増田研
                - abstだけ読むと、変動光応答のキーというよりは、強光→弱光時のNPQ低下に支配的なだけでは？
                    - って思ったけど、そもそもほとんど全ての応答に時間遅れがあるわけで、変動光応答のキーというものは存在しない、あるいは全ての要素がキーである、といってもいい
                - 待ち
            
            - 雑記
                - 科研申請、「方向はこれでいくかー」っていうのはざっくりうまる
                    - 一応、予備データになるものを東大時代にとってある
                    - ただ、関連する論文が出せてないので、そこが弱い
                    - もう少し練る
                    - 最悪いまはとれなくても数年内にはとれそう
                - 科研申請の学内締切は10月半ばらしい
                    - 情報が届きづらいので警戒必要そう
            
        - 09
        
            257. [Bezryadina et al. 2017; Phys Rev Letter](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.119.058101); 無
                - Nonlinear Self-Action of Light through Biological Suspensions
                - バクテリアの凝集程度をコントロールして前方散乱させるライトガイド、散乱膜にする
                - かっとんでるな
                
            258. [Suorsa et al. 2016; Mol Plant](http://www.sciencedirect.com/science/article/pii/S1674205215004542); 20170809摘
                - PGR5-PGRL1-Dependent Cyclic Electron Transport Modulates Linear Electron Transport Rate in <i>Arabidopsis thaliana</i>
                - in pressを脱していたので、とりあえず落としてAbstのみ
                    - LEFとCEFの解析のため、LEF活性が小さくなるようにPSII系のquintuple mutant ($\Delta5$) を作成
                    - dark-light transition時に、$\Delta5$はLEFの低下をCEFで補っており、NPQが活発
                    - $\Delta5$に更にqE, NDH-CEF, or pgr5-pgrl1の欠損を付加して (sextuple...)、PGR5経路の重要性を提示
                    - pgr5のsingle mutantだと変動光致死だが、$\Delta5$-pgr5のsextupleだとサバイヴ
                - CEF/LEF or CET/LETはどっちが主流になるだろう
                    - 寺島ラボ、Chowラボ、三宅ラボが`F`だからそっちで書いているが、Aroラボ、鹿内ラボ、Allakhverdievラボは`T`
                    - インパクトがある論文を書きがちなのは、molecularな研究が多い後者
            
            - 雑記
                - physiol plant投稿中の論文がようやくeditor assignまで進んだ
                - PCE論文のproofの第2稿が届いて確認
                    - 現所属表示の関係で、ダブルコレスポなのに自分にだけ*がついてやや難ありなので、修正を依頼
                    - 前回の指摘で数字か記号かアルファベットで現所属を表示して、といったのが若干うまくなかった、と反省
                - 科研の話を先生とちらほら
                    - 自分のなかで学振課題の比重がかなり重いから、いろいろ考える
                    - 若手 & 萌芽で出したらというアドバイス
                    - 仮に３つ抱えたら、単独では実施しきれない
                        - 学生主導でっていうのはぼくの側の気持ちの問題で無理だなぁ
                        - テクニシャンさんを雇うってのは現実的にありえるのか？
                    
        - 10
        
            - 雑記
                - physiol plantへ投げた論文がAwaiting Reviewer Assignmentに
            
        - 11
        
            - 雑記
                - シンボリックリンクを使いこなせるようになり、非常にグッド
                - ただ、knitrだとシンボル側からアクセスできないっぽいので、やや難
            
        - 12
        
            259. [Zavafer et al. 2017; Sci Rep](https://www.nature.com/articles/s41598-017-07671-1); 低
                - Mechanism of Photodamage of the Oxygen Evolving Mn Cluster of Photosystem II by Excessive Light Energy
                - PSII光阻害の2stepが概ね終わったかんじ？
            
            - 雑記
                - スライドをreveal.jsに完全以降するべく作ってたけど、これは魔
                    - Rで出した図を差分表示するとき、オブジェクトの配置の手打ち感が致命的
                    - ここらへんをwrapするスクリプトを組むにはhtmlの簡単なお勉強がいる
                - 撤退するつもりでパワポいじったら久々すぎて、作り方を忘れている...
                - 結局、revealjsに戻る
                - 雑スラな人になる、という手もある
        
        - 13
          
            - 雑記
                - Philos Transが光合成特集っぽいので明日チェック@自宅
                    - すぐダウンロードできないと忘れてしまうからやっぱりよろしくない
                    - [toc](http://rstb.royalsocietypublishing.org/content/372/1730)だけはっとく
            
        - 14
        
            260. [Waese et al. 2017; Plant Physiol](http://www.plantcell.org/content/early/2017/08/14/tpc.17.00073?rss=1); 未刊・未取得
                - ePlant: Visualizing and Exploring Multiple Levels of Data for Hypothesis Generation in Plant Biology
                - Trontoのグループ
                - eLifeに出して落ちてそう (しょうもない感想)
                
            - 雑記
                - 電子伝達モデル論文がようやく査読開始
                - 今日は終日測定、あいまに生環工スライドづくり
                    - いちおう、最低ラインには達したかんじ？
                
        - 17
        
            261. [Ruban 2017; Phil Trans R Soc B](http://rstb.royalsocietypublishing.org/content/372/1730/20160393); <FONT color = "green">中</FONT>
                - Quantifying the efficiency of photoprotection
                - qPd推し
                
            262. [Tayler & Long 2017; Phil Trans R Soc B](http://rstb.royalsocietypublishing.org/content/372/1730/20160543); 中
                - Slow induction of photosynthesis on shade to sun transitions in wheat may cost at least 21% of productivity
                - だろうさね
            
        - 18
        
            263. [Osmond et al. 2017; Funct Plant Biol](http://www.publish.csiro.au/FP/FP17024); 高
                - Relative functional and optical absorption cross-sections of PSII and other photosynthetic parameters monitored *in situ*, at a distance with a time resolution of a few seconds, using a prototype light induced fluorescence transient (LIFT) device
                - “PAMとほとんど同等かそれ以上の情報をクロロフィル蛍光から拾ってくるのに、LIFTは多くの文献で言及されていない”
                    - 見落としていて申し訳ない気持ち
                    - Walzと組んでガンガン普及させてるPAMと比べるとどうしても...
                - [Soliense](http://www.soliense.com/index.php)という会社が商品化担当らしい
                    - おしゃれなページだが、Footerがはみ出している
                    - 代理店を問い合わせる
                - 複写依頼で1405円也
            
            - 雑記
                - [キプロスでCIGRの国際学会](http://www.cigr2018.org/)
                    - 北キプロスはトルコがバックになって独立体裁だが、国際的には承認されていないらしい
                    - 会場は北
                    - 12/14がearly bird締め、翌01/05がabst締め
                - ついでに[IHC](http://www.ihc2018.org/en/WORKSHOPS.html)
                    - 10/31がabst締め
                
        - 19
        
            264. [Lichtenberg et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/08/18/pp.17.00820?rss=1); 中・未刊・未取得
                - Light sheet microscopy imaging of light absorption and photosynthesis distribution in plant tissue
                - この技術、最近ぽつぽつ出ているが、はやるか？
            
        - 20
        
            265. [Tikkanen & Grebe 2017; Physiol Plant](http://onlinelibrary.wiley.com/wol1/doi/10.1111/ppl.12618/abstract); 
                - Switching off photoprotection of photosystem I – a novel tool for gradual PSI photoinhibition
                - データがほぼないが、１次研究ではないのか？
                - 測定光と、PSII過剰励起光と、阻害誘導用の飽和パルス光を併用して、系間のRedoxを制御する、というコンセプト
                - tipsが多すぎてジェネラルな技術にはなりえない、と個人的には思う
                
            - 雑記
                - つい光合成生理系の論文に目が行くが、今後を考えると改めねば
                - reveal.jsにかなり親しんできた
        
        - 21
        
            266. [Nichelmann & Bilger 2017; Planta](https://link.springer.com/article/10.1007/s00425-017-2752-2); 低
                - Quantification of light screening by anthocyanins in leaves of *Berberis thunbergii*
                - 一応ダウンロードだけ、って感じ
        
            - 雑記
                - LIFTが商業レベルで出ていたので、estimate依頼
                - 日本の代理店がない場合、めんどうな気がするなぁ
        
        - 22
        
            - 雑記
                - 学会スライドの練習
                    - プロジェクション型だとだいぶ色が薄いなぁ
                    - 結構修正
                - 「grantに含めることを決めたら見積書を出すからもう一度連絡しなさい」スタイルはだるい
        
        - 23
        
            - 雑記
                - rmd + revealスタイルはやっつけスライド作るのに最強だ (新入生への説明スライド作成)
        
        - 24
      
            - 雑記
                - physiol plantのがWaiting Editor decisionに
                    - 査読が8日で短すぎだからrejectな気がする
                    - もともとダメ元だったのでさもありなん感はある
                    - 次どこにだそう
                - スキャナ (ScanSnap ix500) が届いた
                    - 速いしコンパクトだしめちゃくちゃいい
                    - デメリットはソフト周りがばらついていて、無駄機能が多いくらい？
                    
        - 25
        
            267. [Su et al. 2017; Science](http://science.sciencemag.org/content/357/6353/815); 無
                - Structure and assembly mechanism of plant C<sub>2</sub>S<sub>2</sub>M<sub>2</sub>-type PSII-LHCII supercomplex
                - 構造解析系
                - M2のattach/detachを調節して集光機能を変えているとかそんな感じ
                - 金の小槌で力いっぱい叩く系だという認識
            
            - 以下、Forthcoming papersブックマークを削る
            
            268. [Schymanski & Or 2016; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12700/abstract); 無
                - Wind increases leaf water use efficiency
                - ETH
                
            269. [Miner et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12871/abstract); <FONT color="green">低</FONT>
                - Estimating the sensitivity of stomatal conductance tophotosynthesis: a review
                - Colorado State Univ & UCB
                - 参考になりそう
            
            270. [Engineer et al. 2016; Trend Plant Sci](http://www.sciencedirect.com/science/article/pii/S1360138515002290); <FONT color="green">低</FONT>
                - CO<sub>2</sub> sensing and CO<sub>2</sub> regulation of stomatal conductance: advances and open questions
                - UC San Diego
                - とりあえず
        
        - 28
        
            271. [Goltsev et al. 2016; Rus J Plant Physiol](https://link.springer.com/article/10.1134/S1021443716050058); <FONT color="green">低・引</FONT>
                - Variable chlorophyll fluorescence and its use for assessing physiological condition of plant photosynthetic apparatus
                - Allakhverdiev、Kalajiなど
                - OJIPカーブ周りの解説
                - しっかりしたメソドロジー系レビュー
            
            - 雑記
                - reject with invitation of resubmission を戦うことにした
                - 休んでから考えると、案外やれる気になる
                - これで負けるとどん底な気持ちになるんだろう
        
    - 09
        
    
        - 04
        
            272. [Szechyńska-Hebda et al. 2017; Front Plant Sci](http://journal.frontiersin.org/article/10.3389/fphys.2017.00684/abstract); <FONT color="green">低・未刊・未取得</FONT>
                - Electrical Signalling, Photosynthesis and Systemic Acquired Acclimation
                - Systemic regulationの人たち
                
            - 雑記
                - 学会から帰還、学会中も新着論文はみていたが、ちょうど少ないタイミングだった
            
        
        - 05
        
            273. [Suthaparan et al. 2017; J Photochem Photobiol](http://www.sciencedirect.com/science/article/pii/S1011134417307327); 低・未刊・未取得
                - Daily light integral and day light quality: Potentials and pitfalls of nighttime UV treatments on cucumber powdery mildew
                - ノルウェーのグループ
                - UVでのうどんこ病抑制効果は、栽培時の高PFD、長明期、高青PFDで低下、UV->R->明期で向上
                - とりあえず２次関数でフィットするメンタリティが理解できないが、何かが見つかっているのかもしれない
            
            - 雑記
                - 科研費をもぞもぞと書き始めた
                - 0稿までがしんどいなぁ
                - 論文も書かないと...
        
        - 06
        
            274. [Kawada et al. 2017; Biol J](http://www.sciencedirect.com/science/article/pii/S0006349517308081); 低
                - Spatially different tissue-scale diffusivity shapes ANGUSTIFOLIA3 gradient in growing leaves
                - [基生研プレスリリース](http://www.nibb.ac.jp/press/2017/09/06.html)から
                - カタチが拡散で決まる、というのは直感的にしっくりくる
                - かっこいい
                
            275. [Calvo et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.13065/abstract); <FONT color="cyan">無</FONT>
                - Are plants sentinent?
                - PCEじゃなかったら似非か、って思うところ
            
            - 雑記
                - 科研費学内締切は10/12
            
        - 07
        
            - 雑記
                - 研究者番号が付された (50813903)
                
        - 08
        
            - 雑記
                - ANU滞在用に推薦書x２がいる
                    - すっかり忘れていたけど、そりゃそうだ
                    - 来週火曜 (!) まで
                    - 草案作って現ボスとお師匠様に月曜送付
                    - あちらにお金を出してもらう場合であればもっと心にくるだろうけど、自前で研究費持ちだと気楽
                - 科研費申請は萌芽＋若手のダブルビームでいくことに
                    - パワーワーク (萌芽) vs シミュレーション (若手)
                    - テーマ的には後者が通った方が助かるけど、前者の方が通りそう
                    - ボス曰く、「仮に２つとも通ったら一方辞退もある」
                        - あるのか？
                        - 取らぬたぬきのなんとやら
                - 結局、週末に仕事が残った
                    - 学会はさんだせいか、ギアが落ちた
                    - クリエイティブ枠が多かった
                
        - 10
        
            276. [Liu & Last 2017; PNAS](http://www.pnas.org/content/early/2017/08/29/1712206114.abstract); 中
                - A chloroplast thylakoid lumen protein is required for proper photosynthetic acclimation of plants under fluctuating light environments
                - Michigan State Univのグループ
                    - Kramerの後ラボ？
                - 変動光に適切に順化とは...
                    - 強光時にすみやかに誘導される消去系がある、くらいのニュアンス？
                    - うまいことまとめると論文になりそうだけど、誰かやれよ、って感じ？
                - MAINTENANCE OF PHOTOSYSTEM II UNDER HIGH LIGHT 2 (MPH2; encoded by At4g02530)
            
            - 雑記
                - 推薦書案を送付
                
        - 11
            
            277. [Lawaetz & Stedmon 2009; Appl Spectrosc](http://journals.sagepub.com/doi/abs/10.1366/000370209788964548); 低
                - Fluorescence Intensity Calibration Using the Raman Scatter Peak of Water
                - 某学会の要旨で見て
                - Raman分光の原理などを少し勉強してざらっと
                - どのくらいの精度の測定器が必要なのか、が問題
            
            278. [Goldstein et al. 2017; Nat Ene](https://www.nature.com/articles/nenergy2017143); 未取得・低
                - Sub-ambient non-evaporative fluid cooling with the sky
                    - 放射冷却パネルデバイスで3--5度程度の冷却効果
                    - 温室とかに使えないかねえ
                    - フリーアクセスじゃないので行くか行かないか...
                    - Nature系列くらい全部購読しておいてほしいなぁ...
                    
            - 雑記
                - 誕生日の研究室作法に従い、ケーキを食す
                - 論文書きも佳境、明日中に再投稿できそう
            
        - 12
        
            279. [Deram et al. 2014; HortScience](http://hortsci.ashspublications.org/content/49/4/448.full); 20170912摘
                - Supplemental Lighting Orientation and Red-to-blue Ratio of Light-emitting Diodes for Greenhouse Tomato Production
                - カナダMcGillのグループ
                - 哲学のない実験系だ
                - Mendelayに推されて
                    - ScholarやResearchGateは光合成生理学系のサジェストが多いが、こっちはまだコレ系が多い
                    - profにあるデータをアップデートしてないからか
            
            280. [Lobo et al. 2013; Photosynthetica](https://link.springer.com/article/10.1007/s11099-013-0045-y); 低
                - Fitting net photosynthetic light-response curves with Microsoft Excel - a critical look at the models
                - ブラジルのグループ
                - パラメータ数振ってAICをみない人たち
                
            281. [Long et al. 1993; Planta](https://link.springer.com/article/10.1007%2FBF00195081?LI=true); 20170912概
                - Quantum yields for uptake of carbon dioxide in C<sub>3</sub> vascular plants of contrasting habitats and taxonomic groupings
                - いまさらダウンロード
                - `Björkman & Demmig 1987`のO<sub>2</sub>発生収率と比べると見えてくる
            
            282. [Tenreira et al. 2017; Plant Cell](http://www.plantcell.org/content/early/2017/08/31/tpc.16.00949); 無・未取得・未刊
                - A specific gibberellin 20-oxidase dictates the flowering-runnering decision in diploid strawberry
                - ジベレリン酸化酵素がイチゴの花成・ランナー形成の決定で支配的らしい
                - イチゴのランナーはコントロール難しいとかなんとか聞いたので気になった
                
            283. [Walker et al. 2017; Plant Cell](http://www.plantcell.org/content/early/2017/09/11/tpc.16.00961?rss=1); 高・未取得・未刊
                - Root architecture shaping by the environment is orchestrated by dynamic gene expression in space and time
                - 根での例だが、これはゴールしている
                - クアドラプル・ファースト、セクスタプル・セカンド、トリプル・サードという謎構造
                
            - 雑記
            
                - 再投稿用原稿を共著者へ送信
                    - F先生から電話でレスポンスがあってびびる
                    - M先生からも当日レスポンス
                    - 目上の人たちにこれをやられたら下は頑張るしかない
                    - レターを英文校閲依頼まで
                - 実験装置の校正に関する問い合わせに応答
                    - 先週月曜/火曜にwebフォームから送っての今日では話にならない
                    - ついでにフォームを受信した旨のメール通知がなかった、納品した製品のバージョンをこちらに問い合わせる、メールでという指定を無視して電話→ボスが対応→自分に連絡で２倍の時間をかけさせる、と減点３つ
                - 自分がPIになったらここは絶対使わないリストが増えるなあ
        
        - 13
            - 雑記
                - 英文校正まで終えて、論文投稿準備OK
                - 明日の朝一で共著者へ送信する
                    - 先生たちはこの時間でもメールを見たらPC開いて「見たよ」を返してくれてしまうから
        
        - 15
            - 雑記
                - 普段は自分が先に相手の情報をみるタイプなので、相手が自分の情報を持っている、というのはやりづらい
            
        - 16
            - 雑記
                - 前回もそうだったけど、Physiol Plant誌の編集幹事、担当editorへの割り当て遅い
            
        - 18
            - 雑記
                - 季節の変わり目で風邪気味
                - Newハンダゴテを買ったら非常に捗った
            
        - 19
        
            284. [Golovatskaya & Karnachuk 2014; Rus J Plant Physiol](https://link.springer.com/article/10.1134/S1021443715060084); <FONT color="green">低</FONT>
                - Role of green light in physiological activity of plants
                - ロシアの国研系の人たち
                - Mendeleyのレターから
                - 個人的には、緑色光の受容体周りは眉唾だと思っている
                    - 青色光受容体の一部が緑バンドで反応し、それを除外できているのかが不明瞭な例が多い
                        - 緑あるだろう、を仮説でスタートするタイプの実験が多い印象
                    - 緑をセンスする受容体の機能はFR受容体と重複することから冗長な機能になる
                        - ただ、青色光受容体が複数あることからも、重複自体はあるのでこれは微妙
                    
            285. [Morales et al. 201X; Plant Physiol](http://www.plantphysiol.org/content/early/2017/09/18/pp.17.00779); 中・未刊・未取得
                - In silico analysis of the regulation of the photosynthetic electron transport chain in C3 plants
                - Wageningenのシミュレーション組 & Kramer、筆頭は博士学生
                - 自分のD論もそうだけど、in silico系ってのは設計した時点で終わるから、解析というのは変な気もする
                - こういうのに引用される人間になりたい
                
            - 雑記
                - さきがけ・CRESTの結果が出た
                    - 元ラボの性格的にそういうのから離れがち
                    - でもさきがけに出せるようなネタを考えないと、のたれ死にそう
                - ANU行きが着々と
                    - visiting fellowなどの滞在者用のシステムがwebにあってよくできている
                    - 滞在先の先生は名誉教授で受入はできないので、形式的には受入先が別ラボとなる
                    - やりづらそう
                    
        - 20
        
            - 雑記
                - visiting fellowでVISAを出すには、研究計画の文書が必要
                    - 「ざっくりした話は前したから、とりあえず書いて」とのお達しで書く
                    - 科研もありーのくそ忙しい
                - PhysiolPlant誌は、Round2に無事進んだ
                    - 担当editorさんは仕事速いのに
                    
        - 21
        
            286. [Carlos & Ballaré 2017; TPS](http://www.cell.com/trends/plant-science/fulltext/S1360-1385(17)30200-5?rss=yes); <FONT color="green">20170921済</FONT>
                - Phytochrome Responses: Think Globally, Act Locally
                - phyB系のhyponastyはlocally ristricted response
                - tipでのFR感知→auxinのpetioleへの移動→auxinの屈曲→hyponasty (`Pantazopoulou et al. 2017`と`Michaud et al. 2017`)
                    - “... rosette plants have evolved a clever system to concentrate light sensing in the outermost tip of the leaf and to relay the information to the leaf base, ”
                    - `Pantazopoulou et al. 2017`での3Dモデルと光環境シミュレートによると、adaptive (なにとくらべて？)
                    - 読まないと
                    
          287. [Michaud et al. 2017; PNAS](http://www.pnas.org/content/114/28/7444); 中
              - Local auxin production underlies a spatially restricted neighbor-detection response in <i>Arabidopsis</i>
              - `Carlos & Ballaré 2017`から
              - 自分との関係性から、`Pantazopoulou et al. 2017`の方が優先
          
      - 22


          - 雑記
              - ANUの方の研究計画はOK
              - 科研にも混ぜ込む感じにする
                  - 萌芽と若手の内容をスイッチ
                  
      - 24
      
          288. [Grübler et al. 2017; Plant Physiol](http://www.plantphysiol.org/content/early/2017/09/21/pp.17.00982); 低・未刊・未取得
              - Light and plastid signals regulate different sets of genes in the albino mutant pap7-1
              - Pfanschmidtグループなので、きっと面白い
          
          289. [Arana et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.13076/abstract); 低・未刊・未取得
              - Physiological and molecular mechanisms underlying the integration of light and temperature cues in Arabidopsis thaliana seeds.
              - 初見のアルゼンチンのグループ
              - 種でなければマスト論文だけども
              
          - 雑記
              - ANU研究計画をC先生に送付
          
      - 25
      
          290. [Fanourakis et al. 2017; EEB](http://www.sciencedirect.com/science/article/pii/S0098847217302204); 20170925摘・未刊
              - Differential effects of elevated air humidity on stomatal closing ability of <i>Kalanchoë blossfeldiana</i> between the C3 and CAM states
              - Aarhus大学 (Denmark) のOttosen Lab
                  - このグループは結構近しい内容だから気になっている
                  - 純・農業工学、って感じ
              - CAM-C3の両態をとるカランコエでhigh RHのgs影響を評価
                  - high RHのgs低下はC3状態に限られるらしい
              
          291. [Bressan et al. 2017; Photosynth Res](https://link.springer.com/article/10.1007/s11120-017-0444-1); 20170925摘
              - Loss of LHCI system a ects LHCII re-distribution between thylakoid domains upon state transitions
              - Verona組
              - `Bressan et al. 2016; Nat Plants`の続き
              - LHCIを4つ潰すと、PSIIが補填するが、state transitionがうまいこと働いていないらしい
              - これほど崩してもphenotypeに出ない、ってすごいよなぁ
              - abstがちょっと下手くそな気がする (with respect toが３回とか)
              
          - 雑記
              - 科研にくるしむ
                  - なによりも手が足りない
                  - 周りの手を期待できないのがきついなぁ
              
      - 26
      
          - 雑記
              - ANU滞在のノミネーションまで終わった
              - 科研が終わったらまとめよう
          
      - 27
      
          - 雑記
              - 研究機器商社のバグ入り自作クソソフト (ver違いのマニュアル付き) のせいで無駄な時間を喰った
              - O大からK先生、E先生、Jさんが来研
                  - はやくて引き出すのうまい人と喋るのは楽しい
              - 留学生fromベトナムが部屋に新加入
                  - 英語うめーな... (自分が下手なだけ)
              
      - 28
      
          292. [Laisk & Oja 2017; Photosynth Res](https://link.springer.com/article/10.1007%2Fs11120-017-0439-y); 中
              - Kinetics of photosystem II electron transport: a mathematical analysis based on chlorophyll fluorescence induction
              - CEF-PSIIにフォーカスしている印象
              - よまないとだけど、Laiskの論文はとてもしんどい