---
title: "MyPhrases"
output:
  html_document:
    toc: true
    toc_float: true
layout: post
categories: bookmarks
tags: memo
---

# 書き英語


## 平均値が反復で揃わないとき

> Because of the destructive nature of low-temperature experiments, the results reported in Table 2 required a number of measurements on different sections from the same leaf in order to approach meaningful averages. From the standard deviations and number of measurements, it seems likely that the average values for each experiment are significant.
> (Canaani et al. 1984; PNAS)


## Enhancement effect の説明によさそう。

> When photosynthesis is driven experimentally by two lights of different wavelength, the rate of photosynthesis with both lights may exceed the sum of the rates obtained with each beam alone.
> 

> If all LHCII detached from PS II upon phosphorylation becomes attached instead to PS I [95,96], then these results fall short of the required increases in absorption cross-section of PS I of at least 16% for broad-band excitation and of 40-70%for Chi b excitation.
> (Allen 1992; BBA)


## 解釈しづらい結果が出たとき

> ~ cannot be distinguished and requires further investigation, which however is beyond the scope of the present study.
> (Wargner et al. 2008; Planta)

> At the present state, we do not have an explanation for this difference.


## AはBと相関がある (A縦軸、B横軸)

- A (show, represent) a (considerable, strong, positive correlation with B.
    - Dark respiration rate reportedly represents a positive correlation with the amount of leaf N per LA.


## AはBと関係している (A→B)

- A can be involved in B
- A can be (closely) related to B
- (an) involvement of A in B can be suggested.
- B is (strongly) dependent on A.
    - leaf photosynthetic capacity of C3 plants is strongly dependent on the amount of N.


## AはBによって説明できる (B⇒A)
- A can be (largely, partly) accounted for by B.
    - The light-induced systemic regulation was largely accounted for by PPFD.
- B might explain A.
- A can be attributable to B.
- (possible, likely) causes of A are B 



# オーラル系

<FONT color="grey">Last update: 2016-05-03  </FONT><br>

<FONT color="green">フォーマル</FONT>  
<FONT color="orange">フランク</FONT>  
<FONT color="red">NG</FONT>  


## イントロ
大分類 (光合成の話です)  

- Today, I'd like to talk to you about light use efficiency of the photosynthesis.

中区分 (光合成の中でも)

- There are three things I’d like to cover today.


- I will share with you some of recent data.
- I will show you some of the highlight data.  

### 背景知識の紹介
レベルに合わせて

- Let me refresh your memory on XXX
    - "Let me remind you of XXX" は避けた方が無難  



## まとめ

- We are coming to the end of today’s presentation.  
- I’m now going to give a brief summary of what we have covered.  
- Just to summarize, let’s quickly look at the main points again.  



## つなぎ
テーマの変わり目、スライドの変わり目、では一言を  

ここまでのテーマをまとめる
- I think that covers the topic of XXX  
- Up to here, I have spoken about XXX

次のテーマ/スライドを誘導する  
- I’d like to start by looking at  
- Next, I’d like to talk about  
- Let’s move on to  

ラストのまとめを誘導する  
That brings us to the end of the final part.  



## 質疑応答

### 内容を確認する
迷う余地がないとき以外は、「〜という意味の質問でよろしいですか？」と確認するのが安全  

- Before I get to answer your question, let me just make sure that I understand you correctly.
- 



### 
バリエーションが欲しい  

- Sorry, I couldn't hear you very well.
- I didn't fully catch your question.
- Can you rephrase that more simply?
- I'm not following you, please repeat again.
    - I don't understand は失礼な言い方

「〜に関する質問であることはわかったのですが、細かいところを聞き漏らしました」と伝えたい

- I only heard you saying somthing about XXX, right?



### 締める
雰囲気でわかるけど、一応「この答えで満足いただけましたか？」

- Did I answer your question?
- <FONT color="orange">Am I clear?</FONT>  


それでもダメなら  
- I am not qualified to answer... .
- Still I can't get the point, so let me answer your question later on.
- Sorry, I’m having trouble understanding your question. Could we talk directly after this session?


--------

## まめ

- I <FONT color="red">want to</FONT> ~  
    - 幼児語らしい
    - I'd like to ~ で

- I am ~
    - 死語らしい
x    - I'm

- 図中でのred lines, red points  
    - lines in red, points in red の方がそれっぽい



