---
title: "PublicationList"
output: md_document
permalink: /publication_list/
layout: default
---

```{r, message = F, echo = F, results = 'asis'}
library(scholar)
library(magrittr)
library(dplyr)
library(knitr)
library(DT)
library(markdown)
# format: 
# 

ToRecord <-
  function(title, year, journal, type, url)
  c(Title = paste0("<a href=", url, ">", title, "</a>"), Year = year, Journal = journal, Type = type)

PublicationList <-
  matrix(byrow = T,
    ToRecord(
    "Light-induced systemic regulation of photosynthesis in primary and trifoliate leaves of <i>Phaseolus vulgaris</i>: effects of photosynthetic photon flux density (PPFD) <i>versus<i/> spectrum",
    2014,
    "Plant Biology",
    "Article (peer-reviewd)",
    "http://onlinelibrary.wiley.com/doi/10.1111/plb.12055/abstract")
  # ),
  # ToRecord(
  #   "Effects of supplemental lighting to a lower leaf using light-emitting diodes with different spectra on the leaf photosynthetic rate in sweet pepper",
  #   2013,
  #   "Journal of Agricultural Meteorology",
  #   "Article (peer-reviewd)",
  #   "https://www.jstage.jst.go.jp/article/agrmet/69/2/69_69.2.2/_article"
  # ),
  ) %>%
  t

colnames(PublicationList) = c('<em>Title</em>', 'Year', 'Journal', 'Type')
datatable(PublicationList, escape = F)  #
```


```{r eval = F, echo = F}
rmarkdown::render("~/Dropbox/KeachMurakami.github.io/PublicationList.Rmd")

knit(input = "~/Dropbox/KeachMurakami.github.io/PublicationList.Rmd",
     output = "~/Dropbox/KeachMurakami.github.io/PublicationList.md")
```