---
output: revealjs::revealjs_presentation
---

# Demo1 | show figures incrementally

## hook1

```{r}
library(knitr)

hook_fragment <-
  function(before, options, envir) {
    if (before) {
      before_chunk <- paste0("<div class='fragment' data-fragment-index='", options$fragment,"' style='position:absolute;top:0;left:0'>")
    } else {
      after_chunk <- "</div>"
      ## code to be run after a chunk
    }
}

knit_hooks$set(fragment = hook_fragment)
```


## rmarkdown1

```{r}
# <div style="position:relative; top:0px; width:700px; height:500px; margin:0 auto;">
# ```{r fragment = 1, echo = F}
# library(ggplot2)
# ggplot(iris, aes(Sepal.Length, Petal.Length, col = Species, group = Species)) +
#   geom_point()
# ```
# ```{r fragment = 3, echo = F}
# ggplot(iris, aes(Sepal.Length, Petal.Length, col = Species, group = Species)) +
#   geom_point() +
#   geom_smooth(method = "lm")
# ```
# </div>
# <br>
# <div class="fragment" data-fragment-index="2">- Plot points</div>
# <div class="fragment" data-fragment-index="4">- Add regression lines</div>
```

## output1

<div style="position:relative; top:0px; width:700px; height:500px; margin:0 auto;">
```{r fragment = 1, echo = F}
library(ggplot2)
ggplot(iris, aes(Sepal.Length, Petal.Length, col = Species, group = Species)) +
  geom_point()
```
```{r fragment = 3, echo = F}
ggplot(iris, aes(Sepal.Length, Petal.Length, col = Species, group = Species)) +
  geom_point() +
  geom_smooth(method = "lm")
```
</div>
<br>
<div class="fragment" data-fragment-index="2">- Plot points</div>
<div class="fragment" data-fragment-index="4">- Add regression lines</div>

```{r}
devtools::session_info()
```