---
title: "revealjsでincrementalに図を表示する (R"
output: html_document
layout: post
tags: lab R revealjs presentation
---

```{r setup, message = F, warning = F, include = F}
library(ggplot2)
knitr::opts_chunk$set(echo = T, include = T)
```

{revealjs}メモ

最近は基本的に[`revealjs`](https://github.com/hakimel/reveal.js/)でスライドを作るようにしている。スライド内で、差分的に画像を出したい場合のメモ (点プロットで散布図 -> 回帰直線を追加、など)。

```{r}
fig1 <-
  ggplot2::ggplot(iris, aes(Sepal.Length, Petal.Length, col = Species, group = Species)) +
  ggplot2::geom_point()

fig2 <-
  fig1 +
  ggplot2::geom_smooth(method = "lm")

cowplot::plot_grid(fig1, fig2)
```

以下のように、rmarkdown上で直接htmlタグを入れてもいいが、面倒。

```
 # <!-- 先に領域を作る -->
 # <div style="position:relative; top:0px; width:800px; height:600px; margin:0 auto;">
 # <!-- 領域内で同じ絶対位置にプロット -->
 # <div style="position:absolute;top:0;left:0;" class = "fragment" data-fragment-index="1">
 # ```{r}
 # fig1
 # ```
 # </div>
 # <div style="position:absolute;top:0;left:0;" class = "fragment" data-fragment-index="3">
 # ```{r}
 # fig2
 # ```
 # </div>
 # </div>
 # 
 # <div class="fragment" data-fragment-index="2">- 散布</divs>
 # <div class="fragment" data-fragment-index="4">- 回帰</div>
```

`knitr`の`hook`で解決する。

```{r}
hook_fragment <-
  function(before, options, envir) {
    if (before) {
      before_chunk <- paste0("<div class='fragment' data-fragment-index='", options$fragment,"' style='position:absolute;top:0;left:0'>")
    } else {
      after_chunk <- "</div>"
      ## code to be run after a chunk
    }
}
knitr::knit_hooks$set(fragment = hook_fragment)
```


```
# <div style="position:relative; top:0px; width:800px; height:600px; margin:0 auto;">
# ```{r fragment = "1", echo = F}
# fig1
# ```
# ```{r fragment = "3", echo = F}
# fig2
# ```
# </div>
# 
# <div class="fragment" data-fragment-index="2">- 散布</divs>
# <div class="fragment" data-fragment-index="4">- 回帰</div>
```

```{r html_download, echo = F}
  source("https://raw.githubusercontent.com/KeachMurakami/KeachMurakami.github.io/master/_supplemental/demo/reveal_frame_by_frame_figure.html")
html <- 
  download.file(url= "https://raw.githubusercontent.com/KeachMurakami/KeachMurakami.github.io/master/_supplemental/demo/reveal_frame_by_frame_figure.html",
                destfile = "./figure/source/2018-03-19-frame_by_frame_fig_in_reveal/demo.html")
```

<iframe src="source/2018-03-19-frame_by_frame_fig_in_reveal/demo.html" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> minimalなRmdファイル -> <strong> <a href="https://github.com/KeachMurakami/KeachMurakami.github.io/blob/master/_supplemental/demo/reveal_frame_by_frame_figure.Rmd" title="reveal_frame_by_frame_figure.Rmd" target="_blank">.Rmd</a> </strong></div>


#### 参考

[hakimel/reveal.js](https://github.com/hakimel/reveal.js/)  
[Hooks](https://yihui.name/knitr/hooks/)  

```{r}
devtools::session_info()
```
