---
title: "AusPheno16予定など"
output: html_document
layout: post
categories: Symposium
tags: lab log Symposium
---

```{r, message = F, warning = F}
library(dplyr)
library(magrittr)
library(lubridate)
library(data.table)

Bus_route_files <-
  dir("~/Dropbox/Symp/2016AusPheno/Canberra_Bus/", pattern = "csv", full.names = T)

Timetable <-
  lapply(Bus_route_files, function(files){
    timetable <-
      files %>%
      fread
    
    forSort <-
      timetable %>%
      select(2) %>%
      set_names("sort")
              
    timetable %>%
      bind_cols(., forSort) %>%
      na.omit %>%
      mutate(sort = hm(sort)) %>%
      arrange(sort) %>%
      select(-sort)
  })
```

```{r, eval = F, echo = T}
library(leaflet)
mapAusPheno <-
  data.frame(
      ID = c("Bus Stop Route39<br>Aspinall St. after Antill St.", "Bus Stop Route56-58<br>Federal Hwy. opp. Phillip Av.", "Hotel", "Meet Prof.WSC<br>14:30 on Thu", "CSIRO Discovery Centre", "University House<br>BBQ 6.30 on Mon", "The Shine Dome<br>Public Seminar 6:30 on Wed"),
      lng = c(149.165486, 149.1448491, 149.166662, 149.116568, 149.1146661, 149.118699, 149.122649),
      lat = c(-35.229084, -35.2363273, -35.224953, -35.277383, -35.2737138, -35.283830, -35.283693)
    ) %>%
  leaflet %>%
  addTiles %>%
  setView(lng = 149.1350328,lat = -35.2656066, zoom=12) %>%
  addPopups(lng=~lng,lat=~lat,popup=~ID)

print(mapAusPheno)

library(DT)  
# Route39行き
datatable(Timetable[[2]])
# Route39帰り
datatable(Timetable[[1]])
# Route56--58行き
datatable(Timetable[[4]])
# Route56--58系帰り
datatable(Timetable[[3]])
```

# バス
終バスが結構早いので注意する  

## Route39行き
`r knitr::kable(Timetable[[2]])`

## Route39帰り
`r knitr::kable(Timetable[[1]])`

## Route56--58行き
`r knitr::kable(Timetable[[4]])`

## Route56--58系帰り
`r knitr::kable(Timetable[[3]])`

### 参考ページ
[AusPheno16](http://icec-auspheno2016.com.au/)  
[Transport Canberra](https://www.transport.act.gov.au/)  
[leafletではじめるRによる地図プロット](https://kazutan.github.io/JapanR2015/leaflet_d.html)  
