---
title: "CV"
output: html_document
permalink: /about/CV/
layout: default
---

<FONT color="grey">Last update: 2016-05-03  </FONT><br>

--------------

村上 貴一 (むらかみ きいち)

東京大学 大学院農学生命科学研究科の[生物環境工学研究室](http://www.kankyo.en.a.u-tokyo.ac.jp/index-E.htm)所属の博士課程学生 (D3) です。  

-------

Address: 1-1-1 Yayoi, Bunkyo, Tokyo, 113-8657 Japan  
Office: Room #413, Building 7A  
E-mail: 4518921281(ATSIGN)mail.ecc.u-tokyo.ac.jp  

```{r, message = F, echo = F}
library(magrittr)
library(dplyr)
library(knitr)
```

### 専門分野  
生物環境工学  
光合成生理学  

### 研究テーマ  

#### 高等植物の光合成電子伝達の光質応答  

------

### 学歴
```{r Education, echo = F}
data.frame(
  Year = c("2008.03",
           "2008.04",
           "2010.04",
           "2012.03",
           "2012.04",
           "2014.03",
           "2014.04"),
  Degree = c("鳥取県立米子東高等学校 卒業",
             "東京大学 理科一類 入学",
             "東京大学 農学部 生物・環境工学専修 進学",
             "同 卒業",
             "東京大学 大学院農学生命科学研究科 生物・環境工学専攻 修士課程 入学",
             "同 修了",
             "東京大学 大学院農学生命科学研究科 生物・環境工学専攻 博士後期課程 進学"
             )
  ) %>%
  kable
```

------

### 職歴
```{r Professional_Experience, echo = F}
data.frame(
  Year = c("2014.4-2017.3"),
  Category = c("日本学術振興会 特別研究員 (DC1)"),
  Advisor = c("受入研究者: 富士原 和宏 教授")
) %>%
  kable
```

------

### 学会活動
```{r Academic_Society_Membership, echo = F}
data.frame(
  Year = c("2012-", "2013-"),
  Society = c("日本生物環境工学会",
              "日本農業気象学会")
) %>%
  kable
```