---
title: "MyTemplate"
output:
  html_document:
    toc: true
    toc_float: true
layout: post
categories: bookmarks
tags: memo
---

## Abstract

### 戦略

- 欠かせない語句一覧を書き出す
    - この時点である程度の文字数が固まる
    - それに加えて何が書けるかが決まる
- ラフに書き上げる
    - 規定の文字数を超える場合がほとんど
- 削る
    - 流れを変えることを考える
    - 小手先の技 (`These results suggest that ...` -> `~, suggesting ...`とか) は最終手段

### 書くこと

0. (トピックの概要)
    - 一般紙になるほど記載されている場合が多い印象
    - いきなり専門の話に入っても伝わらないから
    - 1文でさらっとまとめる
1. 取り組んだ問題
2. 着眼点
3. 対象
4. 手法
5. 結果 + 考察
6. 結論


`formula = zzz ~ (xxx|env) * (yyy|env)`

#### 0. トピックの概要


#### 1. 取り組んだ問題

**現象確認型**

- We investigated the effects of `xxx` and `yyy` on the `zzz` using `PLANT` in a growth-chamber experiment (RM2016SH).
- The objectives of this work using `PLANT` were to examine whether the `xxx` is related to `zzz` (KM2014PB).


**現象解析型**

- The mechanisms underlying the `zzz` and its acclimation to the `xxx` are quantitatively addressed, combining in vivo physiological and in vitro molecular methods (SWH2012PC).
- To assess the roles of `xxx` and `yyy` under `env` condition, we grew the wild type and `MUTANT` mutant of `PLANT`, we measured ~ (MK2014PCP).


**仮説検証型**

-


**手法開発型**

- Using simultaneous measurements of `xxx` and `yyy`, we determined the `zzz`, in the mesophyll cells for individual leaves of `PLANT` (AL1996PP).
-


#### 2. 着眼点


#### 3. 対象


#### 4. 手法


#### 5. 結果 + 考察


#### 6. 結論

- Thus, `xxx` and `yyy` were demonstrated to affect `zzz` (RM2016SH).
- Based on these results, we concluded that the `xxx` has little effects on the `zzz` and that the regulation of `zzz` was largely accounted for by `yyy` (KM2014PB).
- We show quantitatively that leaves acclimate their `zzz` to `xxx` and how this `zzz~xxx` the wavelength dependence of the photosystem excitation balance and quantum yield for CO2 fixation. This also proves that combining different wavelengths can enhance quantum yields substantially.
- The results suggest that `xxx` is a potent stress to `zzz` and that `yyy` is essential to protect `zzz` from this stress (MK2014PCP).

## その他

*Nature Plants*で散見された例

1. `zzz`が重要
    - `zzz` is essential for ...
    - `zzz` plays a vital role in ...
2. `xxx`が`zzz`に関与するが、その機構はよくわかっていない
    - `xxx` that leads to `zzz`, however, are poorly understood.
    -  however, whether `xxx` are possible without impacting `zzz` is debatable. 
3. そこで...
    - Here we evaluate ...
    - Here we show ...



## 参考

- [これから論文を書く若者のために](http://www.kyoritsu-pub.co.jp/bookdetail/9784320005952)