---
title: "CEF-PSI史"
output:
  html_document:
    toc: true
    toc_float: true
layout: post
categories: Lab
tags: memo photosynthesis
---

## PGR5/PGRL1経路

- CEF-PSIの大部分を占める  
- antimycin Aで活性を止められる  
- 複合体形成は違えど、根本は光合成生物に共通  

### タンパク質・変異体の同定  

#### PGR5; PRTON GRADIENT REGULATION 5
[Munekage et al. (2002; Arabidopsis)]() が強光下でのqE上昇が生じないmutant (<i>pgr5</i>) を発見  
低NPQ、P700が還元されやすい、Fd依存のPQ還元が少ない、などの形質からCEF-PSIであると判定  

#### PGRL1; PGR5-LIKE PHOTOSYNTHETIC PHENOTYPE 1  
[DalCostro et al. (2008; Arabidopsis)]()   
Arabidopsisには2コピーの遺伝子が存在  



### 特徴

未読[Finazzi et al. ()]() がCEF-PSIとState transitionのリンクについて言及  
[Takahashi et al. (2013; Chlamidomonas)]() がstateに依らずCEFが生じることを示している  
いずれでも起こるがstate 2・無酸素状態でFluxの方が大きい (単純にEEDのシェアが変わっているからだろう)  

[Iwai et al. (; Chlamidomonas)]() 
state2のPSI複合体を単離、FdからCyt <i>b</i>への電子の流れ (還元) を観察  
CEFが生じた系は、PSI複合体、LHCII、Cyt <i>b<sub>6</sub>/f</i>複合体、FNR、PGRL1を含む  

* CAS (Ca^2+^ sensor) and ANR1 (anaerobic response 1) もCEF超複合体に含まれるらしい (未読[Terashima et al. 2012, PNAS](http://www.pnas.org/content/109/43/17717.abstract))  

PGR5が見つからなかったため、ChlamyとArabiの違いがそこら辺なのか、という噂だったが、[Johnson et al. ()]()がChlamyで<i>pgr5</i> mutantを単離し、<i>pgrl1</i>と<i>pgr5</i>が同様の形質を示すことを明らかにしている  

Arabiではantimycin AでPGR5/PGRL1経路が止まるが、WTのChlamyには耐性があり、PGR5/PGRL1経路が止まらない ([]())  
しかし、PGR5に関係ない部分をいじるとantimycin A耐性がなくなる ([]())  

antimycin Aが作用する対象 (部位？) は2016年でも ([Yamori and Shikanai (2016)]()) 不明  




### NDH経路

裸子植物 (gymnosperm) だとまた話が違うらしい。進化の過程で云々。