---
output: html_document
---

ダウンロードしたことすら忘れるので、ダウンロードした論文とそのひとことメモ

- `低中高`は優先度
- `未刊`はin press
- `費`はアクセス権がなくて有償なもの、おもに書籍

```{r, eval = F}
library(rvest)
library(magrittr)
library(tidyverse)

data_html <-
  "https://github.com/KeachMurakami/KeachMurakami.github.io/blob/master/_supplemental/Literatures.Rmd" %>%
  read_html

num_paper <-
  data_html %>%
  html_nodes("article") %>%
  html_nodes(xpath = "//ul//li//p//a")
  # html_nodes("p") %>%
  html_structure()

```


-----

- 2017
    
    - 01
        
        - 19
        
            1. [Gimenez-Ibanez et al. 2017; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.14354/abstract); 中
                - バクテリアの感染と気孔開度の調節の仕組みに関して
                - 感染で一度閉じた気孔を、Coronatineというphytotoxinにより再度開かせる
                - 後輩に投げつける
            
            2. [de Vries et al. 2017; Trends Plant Sci](http://www.sciencedirect.com/science/article/pii/S1360138516302060); 高・未刊
                - 光獲得と対被食のトレードオフに関して
                - R/FR比がメイン
        
        
        - 20
    
            3. [Ballaré & Pierik 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12914/abstract); 高
                - Shade avoidance syndrome
                - “syndrome”ってつけるとキャッチーだ
            
            4. [Uematsu et al. 2017; New Phytol](http://onlinelibrary.wiley.com/wol1/doi/10.1111/nph.14416/abstract); 低
                - いつか出してやると思っている*New Phytologist*に、研究科の元先輩がacceptされていたので記念に
                - 水田イネへの放射性セシウムの吸い上げについて
        
        
        - 21
        
            5. [Wientjes et al. 2017; BBA](http://www.sciencedirect.com/science/article/pii/S0005272817300099?np=y); 中
                - 画像解析 & 蛍光寿命解析でPSII/PSI比を面的に
                - 以下の`Iermak et al. 2016`の発展
                
            6. [Iermak et al. 2016; BBA](http://www.sciencedirect.com/science/article/pii/S0005272816305564); 20170121済
                - `Wientjes et al. 2017`から
                - two-photonとFLIMで深度情報まで考慮して光化学系組成を解析
                    - 厳密には、LCHII/PSII比とPSII/PSI比
                    - PSII/PSIエネルギー分配の絶対定量はできない
                - 見逃してたので、投稿論文に追加する？
        
        
        - 24
        
            7. [Galvão & Fankhauser 2015; Cur Opin Neurobiol](http://www.sciencedirect.com/science/article/pii/S0959438815000227); 低
                - 植物の光センシングに関する異分野への概説系レビュー
                - Chemical寄り
            
            8. [Razzak et al. 2017; PCE](http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12921/abstract); 高・未刊
                - ヨーロッパアカマツ苗の光強度 x R/FR比への応答
                - 胚軸長、色素蓄積など
                - 被子植物・裸子植物の差異を絡めている
                - abstractだとPCEに載るほどのものはない印象を受けるが...なにかあるんだろう
        
        
        - 25
        
            9. [Morena et al. 2017; J Photochem Photobiol B](http://www.sciencedirect.com/science/article/pii/S1011134416309733); 低・未刊
                - 長波長 (980 nm) LED光での*Pseudomonas aeruginosa* (緑膿菌) 繁殖の抑制
                - 口腔衛生、小児科学などの人たち
            
            10. [Munafò et al. 2017; Nat Hum Behav](http://www.nature.com/articles/s41562-016-0021); 高
                - 再現性の担保について
                    - *P*-hackingとか、そのあたり
                    - 去年のASAのstar-counting 統計の批判以来、流行っている
                    - *eLife*でも特集されてた
                        - [ココ](https://elifesciences.org/content/6/e23693)らへん
                        - 癌研究だとか、生体の実験でRCTだときついだろう
                - 探索的な研究だと仕方ない側面もあるよね、と思いつつ、着々と脱検定を進めている
            
            11. [Shirai et al. 2017; J Food Eng](http://www.sciencedirect.com/science/article/pii/S0260877416303739); 低
                - 食肉の表面から内部へのバクテリアの侵入のモデル化
                - 博士の公開審査で聞いたので
                - 「鉛直プロファイルの*in vivo*値とモデル推定値を比較していないのですか」という質問は、まっとうだけどしんどい
        
        
        - 26
        
            12. [Izumi et al. 2017; Plant Cell](http://www.plantcell.org/content/early/2017/01/25/tpc.16.00637.short?rss=1); 中・未刊
                - chlorophagyなるフレーズ
                - photodamageを受けた葉緑体が液胞中心に移動する
                - 「移動して、そのあとどうなる」が意図的に書かれていなさそう
            
            13. [Kono et al. 2017; PCP](https://academic.oup.com/pcp/article/doi/10.1093/pcp/pcw215/2948616/Photoprotection-of-PSI-by-Far-Red-Light-Against); 高
                - FRで変動光下でのPSI阻害が抑制できる話
                - 内容は既知のものなので、引用されている文献など、知識収集メインで読むべし
        
        
        - 28
        
            14. [Riikonen 2017; Forest Ecol Manag](http://www.sciencedirect.com/science/article/pii/S0378112716311173); 20170128済
                - Content of far-red light in supplemental light modified characteristics related to drought tolerance and post-planting growth in Scots pine seedlings
                - アカマツの苗木にFR添加したときの耐乾燥性とその後の成長
                - *in situ*水利用効率 (P~n~/g~s~) をRGB光源で測定した値で議論
                    - *in situ*な光 (=太陽光) のもとでは？
                    - 典型的な栽培光x測定光の交互作用問題
                - GLMMで、`ORIG x FR`項の係数を水準ごとに解析できるようダミー変数でバラすテクニック
                    - TS先生に今度あったときに話そう
            
            15. [Pierik & de Wit 2014; JXB](https://academic.oup.com/jxb/article-lookup/doi/10.1093/jxb/ert389); 低
                - Shade avoidance: phytochrome signalling and other aboveground neighbour detection cues
                - 群落の成長に伴うR/FRの変化と、その他の光質・物理的接触・VOCと関連付けてレビュー
                
            16. [Cocetta et al. 2017; BookChap](http://link.springer.com/article/10.1140/epjp/i2017-11298-x); 低・費
                - Light use efficiency for vegetables production in protected and indoor environments
                - 37.75 euro
                - D論周りとぴったしだけど、引用文献を見るにあまり得るものはなさそう...?
                - 年度末に学振の研究遂行経費が残っていれば落とす
