---
title: "MyBookmarks"
output:
  html_document:
    toc: true
    toc_float: true
layout: post
categories: bookmarks
tags: memo
---

-------


# 研究全般

## グループ

### 国内学会

- 定期的
    - [日本農業気象学会](http://www.agrmet.jp/) 毎年３月  
    - [日本光合成学会](http://photosyn.jp/) 毎年？５--６月  
    - [日本生物環境工学会](http://jsabees.org/) 毎年９月  
    - [園芸学会](http://www.jshs.jp/) 毎年３月＠関東・９月＠他地方  

- 積極的に参加したい
    - [日本植物学会](http://bsj.or.jp/) 毎年９月  
    - [日本植物生理学会](https://jspp.org/) 毎年３月  
    - [農業施設学会](http://www.sasj.org/) 毎年８--９月  
    - [生態工学会](http://www.see.gr.jp/) 毎年６月  
    - [日本生態学会](http://www.esj.ne.jp/esj/) 毎年３月  
    - [XXX]() 毎年Ｘ月  
    - [XXX]() 毎年Ｘ月  

- やや遠いが気になる
    - [日本生物工学会](http://www.sbj.or.jp/) 毎年９--１０月  
    - [日本芝草学会](http://www.jsts-online.com/start/) 毎年春秋開催  
    - [日本雑草学会](http://www.wssj.jp/) 毎年４月  
    - [日本バイオインフォマティクス学会](http://www.jsbi.org/) 毎年Ｘ月  
    - [XXX]() 毎年Ｘ月  

### 国外学会

- [American Society for Horticultural Science (ASHS)](http://www.ashs.org/)  

### 国際学会

- [International Society for Horticultural Science (ISHS)](http://www.ishs.org/) → [(イベントカレンダー)](http://www.ishs.org/calendar)  
- [International Society of Photosynthesis Research (ISPR)](http://www.photosynthesisresearch.org/)    

### 国内グループ

- [農研機構](http://www.naro.affrc.go.jp/)  
    - [気候変動対応プログラム](http://adpmit.dc.affrc.go.jp/index.html)  

### 国外グループ

- [NCERA-101/NCR-101](http://www.controlledenvironments.org/)  
- [UK CEUG](http://www.ceug.ac.uk/)  
- [Developing LED Lighting Technologies and Practices for Sustainable Specialty-Crop Production](http://leds.hrt.msu.edu/)  

### 国際グループ

- [IPCC](http://www.ipcc.ch/index.htm/)  



## 遺伝資源系ポータル  
使いこなすときが来る気がしない。  

- [Phytozome](https://phytozome.jgi.doe.gov/pz/portal.html) 
the Plant Comparative Genomics portal  
- [TAIR](http://www.arabidopsis.org/) The Arabidopsis Information Resource  
- [1001 Genomes](http://1001genomes.org/) A Catalog of Arabidopsis thaliana Genetic Variation  
- [SIGnAl](http://signal.salk.edu/) Salk Institute Genomic Analysis Laboratory  



## 書き仕事

### 英語  

- [LifeScienceDictonary](http://lsd-project.jp/cgi-bin/lsdproj/ejlookup04.pl) 共起表現が便利  
- [Academic Phrasebank](http://www.phrasebank.manchester.ac.uk/)  
- [科学英語メモ](https://www.gfd-dennou.org/arch/hiroki/homepage/english/english.html)  
- [科学英語メモ (新版)](https://www.gfd-dennou.org/arch/hiroki/homepage/english/english2.html)  
- [科学論文で役立つ英語](http://homepage1.nifty.com/Mercury/ohoyamak/index.html)  
- [論文英語ナビ](http://www.shiga-med.ac.jp/~koyama/eng/eng-index.html)  
- [英語例文を見て自然に英語・英会話を学ぶ](http://www.geocities.jp/kusumotokeiji/eigo.htm)  
- [コミュニケーション@見延庄士郎のHP](http://www.sci.hokudai.ac.jp/~minobe/education.html)  

### 査読
まだやったことないけど、近々くるだろう。

- [英語論文の査読表現集](https://staff.aist.go.jp/a.ohta/japanese/study/Review_ex_top.htm)

### 一般
普段遣いの英語がわからん

- [社会で役立つ英語習得のテクニック](http://www.f.waseda.jp/shinoda/technique-index.htm) 決まり文句など  



## 学会

- [学会発表の心得](http://takenaka-akio.org/index_01.html)  
- [伝わるデザイン 研究発表のユニバーサルデザイン](http://tsutawarudesign.web.fc2.com/)  

### スライド

### ポスター



## 進捗・報告

### ないとき  

- [沼 正作 博士 (1929-1992) ：沼研の伝説的なエピソード](http://scienceandtechnology.jp/archives/9655) あつい。  

### よい報告の仕方  

- [効果的にバグを報告するには](http://www.chiark.greenend.org.uk/~sgtatham/bugs-jp.html) プログラムに限らず、研究一般でも同じ。  



## 研究系ブログ   

### 研究者 (他分野)

- [発声練習](http://next49.hatenadiary.jp/entry/20080105/p3) とても参考になる。  
- [アレ待チろまん](http://www.aremachi.com/) 専門は分子細胞生理学っぽい。  
- [Take a Risk：林岳彦の研究メモ](http://takehiko-i-hayashi.hatenablog.com/) リスク学と統計学。  

### 企業・会社

- [日本環境計測のブログ](http://emj.sblo.jp/) 日本環境計測株式会社さん。エンジニア魂を感じる。  



## 研究助成

- [Science Portal](http://scienceportal.jst.go.jp/funding/application/) 研究助成情報  
- [キヤノン財団](http://www.canon-foundation.jp/index.html) 産業基盤の創生・理想の追求  
- [リバネス研究費](https://r.lne.st/grants/) 科学技術の発展と地球貢献の実現  
- [一般財団法人 旗影会](http://www.nakashima-foundation.org/kieikai/index.html) 畜産、畜産工業その他農畜産、食品工業等に関する学術研究  
- [公益財団法人 新技術開発財団](http://www.sgkz.or.jp/) 広く科学技術に関する独創的な研究や新技術 (会社への助成)  
- [公益財団法人 前川報恩会](http://www.mayekawa.org/) 球温暖化対策を目的とした、熱エネルギーの有効利用に資する研究 農業分野等との学際的研究も含む）  

## 海外渡航助成

- [Human Frontier Science Program](http://www.hfsp.org/funding/research-grants/information-and-guidelines)
    - Research Grants/Postdoctoral fellowships
    - 3 years
    - 分野横断的であることが要件
    - 採択率は全応募者のうち10--15%程度
- [Endeavour Scholarships and Fellowships](https://internationaleducation.gov.au/Endeavour%20program/Scholarships-and-Fellowships/Pages/default.aspx)
    - Australia
    - 4--6 months
    - 採択率は不明


## 申請書

- [科研費.com](http://xn--w8yz0bc56a.com/) 科研費申請書のコツ。大勢がコツに頼りだすとその業界はおしまいでもある。  



## 物品購入

### 気になる物品

- [CID Bio-Science](https://www.cid-inc.com/) CI-203, CI-710が便利そう？精度が低かったらダメだけど？  
- [JTS-10](http://www.ollie.co.jp/JTS.html) デモをワークショップでみたやつ。  
- [酵素法　食品分析試薬　Fキット](https://premium.ipros.jp/azmax/product/detail/2000166418/) どこかの学会で見たやつ。安価・簡単に成分分析ができる。  

### 中古装置

- [Hightech&Facility](http://www.hitechfacility.co.jp/)  
- [日本電計](http://www.n-denkei.co.jp/)  

### ものづくり

- [野方電機工業](http://www.nogatadenki.jp/) 金属加工。webページがとてもカッコイイ。  
- [(有) サンステップ](http://www.sunstep.net/") プリント基板  

### 便利そうな小物

- [AE-LED56V2](http://akizukidenshi.com/catalog/g/gP-08006/) 小型・安価なLED基板



## 科学哲学

### 4つのなぜ (Nikolaas Tinbergen)

- [ティンバーゲンの4つのなぜ](https://ja.wikipedia.org/wiki/%E3%83%86%E3%82%A3%E3%83%B3%E3%83%90%E3%83%BC%E3%82%B2%E3%83%B3%E3%81%AE4%E3%81%A4%E3%81%AE%E3%81%AA%E3%81%9C)  

### Strong Inference

- [“Strong Inference”について](http://neuro.med.tohoku.ac.jp/japanese/education/yawo_strong%20inference.htm) 真偽だけが重要なときはこれ。  



-------

# 植物科学

## 植物生理学

- [植物生理学・分子生理学コンソーシアムによる陸上植物の高CO~2~応答の包括的解明 (新学術領域研究)](http://www.biology.kyushu-u.ac.jp/~plant/shinryoiki/index.html)  
- [植物の環境感覚：刺激受容から細胞応答まで (新学術領域研究)](http://esplant.net/index.html)  
- [二酸化炭素資源化を目指した植物の物質生産力強化と生産物活用のための基盤技術の創出 (CREST+さきがけ研究領域)](http://www.jst.go.jp/presto/plantsci/)  
- [情報科学との協働による革新的な農産物栽培手法を実現するための技術基盤の創出 (さきがけ研究領域)](http://www.jst.go.jp/kisoken/presto/research_area/ongoing/bunyah27-6.html)  
- [将来の地球環境において最適な光合成・物質生産システムを持った強化植物の創出 (CREST研究課題)](http://hostgk3.biology.tohoku.ac.jp/hikosaka/CREST/index.html)  

### 光合成生理生態学

- [光合成事典 (Web版)](http://photosyn.jp/pwiki/index.php?%E5%85%89%E5%90%88%E6%88%90%E4%BA%8B%E5%85%B8)  
- [光合成研究法](http://www.lowtem.hokudai.ac.jp/plantadapt/photosynthesis_way-j.html)  
- [Sun/Shade acclimation (1988; Special Issue of *Australian Journal of Plant Physiology*)](http://www.publish.csiro.au/nid/103/issue/2664.htm)  
- [Regulation of photosynthetic electron transport (2011; Special Issue of *Biochimica et Biophysica Acta (BBA) - Bioenergetics*)](http://www.sciencedirect.com/science/journal/00052728/1807/8)  
- [Light stress in plants: mechanismsand interactions special issue (2005; Special Issue of *Journal of Experimental Botany*)](http://jxb.oxfordjournals.org/content/56/411.toc)  
- [新光合成 光エネルギー変換システムの再最適化](http://photosynthesis.nibb.ac.jp/)  

### 光形態形成・光質応答

- [Annual Plant Reviews Volume 30: Light and Plant Development](http://onlinelibrary.wiley.com/book/10.1002/9780470988893)  

### Phenotyping

- [Special issue on Computer vision and image analysis in plant phenotyping (2016; Special Issue of *Machine Vision and Applications*)](http://link.springer.com/journal/138/27/5/page/1)  

### 代謝  


### 活性酸素

- [Reactive oxygen species (2006; Special Issue of *Plant Physiology*)](http://www.plantphysiol.org/content/141/2)  

### モデリング

- [Plant modelling: new approaches to an old subject (2010; Special Issue of *Journal of Experimental Botany*)](http://jxb.oxfordjournals.org/content/61/8.toc)  


## 栽培方法について

- [Plant Growth Chamber Handbook](http://www.controlledenvironments.org/Growth_Chamber_Handbook/Plant_Growth_Chamber_Handbook.htm)  


## データ提供

- [ASTER Spectral Library - Version 2.0](http://speclib.jpl.nasa.gov/) 分光分布ライブラリ
- [Natural Phenomena Simulation Group@University of Waterloo](http://www.npsg.uwaterloo.ca/data/leaves.php) 色素の吸収スペクトル  


-------

# 統計学  

- [統計科学のための電子図書システム](http://ebsa.ism.ac.jp/)  
- [統計・データ解析 (奥村先生@三重大学)](https://oku.edu.mie-u.ac.jp/~okumura/stat/)  
- [統計webpages入口 (粕谷先生@九州大学)](http://kasuya.ecology1.org/stats/index.html)  

## 実験計画法

### 分散分析　　

- [分散分析のノート](http://ofmind.net/doc/anova-note)  
- [大森先生@東大農](http://lbm.ab.a.u-tokyo.ac.jp/~omori/) 実験計画法全般、生物統計全般の資料。  
- [ぶんさんぶんせき@中西政志さん](http://ofmind.net/doc/anova-note) Type I~IIIのANOVAの話など。  

### 擬似反復  

- [Pseudoreplication and the Design of Ecological Field Experiments (Hurlbert, 1984)](http://www.jstor.org/stable/1942661?seq=1#page_scan_tab_contents)  
"擬似反復 (pseudoreplication)"というフレーズの初出。良論分。  
- ['Pseudoreplication' problem‐接着したコドラートは何が悪いのか (大垣俊一, 2000)](http://www.mus-nh.city.osaka.jp/iso/argo/nl02/nl02-21-32.html)  
Hurlbertの意見を認めつつ、イケてないHurlbertフォロワーを叩いている。"批判的検討"の項がよろしい。  
- [土壌肥料学における数理統計手法の応用上の問題点 : 4. Pseudoreplicationと繰り返し測定 (山村光司, 1999)](http://ci.nii.ac.jp/naid/110001747104)  
擬似反復による場所差の項の効果への混入の寄与が十分に小さいことを示すことができれば、擬似反復でもOKかもしれない、という考え方も示されている。  

## マルチレベルモデリング
要勉強  

- [Multilevel models: An introduction and FAQs](http://www.bristol.ac.uk/cmm/learning/multilevel-models/)  



## 計算統計  

### マルコフ連鎖モンテカルロ法  

- [マルコフ連鎖モンテカルロ法入門](http://ebsa.ism.ac.jp/ebooks/sites/default/files/ebook/1881/pdf/vol3_ch10.pdf)  
webでフリーのMCMC解説だと一番丁寧な印象。  
- [Review Course: Markov Chains and Monte Carlo Methods](http://users.aims.ac.za/~ioana/)  

### 状態空間モデル、パーティクルフィルタ  

- [データ同化論: 状態空間モデルとシミュレーション (統計数理研究所 公開講座)](http://daweb.ism.ac.jp/koza/koza2008/) パーティクルフィルタに関する資料がいくつかある。  
- [Data Assimilation Seminar Series](http://data-assimilation.jp/en/events/da_seminar/index.html) 理研データ同化チームのセミナー資料など。  
- [逐次モンテカルロ/(粒子|パーティクル|モンテカルロ)フィルタを実装してみた](http://d.hatena.ne.jp/teramonagi/20140525/1400996808) teramonagiさんのBlog。リンクもいくつかある。  
- [生態学分野における状態空間モデルの利用 (2016; 日本生態学会誌)](https://www.jstage.jst.go.jp/browse/seitai/-char/ja/) 



## 統計モデリング

### 一般化線形モデル

- [一般化線形モデル周りのRのパッケージと関数まとめ](http://masaqol.hatenablog.com/entry/2016/03/30/003254)  



## 機械学習

- [朱鷺の杜](http://ibisforest.org/index.php?FrontPage)  



## 時系列解析ネタ

- [こんなグラフがあって「XX時には野生型と変異体で差があります」を言いたいときに使う検定](http://togetter.com/li/939366) "６回を独立とみなす"はダメでしょう。  
- [The curse of big data](http://www.analyticbridge.com/profiles/blogs/the-curse-of-big-data) 時系列を回帰するやつ。



## 統計ネタの多いブログ
- [ryamadaの遺伝学・遺伝統計学メモ](http://d.hatena.ne.jp/ryamada22/)  



------

# R  
- [R for Data Science (R4DS)](http://r4ds.had.co.nz/)  
- [RPubs](http://rpubs.com/)  

## グループ
- [meetingsR](https://github.com/jumpingrivers/meetingsR)  

### JapanRs
- [Japan.R](http://lab.sakaue.info/wiki.cgi/JapanR2010?page=%CA%D9%B6%AF%B2%F1%C8%AF%C9%BD%C6%E2%CD%C6%B0%EC%CD%F7) 更新死んでる  
    - [TokyoR](https://groups.google.com/forum/#!forum/r-study-tokyo)
    - [TsukubaR](http://seesaawiki.jp/w/syou6162/)
    - [KobeR](https://kobexr.doorkeeper.jp/)  

### [HOXO-M - anonymous data analyst group in Japan - ](http://mockquant.blogspot.jp/)

### UseR
- [useR! 2016 international R User conference](https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016)  



## ブログ系
- [R-bloggers](http://www.r-bloggers.com/) もろもろ薄く広く。  
- [RStudio Blog](https://blog.rstudio.org/)  
- [R-statistics blog](http://www.r-statistics.com/)  
- [ほくそ笑む](http://d.hatena.ne.jp/hoxo_m/)  
- [My life as a Mock of Quant](http://d.hatena.ne.jp/teramonagi/)  
- [Technically, technophobic.](http://notchained.hatenablog.com/)  
- [日々是独想](http://blog.kz-md.net/) ぞうさん通信  
- [Hi!!](https://kohske.wordpress.com/)  
- [どんな鳥も](http://d.hatena.ne.jp/tsutatsutatsuta/) 
- [StatModeling Memorandum](http://statmodeling.hatenablog.com/)  
- [盆栽日記](http://d.hatena.ne.jp/dichika/)  
- [もうカツ丼はいいよな](http://rion778.hatenablog.com/)  
- [東京で働くデータサイエンティストのブログ](http://tjo.hatenablog.com/)  
- [廿TT](http://abrahamcow.hatenablog.com/)  
- [まだ厨二病](http://uribo.hatenablog.com/)  
- [INPUTしたらOUTPUT!](http://estrellita.hatenablog.com/)  
- [Rでデータマイニング](http://kanosuke.hatenadiary.jp/)  
- [RWeekly.org](https://rweekly.org/)  
- [Timely Prtfolio](http://timelyportfolio.blogspot.jp/) 金融より。  
- [今週も特にありません 進捗どうですか？](http://masaqol.hatenablog.com/archive/2015) 金融より。  
- [ill-identified diary](http://ill-identified.hatenablog.com/)  
- [a log](http://temp20151223.blogspot.jp/)  
- [teuder's blog](http://teuder.hatenablog.com/)  
- [歩いたら休め](http://kiito.hatenablog.com/)  
- [驚異のアニヲタ社会復帰への道](http://d.hatena.ne.jp/MikuHatsune/)  
- [300億円欲しい](http://gg-hogehoge.hatenablog.com/)  



## まとめ系

### 初心者向けまとめ  

- [R基本統計関数マニュアル (pdf)](http://www.is.titech.ac.jp/~mase/Rstatman.pdf)  
- [初心者のR入門](http://r-beginners.com/) 日本語。  
- [Try R](http://tryr.codeschool.com/) 打ち込み学習。  
- [ujjwalkarn/DataScienceR](https://github.com/ujjwalkarn/DataScienceR) Rでのデータサイエンスのチュートリアル。  
- [Rの設定](http://www.agr.nagoya-u.ac.jp/~seitai/document/R2009/Rsettings.pdf) 環境変数など。

### サンプルデータまとめ  

- [R言語 サンプルデータ一覧](http://www.trifields.jp/r-sample-data-491) Rインストール時に導入されるサンプルデータの一覧と簡単な説明。  

### パッケージまとめ  

- [RStartHere](https://github.com/rstudio/RStartHere) RStudio謹製のHadleyの哲学に従ったオススメパッケージリスト。  
- [awesome-R](https://github.com/qinwf/awesome-R) なんでもありなパッケージリスト。  

### UseR!まとめ

- [2016](https://github.com/rweekly/rweekly.org/blob/gh-pages/draft.md)  



## パッケージ・その他  

### パッケージ作成

- [こわくないRパッケージ開発！2016](http://qiita.com/wakuteka/items/54f81f32baf50e243461)  



### データ解析

#### データハンドリング

##### [dplyr](https://github.com/hadley/dplyr)
Dplyr: A grammar of data manipulation  

- [dplyrを使いこなす！基礎編](http://qiita.com/matsuou1/items/e995da273e3108e2338e)
- [dplyrのmutate_if()とかについて](http://notchained.hatenablog.com/entry/2016/07/01/001836)

##### [tidyr](https://github.com/hadley/tidyr)
Easily tidy data with spread and gather functions  

- tidyr::spreadで複数カラムをwide持ちしたい...
    - [できないっぽい](http://stackoverflow.com/questions/29775461/tidyr-repeated-measures-multiple-variables-wide-format?noredirect=1&lq=1)  
    - `tidyr::unite` -> `tidyr::spread` -> `tidyr::separate`は非常に回りくどい  
    - `reshape2::a/dcast`は使いたくないなぁ

##### [purrr](https://github.com/hadley/purrr)
Make your pure R function purrr with functional programming  

- ベクトルに対して`dplyr`当てたい@r-wakalang
    - `ymd(c("2014-09-01", "2014-10-01")) %>% keep(~ . != "2014-09-01")`

##### [forcats](https://github.com/tidyverse/forcats)
tools for working with categorical variables (factors)  

##### [broom](https://github.com/dgrtwo/broom)
Convert statistical analysis objects from R into tidy format  

##### [chunked](https://github.com/edwindj/chunked)
Chunkwise Text-file Processing for 'dplyr'  
重いデータをメモリに読み込まずに処理する  

##### [rvest](https://github.com/hadley/rvest)
Simple web scraping for R  

- [rvestによるWebスクレイピング](https://book.mynavi.jp/manatee/detail/id=59386)  


#### 作図

##### [ggplot2](http://docs.ggplot2.org/current/index.html)
データの階層構造を活かしたグラフ作成  

- [ggplot2逆引き](http://yutannihilation.github.io/ggplot2-gyakubiki/)  
- [ggplot2 extensions](http://www.ggplot2-exts.org/) 拡張パッケージ

geom_area・geom_barのfill順序をうまいことする

- [How do you order the fill colours within ggplot2 geom bar](http://stackoverflow.com/questions/15251816/how-do-you-order-the-fill-colours-within-ggplot2-geom-bar)  
    - `ggplot(aes(order = ...))`はdeprecated (> 2.0.0あたり)  

ポイント＋関数回帰曲線をggplot2で

- [正規分布など好きな関数の曲線を描きたい](http://qiita.com/hoxo_b/items/a6522a6e6561f8ca7b96)  

ggplot2の軸を対数軸べき乗で

- [ggplot2の軸を上付きのべき乗で書きたい](http://d.hatena.ne.jp/teramonagi/20160327/1459066096)  

facetへ数式を書き込む

- [ggplot2: Adding Regression Line Equation and R2 on graph](http://stackoverflow.com/questions/7549694/ggplot2-adding-regression-line-equation-and-r2-on-graph)  

aes(col)に複数のスケールをマッピングする  

- できないと神が仰る → [Allow several simultaneous colour scales](https://github.com/hadley/ggplot2/issues/578)  

##### Plotly
インタラクティブな作図  

- [plotly for R User Guide](https://plot.ly/r/user-guide/) 全般。  
- [Plotly Shiny Gallery](https://plot.ly/r/shiny-gallery/) Shiny×Plotlyのギャラリー。 

##### rCharts
インタラクティブな作図  

- [rCharts featuring highcharts](https://rpubs.com/kohske/12409) rCharts::hPlot。  



#### レポート

##### knitr
解析の再現性を確保したレポート作成  

- [`knitr` Elegant, flexible and fast dynamic report generation with R (yihui)](http://yihui.name/knitr/)  
    - [bookdown](https://dl.dropboxusercontent.com/u/15335397/slides/2016-useR-bookdown-Yihui-Xie.html)に続く  

##### Shiny
共有プラットフォーム  

- [Shiny-Developer-Conference](https://www.rstudio.com/resources/webinars/shiny-developer-conference/) デブコン  
- [Shiny tips & tricks for improving your apps and solving common problems](http://deanattali.com/blog/advanced-shiny-tips/) 小技のまとめ  
- [Authentication of Shiny-server Application Using a Simple Method](http://withr.me/authentication-of-shiny-server-application-using-a-simple-method/) Shinyでパスワード保護  
    - 予め指定したPWに適合しない場合は表示を抑える、というシンプルな戦略  

- [Shiny app for sun paths and light transmission calculation](http://www6.montpellier.inra.fr/lepse_eng/M3P/PHENOARCH-platform/Applications) Shinyアプリを付けている素敵論文  



#### プレゼンテーション

##### rmdshower

- [rmdshower](https://github.com/MangoTheCat/rmdshower) 



#### GIS

- [leaflet](https://github.com/rstudio/leaflet)
    - [Leaflet for R](https://rstudio.github.io/leaflet/)
    - [地理データをRで可視化：コロプレス図](https://book.mynavi.jp/manatee/detail/id=59406)
    - [leafletではじめるRによる地図プロット](https://rpubs.com/kazutan/leaflet_slide)


## [Bioconductor](https://www.bioconductor.org/)

- [R & Bioconductor Manual](http://manuals.bioinformatics.ucr.edu/home/R_BioCondManual#BIOCONPROGRAMS)  



## Data visualization
- [THE R GRAPH GALLERY](http://www.r-graph-gallery.com/)  
- [計算機は楽し](http://ayapin-film.sakura.ne.jp/PlotUtils/plotutils.html) 可視化ソフトが比較してある (Rはない)  
- [統計グラフの色 (奥村先生@三重大)](https://oku.edu.mie-u.ac.jp/~okumura/stat/colors.html)  
- [The viridis color palettes](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html)  

### Google Chart
- [Chart Gallery](https://developers.google.com/chart/interactive/docs/gallery)  
- [Google Visualization API Reference](https://developers.google.com/chart/interactive/docs/reference)    

### heatmap
インタラクティブなヒートマップ  

- [talgalili/heatmaply](https://github.com/talgalili/heatmaply)  

### Sankey diagram
物質・エネルギーの収支をRで書きたい。  

- [リスト](http://www.sankey-diagrams.com/sankey-diagram-software/) 発見  
- [Sankey Diagrams in R?](http://stackoverflow.com/questions/9968433/sankey-diagrams-in-r)  

### [d3.js Data-Driven Documents](https://d3js.org/)
可視化に強いので手を出したい。いずれ。  

- [D3 Tips and Tricks](http://thedata.co/sites/thedata.co/files/u1/D3-Tips-and-Tricks_Book_v4.pdf)  

### Multidimensional
- [Impressive package for 3D and 4D graph - R software and data visualization](http://www.sthda.com/english/wiki/impressive-package-for-3d-and-4d-graph-r-software-and-data-visualization)

### animations
基本的にアニメーションは正しい理解を阻害する  
ただし、プレゼンで「わかった気にさせる」場合には有効  

- [Improving R animated GIFs with tweenr](http://lenkiefer.com/2016/05/29/improving-R-animated-gifs-with-tweenr)  



## 個別案件

インタラクティブな図をpowerpointへ

- [Embedding R-generated Interactive HTML pages in MS PowerPoint](http://www.mango-solutions.com/wp/2015/02/embedding-r-generated-interactive-html-pages-in-ms-powerpoint/)  

論文っぽい表を出す

- [knitr + マークダウンでクールなLaTeXっぽい表](http://rstudio-pubs-static.s3.amazonaws.com/13917_e79b7454b3ca4819a3255ab2f09d84f2.html)  
- [Rで解析：レポートに便利な表の作成「xtable」パッケージ](https://www.karada-good.net/analyticsr/r-302/)  



## What's

- [Hybrid evaluation](https://cran.r-project.org/web/packages/dplyr/vignettes/hybrid-evaluation.html) →  



-------

# Git/GitHub

- [Gitでやらかした時に使える19個の奥義](http://qiita.com/muran001/items/dea2bbbaea1260098051)  



-------

# TeX
よくわからずやっているので、危うい  
とりあえず、導入した手順を思い出せるよう、時系列でURLログ。  
[RStudioから使えるR Markdownで日本語のPDFを作成する](http://bicycle1885.hatenablog.com/entry/2014/10/15/032024)  
BasicTeXで準備→設定→R Markdownファイルの作成までやっても

> pandoc: pdflatex not found. pdflatex is needed for pdf output.
> Error: pandoc document conversion failed with error 41
> Execution halted
> 
> No TeX installation detected (TeX is required to create PDF output). You should install a recommended TeX distribution for your platform:

だったので、MacTeX (June, 2016; 2.93GB) を導入  


-------

# [Stan](http://mc-stan.org/)

- [Case Studies](http://mc-stan.org/documentation/case-studies.html)  
- [RStan Getting Started (Japanese)](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started-%28Japanese%29)  
- [Using the ggmcmc package](http://xavier-fim.net/packages/ggmcmc/) MCMC系 × ggplot2。使い勝手がよさそうなので。
    - [`[stan] [jags]` ggmcmc でMCMCの事後診断 ](http://ill-identified.hatenablog.com/entry/2016/10/07/233000) 解説と改変版



-------

# プログラミング/その他・全般  

- [コードを書くさいの指針として見返すサイトまとめ](http://qiita.com/kenichi_cc/items/c3ecca7b7d5fc5c6bf2e?utm_source=Qiita%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%B9&utm_campaign=2568ed82eb-Qiita_newsletter_213_06_22_2016&utm_medium=email&utm_term=0_e44feaa081-2568ed82eb-33203329)  



-------

# ソフトウェア  

## Windows系

- [X-Finder](http://www.eonet.ne.jp/~gakana/) → タブファイラ [wiki](http://www29.atwiki.jp/xfinder)



## 文献管理

### BibTeX  

- [BibTeX活用術](http://www.okomeda.net/?BibTeX%E6%B4%BB%E7%94%A8%E8%A1%93)  
- [BIBTEXing：BIBTEXの使い方](ftp://ftp.fau.de/ctan/biblio/pbibtex/base/jbtxdoc.pdf)  
- [bibtex Yamamoto's Laboratory](http://akita-nct.jp/yamamoto/comp/latex/bibtex/bibtex.html)  
- [superscript in my reference--bibtex](http://tex.stackexchange.com/questions/186848/superscript-in-my-reference-bibtex) 下付き・上付きにする
    - {}で囲ってTeXの記法 (e.g. `H{$_{2}$}O`) → [書いた](https://keachmurakami.github.io/lab/2016/06/14/bibtex2.html)  

- [Find and edit CSL citation styles](http://editor.citationstyles.org/searchByExample/) 引用スタイルを探す  



## 数学系

- [Wolfram Alpha](https://www.wolframalpha.com/) 微分積分が苦手なので。



## 画像系

- [O RLY Cover Generator](http://dev.to/rly) O'Reilly本の表紙風の画像作成  
- [画風を変換するアルゴリズム](https://research.preferred.jp/2015/09/chainer-gogh/) DNN風加工  
- [TeXClip](http://texclip.marutank.net/) TeX数式を画像で出力  
- [RoogleVision](https://github.com/cloudyr/RoogleVision) 画像認識



## 動画系

- [GIPHY](http://giphy.com/create/gifeditor) GIF作成  



## 可視化

- [プログラマーが効果的な可視化を作成する](http://qiita.com/keiono/items/9042bf58224ca54bdb45)  
- [データ可視化の実践者が共有すべき知識](http://qiita.com/keiono/items/2dd8228c88abcc4db0b0)  
- [THE R GRAPH GALLERY](http://www.r-graph-gallery.com/)  
- [information is beautiful](http://www.informationisbeautiful.net/)  
- [Deep playground](http://playground.tensorflow.org/) d3.jsで可視化したNN  
- [REGEXPER](https://regexper.com/) 正規表現のマッチングの可視



## 素材

### データ

- [Kaggle Datasets](https://www.kaggle.com/datasets) kaggle  

### 写真・画像

- [Pixabay](https://pixabay.com/) 商用可  
- [Compfight](http://compfight.com/) flickr経由なので出所次第  



## デザイン

- [UI Garage](http://uigarage.net/) UIデザイン集  
- [Web Design Recipes](http://webdesignrecipes.com/) 柔らかめ・Illustratorとか  
- [色彩センスのいらない配色講座](http://www.slideshare.net/marippe/ss-9003317)  
- [ノンデザイナーのための配色理論](http://www.slideshare.net/saucerjp/ss-14902681)  

### 好きなデザイン

- [piccsy](http://piccsy.com/investors/) かっこいい  
- [こわくない Git ](http://www.slideshare.net/kotas/git-15276118) おしゃれ  



-------

# その他

## 考え方など

- [「1秒でも遅れる人」とは「1秒でも仕事しない」方が良い。](http://acthouse.net/meeting) プライベートでの遅刻には寛容  

